### ISSUE TITLE
update

### ISSUE THREAD

**Issue by AnitaStef** [ThemeFuse/Unyson#1026]
Just updated...cannot get into dashboard...HELP!!! I have work to do.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1025

**Comment by danyj** [comment]
@2Fwebd  is the woffice developer and I am sure he will get in this asap.

**Comment by 2Fwebd** [comment]
Hi there, 

Thanks @danyj and @moldcraft ! It's NOT an issue with Unyson.

This is caused by a conflict between our birthdays extension & Buddypress 2.4.0 update from yesterday. 

Good news, it was fixed 2 hours after and we can send you more details here : https://2f.ticksy.com/

For now : 
- You can delete the Birthday extension : wp-content/themes/woffice/framework-customizations/woffice-birthdays once done, you'll have access to your dashboard again. 
- The update is in the Themeforest review queue but your can get the fixed version here : https://woffice.io/updater/

Please if you need any other assistance, feel free to open a ticket on our helpdesk. But it's not an issue with Unyson update. 

Best regards,

2F

**Comment by AnitaStef** [comment]
I am unable to download the update. Nothing there...does not download.

**Comment by azharijelek** [comment]
Guys, a customer of mine just reports this issue few minutes ago. She can't login to her dashboard. Although my theme doesn't have any custom extension for unsyon

**Comment by moldcraft** [comment]
Please give us some error messages (from error.log or enable WP_DEBUG)
