### ISSUE TITLE
Hooks for inserting custom HTML

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1033]
Are there any hooks for inserting custom HTML **before** or **after** tabs, metaboxes, options etc..?

**Comment by moldcraft** [comment]
Can you explain what are you trying to do, why you need such hooks?

**Comment by ikixxx** [comment]
I'm trying to add some custom text above / below some of the metaboxes, or options.
I want to add a video etc...
Currently I'm trying to use `custom HTML` field for it , but that is creating a additional value in the database.
![screenshot_00120151120 t](https://cloud.githubusercontent.com/assets/390700/11307912/7abd3c40-8fbb-11e5-82ce-bbadbdb5f00f.png)

**Comment by danyj** [comment]
You would need to make custom option type http://manual.unyson.io/en/latest/options/create-option-type.html#content
 with html param before/after

**Comment by ikixxx** [comment]
Well that kind of defeats the purpose.
I see two scenarios how this could be resolved.
1.There could be hooks before printing every option. Or at the start and end of metabox.
2.Or there should be a flag on the `custom html` field to be skipped for database insertion.

**Comment by danyj** [comment]
@ikixxx  I was after same thing when I first started using Unyson ( asked exact same question )  in Jan but soon figured out that base is base and anything beyond that should be made by us. And is not hard to do it. 

your idea for the hook is not bad at all  since if we only add a hook we dont have to refactor all options, @moldcraft  might consider it.
