### ISSUE TITLE
What is difference between builder and shortcode decoder?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1053]
@moldcraft  When we first started talking about dynamic CSS I started using this function to get shortcdce attributes 

	function _thz_shortcode_options($data){
		
		$atts = shortcode_parse_atts( $data['atts_string'] );
		$atts = fw_ext('page-builder')->get_shortcode_atts_coder()->decode_atts( $atts );	
		
		return $atts;
	}

now here http://manual.unyson.io/en/latest/extension/shortcodes/index.html?highlight=dynamic#enqueue-shortcode-dynamic-css-in-page-head

I see you use different approach and use per shortcode decoder, so I made this 

	function _thz_per_shortcode_options($data,$shortcode){
		
		$atts = shortcode_parse_atts( $data['atts_string'] );
		$atts = fw_ext_shortcodes_decode_attr($atts, $shortcode, $data['post']->ID);
		
		return $atts;
	}

can you please tell me if there is some ups/downs  in these and which one would be better to use.

Thank you!

**Comment by moldcraft** [comment]
```php
fw_ext('page-builder')->get_shortcode_atts_coder()->decode_atts( $atts )
```

works only with atts encoded with page-builder extension. There are also atts encoded with [`editor-shortcodes`](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/tree/master/extensions/editor-shortcodes) extension, and in the future may appear a new encode method.

Also if you disable Page Builder, your old code will not work.

```php
fw_ext_shortcodes_decode_attr($atts, $shortcode, $data['post']->ID)
```

detects which encode method was used. Post id is needed for the editor-shortcodes decode, because that extension stores all atts in post meta, in `$atts` is just a single key/id that points to that meta.

https://github.com/ThemeFuse/Unyson/issues/469

**Comment by danyj** [comment]
thank you bud. makes sense now.
