### ISSUE TITLE
Is Calypso going to affect us much ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1066]
@moldcraft  do you mind going trough his 
http://ma.tt/2015/11/dance-to-calypso/
and advise if we should end our WP endeavors.  Does not seem like it to me since it affects wordpress.com   but something is just not right with this move. 

See also 
https://crosstec.org/en/blog/854-wordpress-is-going-calypso-time-to-switch-to-alternatives.html

**Comment by moldcraft** [comment]
> http://wesbos.com/wordpress-calypso-react/
>
> WordPress is written in PHP, but the Calypso admin interface for WordPress is written with popular front end tools like React and Lodash.
> ...
> WordPress essentially becomes an API which you can pull and push data from. This decoupling of the view and the backend logic has let the developers of WordPress move much faster because they don’t have 12 years of PHP view logic dragging them down.

```
WordPress (no major changes) [PHP] <--- JSON ---> [JavaScript] New Admin Interface
```

**Comment by danyj** [comment]
thnx  bud , makes more sense now. still bit freaky since Matt did not go in to details like wesbos

**Comment by crosstec** [comment]
WordPress (no major changes) [PHP] <--- JSON ---> [JavaScript] New Admin Interface

^----- only for a grace time

**Comment by danyj** [comment]
@crosstec  what do you mean by that ?

**Comment by crosstec** [comment]
in the long run, WP PHP will be entirely ditched. That's the path they choose to get out of the maintaining hell. For now they are building a bridge between WP PHP and WP Calypso so people get used to things. In the end there will be (if not must be) an interruption.

**Comment by moldcraft** [comment]
> in the long run

any eta?

**Comment by danyj** [comment]
@crosstec  is this personal opinion or do you know ( have resource ) more than we were able to find?

**Comment by crosstec** [comment]
Matt clearly stated it himself:
http://thenextweb.com/insider/2015/11/23/wordpress-com-reboots-from-scratch-to-take-on-medium/

"A lot of people thought we should keep this proprietary, but throughout my life I’ve learned that the more you give away, the more you get back. We still have a ton to figure out around plugins, extensibility, contributions, Windows and Linux releases, API speed, localization, and harmonizing the WordPress.com API and WP-API so it can work with core WordPress. Thousands more PHP developers will need to become fluent with JavaScript to recreate their admin interfaces in this fashion. I’m also really excited to revisit and redesign many more screens now that we have this first version out the door."

He would like to introduce everything to recent PHP devs to get used to things.

There is no estimate but if you read the initial crosstec blog post (about the funding) then I don't think it won't be too long in the future. 

Due to my job I am 90% into Joomla, but I will take that as signal to get more experienced into Node.js. Though I would really liked to see Automattic doing Meteor, it's a lot more robust than raw Node.js & React implementations:

https://meteor.com

**Comment by danyj** [comment]
see this 
http://prntscr.com/99iaug
I am asking him direct question now. lets say what he says.

**Comment by moldcraft** [comment]
If Calypso is so different than current WordPress, maybe better they should create a completely new/separate project and don't touch WordPress, and users will start to switch slowly when it will be released?

**Comment by crosstec** [comment]
FYI: it's planned to "laying an entirely new foundation for a generation of apps and services built on WordPress":

https://developer.wordpress.com/calypso/

Tells me there will be new opportunities.

**Comment by danyj** [comment]
OK , we got an answer 
http://ma.tt/2015/11/dance-to-calypso/#comment-585109

**Comment by danyj** [comment]
I guess his #2 answer

>2. Themes and front-end display of a blog are also still PHP, and there are no plans to change that currently. But plugins will need to evolve to be API-driven.

 would affect Unyson at the end so we must think ahead.

**Comment by moldcraft** [comment]
When there will be official docs how to make plugins API-driven, we will do.

**Comment by danyj** [comment]
>When there will be official docs how to make plugins API-driven, we will do.
:+1:

**Comment by crosstec** [comment]
Hey, sounds good. Still sounds like a transitional period to me but that'd ok, enough time to get used to things.
 
Will update the blog post with his comment, thanks for sharing!
