### ISSUE TITLE
Switch option inside customizer has wrong values.

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1083]
I'm getting different values than provided to the `switch` option, when used inside customizer.
```php
					'animate_logo_2'        => array(
						'type'         => 'switch',
						'value'        => 'enabled',
						'left-choice'  => array(
							'value' => 'enabled',
							'label' => __( 'Yes', 'fw' ),
						),
						'right-choice' => array(
							'value' => 'disabled',
							'label' => __( 'No', 'fw' ),
						)
					)
```
```javascript
    wp.customize('fw_options[animate_logo_2]', function (value) {
        value.bind(function (newVal) {
            var data = JSON.parse(newVal);
            debugger;
        });
    });

```
console when `Yes` option is active (value : `enabled`)
![screenshot_00420151204 t](https://cloud.githubusercontent.com/assets/390700/11603098/921246ea-9adf-11e5-9d6b-8c53b4eacb34.png)

console - when `No` option is active (value : `disabled`) :
![screenshot_00320151204 t](https://cloud.githubusercontent.com/assets/390700/11603063/51f07230-9adf-11e5-8ec8-1463a1e8cc95.png)

**Comment by moldcraft** [comment]
Switch in html is a checkbox. On server side, on save, if it's checked, right choise is used, else left choice

**Comment by ikixxx** [comment]
I understand, maybe add that in the documentation.

**Comment by moldcraft** [comment]
I will try to add in html the actual value, that will not be used, but will be useful in your case.

**Comment by moldcraft** [comment]
Now you should have

```
fw_options[animate_logo_2][json]
```

do

```
var switchValue = JSON.parse(newval[0].value);
```

----

But here is a tricky situation, if someone [extracted the value](http://manual.unyson.io/en/latest/options/introduction.html#live-preview) with

```js
newval[0].value
```

now that value will be different because after this update the `...[json]` input will be first.

I can't put the `...[json]` input last because it will overwrite the previous input values.

Another thing that I can do is **get rid of previous 2 inputs and use only the newly added `...[json]`**, but I am afraid to not break someone's javascript. **Should I do this?** I remember @danyj did some complicated stuff with options and worked directly with their html/js (I don't like at all that approach but we don't have an alternative/standard for that)

**Comment by moldcraft** [comment]
Anyway, I did [the changes](https://github.com/ThemeFuse/Unyson/commit/ef0014bd5b3a0a2651ef58aa1e5f2a5b61e46298), it simplified a lot the logic. I hope it will not break someone's sripts.

So the key is the same (without `...[json]`) `fw_options[animate_logo_2]` but the value is json encoded, you should do `JSON.parse(val)`

**Comment by danyj** [comment]
I noticed this issue long time ago and stooped using this option type as much as I could since you were never able to get the actual value you need , or in some cases you dont get the output at all. Had to go checkboxes  or selects instead.

**Comment by moldcraft** [comment]
Good, then the chances that somebody used the switch in js is low.

**Comment by danyj** [comment]
@moldcraft  No not good,  all multi-picker switch option types dont work anymore

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/multi-picker/static/js/multi-picker.js#L42-L44

**Comment by danyj** [comment]
@moldcraft  works
