### ISSUE TITLE
Post Add/Edit Page Options

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#1088]
I know I can add options for specific post types using this directory structure:

{theme}/framework-customizations/theme/options/posts/{$post_type}.php

But, is there a way to create a global set of options for all post types in a single file?

Thanks!

**Comment by moldcraft** [comment]
It has no sense because you can't create views for all post type (also post types created by other plugins) and use/output those options.

You can use [this filter](https://github.com/ThemeFuse/Unyson/blob/6d069ba5f0f58acb493956dad69403b9ebba965b/framework/core/components/theme.php#L116) to add options to your post types.

**Comment by meta4creations** [comment]
Thanks for pointing me to the filter.

The reason I like to have some global options is to allow custom sidebar layouts (along with other "page styles") for each page/post. This allows me to adjust some visual elements of single posts/pages, even for custom post types added through plugins.
