### ISSUE TITLE
Multiple stylesheets in custom icon sets

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1089]
Hi!
Could I add multi stylesheet source to Custom Icon Set?
For example,
```
$sets['custom_icon'] = array(
        'font-style-src-1' => get_template_directory_uri().'/assets/fonts/fontawesome/style.css',
        'font-style-src-2' => get_template_directory_uri().'/assets/fonts/stroke/style.css',
```

**Comment by moldcraft** [comment]
TODO: `'font-style-src'` should accept array

```php
'font-style-src' => array(
    'style-handle' => 'http://.../style.css',
    ...
),
```

**Comment by llemurya** [comment]
@duongancol you can see this [video](https://www.youtube.com/watch?v=AK3bVx6mSAc&feature=youtu.be) as a tutorial.

**Comment by duongancol** [comment]
@llemurya Thank for your tutor, I'll test it and let you know the result. It's helpfull if we can add more than 2 font icons to custom icon sets.
And I found this problem, in the latest unyson and wordpress, when I use custom icon set in page metabox. It's error with default fontawesome icon.Please see here: http://prntscr.com/9cxxvn. It's normal with custom icon: http://prntscr.com/9cxy8k

**Comment by duongancol** [comment]
I downloaded the 2.4.13 versions but the problem that I said in previous comment is not Fixed.
when I use custom icon set in page metabox. It's error with default fontawesome icon.Please see here: http://prntscr.com/9cxxvn. It's normal with custom icon: http://prntscr.com/9cxy8k

**Comment by llemurya** [comment]
@duongancol please see this [video](https://youtu.be/ZNB-jt2gPIA), for me it works  , the `fontawesome` and `typicons` in the same category works, the problem is that these font icons have different css, and if you pay attention you can see one pixel difference between these two icon sets in one group. I want to know how you see this option type , because it might be changed. As an idea how to combine two font icons in one category without extra css, or maybe make another select or picker or  an controller that will set the one icon from a group of icons. I want to know as an idea or concept how you see this option type. I am waiting for your response.

**Comment by llemurya** [comment]
@duongancol please give an answer.

**Comment by duongancol** [comment]
@llemurya : I'm sorry, I forgot this issue, I'll check it and let you know the answer.

**Comment by duongancol** [comment]
It works on Unyson v2.4.16. Thank for your help @llemurya
