### ISSUE TITLE
Developer tools crashing builder

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1101]
Does any of you have trouble with page builder and developer tools? 
Chrome keeps on crashing if I have builder + popup open and hit F12 , 
now just happened on your testlab http://prntscr.com/9co2w8

Win 10

**Comment by moldcraft** [comment]
I had a similar problem: When there was a few elements in builder, when I opened developer tools my CPU went to 100% and the page freezes, the only solution was to close the tab and open a new one. Now the problem is gone after I updated from Chrome 45 to 47. Also that happened only on my slow office laptop.

**Comment by danyj** [comment]
thnx for the info , I tough I am going crazy here. I am on a monster machine and it is happening many times. v 47....... latest. Just wanted to confirm that I am not alone here. thnx.

**Comment by moldcraft** [comment]
If you know how to detect where actually is the problem in js (if any), it will be good to know and fix it.

**Comment by danyj** [comment]
will try becuase to me it is huge trouble , I cant close the tab , tab is not able to refresh , I must take it out of the tabs to new page , go in task manager , find it and than end task. tis is so annoying especial while I work and have many tabs opened. sure is js but why I dont know , 

in my task manager that tab takes always 5% which is not much , but compared to other tabs being at 0.01% it is big .
