### ISSUE TITLE
Multi-Picker inside customizer is practically unusable. 

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1133]
When used with `postMessage` transport layer.
Inside the customizer, It appears that only the 'multi-picker' option itself can change the `transport` layer to be `postMessage', nested options can't be changed, they get, whatever the top option is having.

There is no way to set the transport layer per option basis inside the `multi-picker`.

Also from javascript, when the value in the multipicker changes, I get back an indexed array, with objects representing all options inside the 'multipicker' , and the array has different length for some reason.

The only reliable way to use the multipicker inside the customizer, is to iterate through actual html elements and get the values directly from them, and then see if and what is changed.
That's a big hack.

**Comment by moldcraft** [comment]
I don't know a solution, sorry.

**Comment by ikixxx** [comment]
Data is getting saved correctly.
But accessing data via javascript so the browser doesn't do a hard refresh is practically impossible.
However I've created two javascript classes to manage communication when multipicker changes.
We need two classes because one class needs to be added to the customizer panel, the other one is added to the theme when the theme is in the customizer (iframe).
So the panel class is monitoring for the change on the picker, and checking which field has actually changed, and then dispatches that data to the iframe (theme is running in the iframe) , and the other class is listening for those events in the iframe, and doing live updates on changed values only.

When I'm done with this class I can post it here so you can review it , and maybe add it to the core or whatever.
