### ISSUE TITLE
[feature request] Portfolio shortcode

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1140]
We have portfolio extension but no portfolio shortcode for the builder. 
Can we get that or instructions how to pull projects out of the extension please.

**Comment by danyj** [comment]
@moldcraft  nothing on this , not even info ?

**Comment by moldcraft** [comment]
It's too late to add `portfolio` shortcode in extension, because a lot of themes already created it and it will conflict or will be 2 portfolio shortcodes.

To create your own portfolio shortcode, try [this](https://wordpress.org/support/topic/filter-portfolio-items-by-categories-in-page-builders-gallery-portfolio#post-7682966)

**Comment by danyj** [comment]
ok , that helps
