### ISSUE TITLE
Contact form not working properly on a customer host.

### ISSUE THREAD

**Issue by giathinh910** [ThemeFuse/Unyson#1148]
Hi.
I'm encountering an issue with contact form on my customer site.

Symptom is: After filling all the info and press submit button, the page reload but there is no flash message return, all the values remain staying in the form fields and no mail was sent.

Config: I try both wp-mail and STMP but the problem persists.

What I did test: I tested mailer using WP Mail SMTP plugin, mail was sent successfully with both phpmail() and STMP configuration.

The contact form is working properly with other customer host. Please let me know if you need more info or login credential.

Thank you.

**Comment by moldcraft** [comment]
Hello,

please send credentials to `moldcraft[at]email.com`

**Comment by moldcraft** [comment]
I added [here](https://github.com/ThemeFuse/Unyson/blob/v2.4.14/framework/helpers/class-fw-form.php#L292) `fw_print($this->get_errors());` and it showed [this](https://static.md/025ef521f934c826147f7a16b2ce753b.png)

Then in in browser console I wrote `_localized_form_errors` and [the errors are there](http://static.md/4821289ec2402fd4b5fe00329b609012.png) so [the problem is in javascript that shows the errors](https://static.md/7cc58f4f7fafa7d21a4a5540381e4d7c.png).

Maybe you uploaded the files via FTP and some files transfers failed.

**Comment by giathinh910** [comment]
Thanks very much for your help.
