### ISSUE TITLE
Inconsistent values when getting customizer options [urgent]

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1151]
Check this out, this is debug session from inside phpstorm:
code:
![screenshot_00120151222 t](https://cloud.githubusercontent.com/assets/390700/11963119/effb630a-a8e4-11e5-877e-4f2bf79a5ce4.png)

```php
$btnTest2                     = fw_get_db_customizer_option( 'fs_panel_4_btn_enabled', false );
$btnTest3                     = fw_get_db_customizer_option( 'fs_panel_4_btn_enabled' );
$allCustomizerOptions         = fw_get_db_customizer_option();
```
variable values:
![screenshot_00220151222 t](https://cloud.githubusercontent.com/assets/390700/11963125/f9184750-a8e4-11e5-9f98-a18b84d045e6.png)

Why am I getting incosistent values ?
If you look at `$allCustomizerOptions` you can clearly see that the value is there (I'm expecting  **enabled** to be the value)

**Comment by moldcraft** [comment]
`fs_panel_4_btn_enabled` doesn't exist in db, the default value is returned if you provide one (first case), else the default values will be extracted from `customizer.php` options (second and third case)

**Comment by ikixxx** [comment]
How can it not be in the database ? 
Are you saying that if I have options on the page, and the user doesn't manually alter the default values of those options, default value will never be saved to the database?
So if I have 10 options on the page, user only changes 4 options. There will be only 4 options in the database?

**Comment by moldcraft** [comment]
Yes

**Comment by ikixxx** [comment]
Is there any particular reasoning behind that ? 
So basically now I have two models where data is stored.
One is the database, the other is the options array itself.

**Comment by moldcraft** [comment]
In customizer is not a regular form submit, on input change the customizer collects via js the values and on "Save & Publish" only those changed values are saved.

I think it's efficient that way.

The solution in your case is simple: just don't specify the default value manually, it will be extracted from options array if db value is empty.

**Comment by ikixxx** [comment]
Is the logic same for theme, post and term settings ?

**Comment by moldcraft** [comment]
The logic is the same, the only difference is that on theme, post and term settings Save is a regular form where on submit are sent all input values. 

But for example you released your theme and after 2 months added a new option in theme settings, in templates you will get that option but on most of user installations it will not exist in db because they saved theme settings a month ago when your new option wasn't there, so the default value will be extracted from options file.

**Comment by moldcraft** [comment]
The logic is the same only in theme settings, the only difference is that on theme settings Save is a regular form submit where on submit are sent all input values. 

But for example you released your theme and after 2 months added a new option in theme settings, in templates you will get that option but on most of user installations it will not exist in db because they saved theme settings a month ago when your new option wasn't there, so the default value will be extracted from options file.

**Comment by ikixxx** [comment]
So in any case, nothing will break if I provide the $default value, or if I just let the framework get the option from db or settings array?

**Comment by ikixxx** [comment]
I'm not embedding your plugin , so I have my own wrapper around your **db helper functions **, so in case your plugin isn't there, i still get some default values back.

**Comment by moldcraft** [comment]
Nothing will break. Better in your wrapper do this:

```
function your_wrapper($option_id, $default_value) {
    if (defined('FW')) {
        return fw_get_db_customizer_option($optoin_id); // note that default value is not specified
    } else {
        return $default_value;
    }
}
```

**Comment by ikixxx** [comment]
Yes, I have something like that :+1: 
Although I have a proxy class that under the hood uses your plugin if it's available, otherwise uses default wordpress functions.

Thanks.
