### ISSUE TITLE
Several issues with portfolio extension featured  image handling

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1153]
Portfolio extension needs some adjustments 

  1 ) Give us an option to disable image resizing .
Right now if you set image sizes in config  all your images are set by that size so masonry layouts 
with different image heights are impossible.  http://theme-fusion.com/avada/3-column-grid/

You cant ever have taller or wider images, even if I use my own image settings set in the portfolio item , the featured image select is croping and resizing  based on the config.php

example : expected image 

![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/11965222/9d8f31a0-a8f3-11e5-9689-e4c4ac7222df.jpg)

outputted image croped  or not croped

![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/11965240/c3d6f99c-a8f3-11e5-853e-94e114d8dcfe.jpg)

 2 ) when you remove featured image ,  you are sometimes left with a -1 entry

![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/11965064/6c17e622-a8f2-11e5-8c96-ca443833512b.jpg)

 3)  When crop is set to false , the sizing should do aspect ratio and not make the image by the size set , example if I have
this in config 

	'featured-image' => array(
		'width'  => 1500,
		'height' => 800,
		'crop'   => false
	),

than image should be max 1500 wide  or max 800 high and not    1500x800 croped somewhere in the middle.

**Comment by llemurya** [comment]
@danyj at the first point you can overwrite your view in the theme portfolio extension ,because this view is a demo you can customize how you want, also you can write your config and get it in the view and work with it.Also you can use other helpers from WordPress or from other sources to crop the images in the view. At the third point can can you describe more detailed what do you mean.The second point I will try to reproduce and fix it. Thanks for contributing . I am waiting for your response.

**Comment by danyj** [comment]
1 and 3 were solved with my view override and I saw the resizing there so I removed id. Thnx.

**Comment by llemurya** [comment]
@danyj I tried to reproduce this bug in different ways , but without success, for me it works.Can you please give me an roadmap how to reproduce it. Thanks.

**Comment by danyj** [comment]
I added image , saved ,  clicked to remove it and saw -1 that is all
