### ISSUE TITLE
Shortcode html title

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#1192]
Hello,

I want to add a HTML tag to the shortcode title.
The issue is that after adding the shortcode to page builder the title has encoded HTML tag, which is not pretty.
After saving the page this issue goes away because I am using ```'title_template' => '{{= title }}'```.

How can I solve this issue before saving page?

**Comment by pear1** [comment]
Update: Is it possible to enable 'title_template' to work instantly after shortcode is added?

**Comment by moldcraft** [comment]
It should work instantly.

I will check it tomorrow.

**Comment by pear1** [comment]
Thank you.
At least for me it is not working.

I also looked inside the console, but there are no error messages or warnings.

**Comment by moldcraft** [comment]
> after adding the shortcode to page builder **the title has encoded HTML tag**

Fixed 

1. https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/2319d1f750abf0ac6a9e08cdf434cfb6accee559
2. https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/c7370979a8729b844674ed4849450aa31dbcd995 

> Is it possible to enable 'title_template' to work instantly after shortcode is added?

No. Because when you add a shortcode it doesn't have any option values (the `o` variable from template would be empty), they appear only after options modal save (after option values are received from server)

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/2319d1f750abf0ac6a9e08cdf434cfb6accee559/shortcodes/section/includes/page-builder-section-item/static/js/scripts.js#L114

**Comment by pear1** [comment]
Thank you.
