### ISSUE TITLE
Auto responders for forms in Unyson

### ISSUE THREAD

**Issue by mattvaluckis** [ThemeFuse/Unyson#1198]
I'm using the Wordpress Theme Campaign and Version 2.4.16 of Unyson. I'm looking for the option to send an auto response email to someone when they fill out a form. I'm not finding a way to do so in the dashboard. Can you help? The site in question is melton2016.com

Thanks,

~Matt

**Comment by moldcraft** [comment]
You can't do that from dashboard because the contact form doesn't have a predefined/required field for user email, you can create a form with any fields (without user email). So the only solution is to hook in to action when the contact form is submitted, extract the user email and send the email, all this manually from code. If this solution would be ok for you, let me know, I will add an action after the form was successfully submitted and send.

**Comment by mattvaluckis** [comment]
That would be great! Thanks so much. I'm not super familiar with coding (enough to be dangerous), so if that is what it takes to make it work, I'll do my best not to fubar it.

Another issue I'm having with the theme is on this page:

http://www.melton2016.com/volunteer/

I can't seem to find the code to recolor the text in black. Also, is there a reason in FF that the radio buttons show up above the text, not next to it?

**Comment by moldcraft** [comment]
I added [this action](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/82e58212f33f9b3c988646135f4535c44094ab9f). If you need more data in it, let me know or make a pull request.
