### ISSUE TITLE
Theme user question

### ISSUE THREAD

**Issue by smillas-snee** [ThemeFuse/Unyson#1200]
Dear Unyson team,
I'm a user of a ThemeFuse theme (not a programmer), and the theme support redirected me here with my question: "Is it possible to add shortcode from third-party plugins in [such brackets] to Unyson Visual Builder pages? How?"
Thank you!

**Comment by danyj** [comment]
You have to get your hands dirty bud, this is how builder shortcodes are made
http://manual.unyson.io/en/latest/extension/shortcodes/index.html#creating-a-new-shortcode

**Comment by smillas-snee** [comment]
Ok, I knew this is no place for beginner, but I had to try :)

**Comment by moldcraft** [comment]
Hello,
Adding `[such crackets]` in the Text Block shortcode [should work](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.8/shortcodes/text-block/views/view.php#L9)

**Comment by smillas-snee** [comment]
Thank you @moldcraft, it worked!

**Comment by pmbrix** [comment]
Hi there @moldcraft,
adding the shortcode in brackets in a text block works. The problem is that the shortcode is read as text in all SEO plugins (like Yoast SEO). Do you have an alternative way of adding the shortcode? (and copying in the code in the text editor breaks the visual page builder)
Any input is welcome (I have spent days on solving this!!!)
thanks
