### ISSUE TITLE
Problem with plugin Unyson 

### ISSUE THREAD

**Issue by TatianaKolotushkina** [ThemeFuse/Unyson#1206]
Hello! It seems that I have a problem with plugin Unyson on my site: http://atanyak.bget.ru/ built on Core ThemeFuse template.
Yesterday evening after I changed one picture on the main page, the main page editor became blanc - the editing field is blanc, the buttons on right sidebar are not responding.
I tried to deactivate Unyson plugin, and on editing field of the main page the raw code appeared. On the web site itself (not admin panel) I saw the same code except the normal view of main page. 
After I activated the plugin, I see again the normal view of main page on website, but editing panel of the main page is blanc again. 
![slice 2](https://cloud.githubusercontent.com/assets/16774501/12414333/004cbec6-bea6-11e5-9aae-762770b240dc.jpg)

Hope for your attention to this problem!
Best regards,
Tatiana

**Comment by alexluncashu** [comment]
Hi Tatiana,

we fixed this in your site.

The problem comes from multiple revisions of the page.
There are few solutions:

 - You can disable revisions by adding this code in `wp-confing.php`:
 
```
define('WP_POST_REVISIONS', false );
```

 - In case you use revisions then you need to remove old revisions, also define in `wp-config.php` the nu,ber of revisions you want to have, by adding this code in `wp-config.php`:
 
```
define('WP_POST_REVISIONS', 5 );
```
 
For future questions, plase open a ticket on ThemeFuse support [page](http://support.themefuse.com/).

**Comment by TatianaKolotushkina** [comment]
Hi Alex! Thank you so so much for your prompt help! Everything's working now :)
