### ISSUE TITLE
ShortCodes via Unison Shortcode Editor not working properly

### ISSUE THREAD

**Issue by apavitt** [ThemeFuse/Unyson#1227]
I am creating Courses, Lesson and Topics in LearnDash by copy and pasting my course material from MS Word documents as it is much quicker creating these using a simple paste into the Visual editor rather than constructing the page with the Visual Page Builder.

However as per the attached capture I am using the Unison Shortcode editor so should this not work also?

I have tried and had problems with adding the following in this way:

Dividers (Blank space and line)
Fileaway

![capturelessonpagecodeviewunison](https://cloud.githubusercontent.com/assets/16840950/12517271/d7177bb4-c129-11e5-8f6b-0001dbf551a8.PNG)
![capturelessonpageview](https://cloud.githubusercontent.com/assets/16840950/12517288/e7775916-c129-11e5-8c11-7e279f7b7d85.PNG)
![capturelessonpagecodeview](https://cloud.githubusercontent.com/assets/16840950/12517293/eb5f1820-c129-11e5-9920-b6548c558a8e.PNG)

I have discovered that when the front end shows as displayed in the screen shot the short code in text editor mode shows:

[file_away fw_shortcode_id="1"]

When according to your link below from https://wordpress.org/support/topic/number-of-base-directories it should read:

[fileaway base=2 sub="Train-the-Teacher/Intro"]

I managed to get something working using only short codes and the text editor:

[fileup base="2" sub="Train-the-Teacher/Lesson1" makedir="true"]

[fileaway base="2" sub="Train-the-Teacher/Lesson1" directories="on"]

This is not understood by the Fileaway Shortcode applet you have built into the visual editor toolbar as shown in the screen capture.

I have shown both these issues to the https://woffice.io/ Theme support and they suggested I reffer to you guys.

**Comment by moldcraft** [comment]
Hello,

Thank you for all the details. But I want to let you know that the [EditorShortcodes](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/tree/master/extensions/editor-shortcodes) was created by a developer who is not in your team anymore. Also it uses a strange way of [encoding](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/includes/coder/class-fw-ext-shortcodes-attr-coder-post-meta.php) shortcode attributes: Instead of `[shortcode foo="bar" hi="hello"]` it creates `[shortcode fw_shortcode="X"]` and moves all attributes data in post meta.

We can't give you any eta when we will inspect and fix this issue, because we have a lot of issues in pending waiting to be fixed. So you can try to inspect extension code yourself or find a developer to help you, then submit a pull request.

**Comment by apavitt** [comment]
Unfortunately I am not a developer myself.  Maybe the people at WOffice will be able to help you.

**Comment by moldcraft** [comment]
We have released the **WordPress Shortcodes** extension, a replacement for the EditorShortcodes extension.
