### ISSUE TITLE
Page Builder topbar error

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1238]
The top bar of Page Builder doesn't work properly. In 'Content Element' tab, it doesn't sticky when I scroll to the bottom. Please check my video here: https://youtu.be/I4P_oKyAjeU .
And in Safari, it's not smooth.

**Comment by moldcraft** [comment]
1. When the toolbar is bigger that half of the screen size, it will not activate sticky because you will have left too little space to work with shortcodes.
2. It's not smooth because we use javascript `scroll` event to update the position, but in some browsers with smooth scroll that event is triggered with delay.

    A solution would be to switch the script logic to set `possition:fixed;` and `top`, `left`, `width` properties, but it's a bit more complicated than current solution that changes only `padding-top`. At the moment I don't have for this, sorry. You can submit a pull request ([code](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/ebd9c1e649a9fa52fc5a15fbe557fc45d849a743/includes/option-types/builder/static/js/initialize-builder.js#L340)).

**Comment by duongancol** [comment]
ok thanks!
