### ISSUE TITLE
Infinite recursion detected fw_get_db_post_option()

### ISSUE THREAD

**Issue by yongkiagustinus** [ThemeFuse/Unyson#1307]
Hi, i got this warning message when editing my custom post type that displaying Unyson metabox

Infinite recursion detected in post type "mycpt" options caused by fw_get_db_post_option() in /####/wp-content/plugins/unyson/framework/helpers/database.php on line 131

**Comment by danyj** [comment]
see this comment https://github.com/ThemeFuse/Unyson/issues/912#issuecomment-145469371

**Comment by yongkiagustinus** [comment]
Thanks @danyj , it solved :+1:

**Comment by olavepablo** [comment]
Hi, good day for all, I have the same problem but in foreach, my code extract:

`<pre>// ... Prev wp query

foreach($posts as $post ) {	

$prods[]	=	array(
'val'				=>	$post->ID,
'title'				=>	$post->post_title,
'data-postid'		=>	$post->ID,
'data-postname'	=>	$post->post_name,
'data-valormeta'	=>	fw_get_db_post_option($post->ID, 'miclave', $vacio),
'atributos'			=>	array(
	'data-idpost'		=>	$post->ID,
	'data-nombrepost'	=>	$post->post_name,
	),
);
}
//...</pre>`
I want to show in data-valormeta the value of each option "miclave" in custom post-type. But I get this error
($vacio is empty variable)

:  Infinite recursion detected in post type "cotizacion" options caused by fw_get_db_post_option() in ...route...\database.php on line 131

I appreciate your cooperation and time, thanks and best regards

**Comment by danyj** [comment]
bud , your $vacio var is nowhere defined thus there is var error plus since it is not there default value for option cannot be set and that produces the recursion error. define your $vacio var and you will be set.

**Comment by olavepablo** [comment]
Hi @danyj ! thanks for your answer but $vacio is global var in my document, I put it in and out of this foreach and the same error appears "infinite recursion..."

sorry for my english, and once again thanks

**Comment by danyj** [comment]
but you forgot to call it. 

    global $vacio

**Comment by olavepablo** [comment]
Hi! Good day @danyj  and thanks for your answer. I changed the function and I put text string as the default value in fw_get_db_post_option(), but the same warning appears when calling _fw_cotizacion_agr_prod()

<pre>
function _fw_cotizacion_agr_prod()
{
$query	=	new WP_Query(array(
								'post_type'			=>	'cotizacion',
								'posts_per_page'	=>	-1,
));
				
$posts	=	$query->get_posts();	
$prods	=	array();
	foreach($posts as $post ) {	
			$prods[]	=	array(
									'val'				=>	$post->ID,
									'title'				=>	$post->post_title,
									'data-postid'		=>	$post->ID,
									'data-valormeta'	=>	fw_get_db_post_option($post->ID , 'miclave', "hola"),
									'atributos'			=>	array('data-idpost'	=>	$post->ID),
			);
	}
return $prods;
}
</pre>

Sorry for inconveniencies, thanks and best regards

**Comment by olavepablo** [comment]
Solved! I created cpt and options metabox again and this warning has disappeared, thanks for all.
I am contributing to the translations of Unyson, and soon will have more active participation in this project.
Thank you for this framework and support
