### ISSUE TITLE
Floating Icon Shortcode

### ISSUE THREAD

**Issue by YaegerDesign** [ThemeFuse/Unyson#1332]
The current Icon shortcode is setup to take up an entire line. There should be an option to "float" the icon so multiple icons can be placed on the same line next to each other.

**Comment by moldcraft** [comment]
Hello,

You can overwrite the shortcode options and view in theme

http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes

**Comment by YaegerDesign** [comment]
Yes, I understand that those can be overridden, but it's not necessarily the best option if adding this feature can benefit everyone. I'm using a ThemeFuse theme, so it seems moot to ask you to override your own theme to overcome a pitfall of your own framework when you can simply modify the framework and have it applied to all your themes.

**Comment by moldcraft** [comment]
We can't add additional options to shortcodes because some themes may have overwritten only the shortcode view and use the built-in options of that shortcode, if we add additional options the view will not be aware of them and will not use them (and the user will be confused that that option doesn't work).
