### ISSUE TITLE
Any RTL support

### ISSUE THREAD

**Issue by ovedmo** [ThemeFuse/Unyson#1344]
the builder is non rtl compatible and align to left...

**Comment by moldcraft** [comment]
You can submit pull request with css fixes.

**Comment by ovedmo** [comment]
it is not just css, this is not the right approach for rtl(ing) this plugin/framwork cause it have to be right not just css... it have lot of shortcodes, addon and more.
it have to be part of the core?!

**Comment by moldcraft** [comment]
Can you make the fixes in framework and send us the changes (as zip or git pull request) ?

Currently we have some rtl support from css contributed by https://github.com/ThemeFuse/Unyson-Framework/pull/1

We don't plan to provide strong rtl support because we don't use it (and don't have time to support it). But we are open for contributions.

**Comment by ovedmo** [comment]
can try! (-:

2016-03-10 10:22 GMT+02:00 moldcraft <notifications@github.com>:

> Can you make the fixes in framework and send us the changes (as zip or git
> pull request) ?
>
> Currently we have some rtl support from css contributed by
> ThemeFuse/Unyson-Framework#1
> <https://github.com/ThemeFuse/Unyson-Framework/pull/1>
>
> We don't plan to provide strong rtl support because we don't use it (and
> don't have time to support it). But we are open for contributions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1344#issuecomment-194727933>.
>



-- 
משה עובדיה
*וובמקס - פתרונות אינטרנט*
*נייד: 054-5758942*
