### ISSUE TITLE
Label sizes to small  in large popup

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1353]
I am on 27" and a large popup option shows smaller  label sizes 

http://prntscr.com/aeaf2e

If I resize  browser to below 1200   they are ok 
http://prntscr.com/aeag7i,  
shouldn't this be other way around?

**Comment by moldcraft** [comment]
"Large" is the biggest size in bootstrap like grid, so we made it as small as possible to prevent too large label on very large screens, to prevent label and input to be very far apart.

![](https://static.md/008f2f472750b2736c34753708e2bd3e.png)

This should work just fine when the options are in page. But when the options are inside modal, this happens: css (media query) for `.fw-col-lg-*` is dependent on window size, but option is inside modal, which has a `max-width` (on large screens it the same as fixed width), so you resize the page, the grid is adapting to the page width, but because the elements are inside a fixed width container, it looks inadequate.

**Comment by danyj** [comment]
this can fix that 


```
@media (min-width: 1200px) {
	.media-frame-content .fw-backend-option > .fw-col-lg-2{
		width:25%;
	}
	.media-frame-content  .fw-backend-option > .fw-col-lg-offset-2{
		margin-left:25%;
	}
	.media-frame-content  .fw-backend-option > .fw-col-lg-10{
		width:75%;
	}
}
```


http://prntscr.com/af4ajk

**Comment by moldcraft** [comment]
P.S. When I [see code like this](https://static.md/dfb818e812088fcee028a4d5f5c31c98.png) I [feel like this](https://www.google.com/search?q=perfectionist+nightmare&tbm=isch)

**Comment by danyj** [comment]
I know how you feel, but I also feel like that when I see that the visual layout does not match on both sides. I just gave you suggestion how the layout should be in popups

**Comment by moldcraft** [comment]
I removed these changes because it breaks element from custom option types from our theme.

`lg-2` is 100/6 = 16.6% so changing it to 25% is wrong because some option types are doing

```
<div class="... fw-col-lg-2"></div>
<div class="... fw-col-lg-2"></div>
<div class="... fw-col-lg-2"></div>
<div class="... fw-col-lg-2"></div>
<div class="... fw-col-lg-2"></div>
<div class="... fw-col-lg-2"></div>
```

**Comment by andreiglingeanu** [comment]
@moldcraft [offtop](http://xkcd.com/1015/)

**Comment by danyj** [comment]
@moldcraft  @andreiglingeanu  pulling jokes is all nice and dandy but how is this going to help us , the labels look like crap in popups and dont match the theme settings no matter how sarcastic or funny you find the issue or proposal. And I dont think I am asking for anything out of line. I pointed to possible solution , if it does not work fine , lest find another that does work without trying to insult or make fun of each other.

**Comment by moldcraft** [comment]
sorry

**Comment by danyj** [comment]
@moldcraft  no need but is appreciated, just trying to find a solution, that's all.
