### ISSUE TITLE
Auto setup

### ISSUE THREAD

**Issue by reardestani** [ThemeFuse/Unyson#1376]
Hi,

I see in one of your premium themes (the core), you use Auto Setup instead of TGM Plugin Activation. Wondering to know, if the script is also free or I should use TGM in my theme?

Can I use that in my theme?

<img width="419" alt="screenshot at mar 22 12-27-33" src="https://cloud.githubusercontent.com/assets/2968507/13945261/7b5b2684-f029-11e5-839c-565705354fba.png">

Looking forward to your feedback,

**Comment by reardestani** [comment]
@llemurya Are you the developer of that? are the codes free to use?

**Comment by alexluncashu** [comment]
Hi reardestani,

Unfortunately, Auto Setup is not part of Unyson because it was exclusively developed for The Core theme. Besides the code within the theme, there are also some configs on server side for this option. 
Maybe we will think later about adding a such extension in Unyson, but I can't promise anything right now.
