### ISSUE TITLE
New color picker option

### ISSUE THREAD

**Issue by mandava** [ThemeFuse/Unyson#139]
How about this New Color Picker thats available in theme customizer?
https://make.wordpress.org/core/2012/11/30/new-color-picker-in-wp-3-5/

**Comment by moldcraft** [comment]
What's the difference between existing color picker?

**Comment by mandava** [comment]
I think the color picker available in customizer is different from Iris? Here is a screenshot of the color picker I'm talking about.  
http://buildwpyourself.com/wp-content/uploads/2014/03/quota-colors.png

.wpColorPicker() and .iris()

**Comment by moldcraft** [comment]
We thought it will be more convenient if the color picker will be an input with the color code *(you can see the code and edit it right away)* instead of a little square that you have to click to see the color code.

----

Do you consider we have to change the `color-picker` option type to this

![staticshot_04-01-2015_20-24-22](https://cloud.githubusercontent.com/assets/1475489/5606988/155dcd04-9450-11e4-8f37-5da21ad64209.png)

instead of input *(like it is now)*

![staticshot_04-01-2015_20-26-33](https://cloud.githubusercontent.com/assets/1475489/5606990/1cf8a174-9450-11e4-9ea0-0fbeeb44fc18.png)

?
