### ISSUE TITLE
Unyson page builder (editor type) + Yoast SEO plugin

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1466]
Hello!
My client reported [this error](https://youtu.be/yQ4CH9iSj78). The page-builder will extremely lag when using text editor shortcode( Visual mode). I disabled all plugins and found this problem happened when activating Yoast SEO plugin. Nothing found in Console browser also.
I need your help to find what exactly happen? 

Thanks!

**Comment by moldcraft** [comment]
He wad a similar problem https://github.com/ThemeFuse/Unyson/issues/859 but it was fixed. The cause was [this](https://github.com/ThemeFuse/Unyson/issues/859#issuecomment-182868741)

But in this case the editor is visible. I will try to reproduce and find the problem.

**Comment by duongancol** [comment]
I've just sent you an email with site account. I think it's easier to reproduce this problem because this doesn't happen on the new page. Please check it! Thanks!

**Comment by duongancol** [comment]
Hi @moldcraft, any news?

**Comment by moldcraft** [comment]
`wp-editor` doesn't work in addable-box, because it tries to init multiple instances with same id.

I tried this option in `framework-customizations/theme/options/posts/post.php`:

```php
$options = array(
	'a' => array(
		'type' => 'addable-box',
		'box-options' => array(
			'b' => array('type' => 'wp-editor',),
		),
	),
);
```

and only first editor is initialized fine

![](https://static.md/db2a21014da37333d96aaa0dc08d2ac6.png)

----

In the latest update from `wp-editor` option-type was removed a lot of hardcode and now it has very minimal custom code, everything is handled by WordPress.

Here is how it works:

1. [`wp_editor()` is called on assets enqueue](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L121-L130) to register the required settings inside WP Editor instance, which later will be javascript localized in page. These can't be hardcoded because other plugins like "advanced tinymce" add features there via WP filters.
2. Editor id is unique, generated [here](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L147-L151)
3. [Second time `wp_editor()` is called](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L62) on render to generate the html
4. For each editor, [default WP init](https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/class-wp-editor.php#L1249) ([scroll to right](https://static.md/b3ef189e53113f4c7be15eeb609164de.png)) is [disabled via filter](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L34-L46)
5. In js [the editor is initialized manually on option init](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/includes/option-types/wp-editor/static/scripts.js#L15-L60) (for e.g. inside options modal), using the settings from `tinyMCEPreInit.mceInit[ id ]` generated by the step 1.

**Comment by moldcraft** [comment]
So I don't know how to fix this. If you'll find a solution, please share.

**Comment by duongancol** [comment]
Ok, thank for your time!

**Comment by moldcraft** [comment]
In next Unyson release will be possible to use wp-editor in addable-box.

[Test it](https://github.com/ThemeFuse/Unyson-Extensions-Approval)

Thanks to @andreiglingeanu

**Comment by duongancol** [comment]
Thank @moldcraft & @andreiglingeanu , I'll test and let you know if it has problem.
