### ISSUE TITLE
Disable one of the tabs in page builder ?

### ISSUE THREAD

**Issue by eyeswizard** [ThemeFuse/Unyson#1534]
is it possible to disable one of the tabs in page builder (Layout Elements, Content Elements, Media Elements) and add a new custom one ?

**Comment by moldcraft** [comment]
Tabs are generated from shortcodes [`$cfg['page_builder']['tab']`](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file). There is no way to disable tabs, because it will be incorrect/strange that shortcodes exists but are not displayed. So better [disable shortcodes](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#disabling-shortcodes) and the tab will disappear if it has no more shortcodes in it.
