### ISSUE TITLE
Can we change page builder output?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#160]
Is there a way to change page builder class names output? 
I see you have own markup but I would also like to add mine. Is it at all possible?
Talking about rows and columns.

**Comment by moldcraft** [comment]
Sure, overwrite this [config key](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/9855e25e68041fac8a715cc182cbd28807d22840/config.php#L13) in your theme http://unyson-docs.themefuse.com/en/latest/extensions/directory-structure.html#content

**Comment by danyj** [comment]
Nice one but the top container is not editable 
![capture](https://cloud.githubusercontent.com/assets/2340172/5691986/1eb71618-98e1-11e4-86b5-6eb5a56196ba.JPG)

**Comment by moldcraft** [comment]
[Here is a filter](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/db2b612b4f7472e1bd278ff5be3d59b49ab46f85/class-fw-extension-page-builder.php#L145) which allows you to edit/remove that class

**Comment by danyj** [comment]
OK , I do see that you guys are using some sort of MVC pattern that is very logic to you but you cant assume that everyone thinks  the way you do. I made same mistake few years back where I was sure that all my customers would understand  me and it backfired. Only when I gave them actual examples it  made sense to them. It was me who assumed, " hey , he/she knows that" .
Even if  "copy_this_here" was so stupid for me to write down, it opened eyes to many of my customers. Not that they were stupid , but they did not know where to begin. 

You guys have beautiful brains but they are yours only and your logic is different than your users logic.  Unyson looks beautiful and from developer view the php code is poetry. Not so perfect on frontend. But how on earth can I make this mine where there are no logic steps or examples. 
Or better yet,  how can I teach my customers to use it (100k+, 70% devs) when I am struggling to understand it myself. I am in biz since about 10 years, 10 joomla (115 templates + 80 extensions )  and last 2 wp and J, trust me when I tell you , I feel like I have never seen a line of code when I try to understand your logic. 

There is no start, 
yes there is middle 

Writhing an article like this 
http://unyson-docs.themefuse.com/en/latest/extensions/directory-structure.html#content

makes no sense to anyone that is trying to extend the framework. 

A simple code example , or an extend bundle that we can use is much more efficient than what you have  there. 

Only file I was able to extend or change is the config.php

than you trow the method that should change the rest of the markup
I try to extend it in my copy of class-fw-extension-builder.php and sure it does not work. 
So it looks like if I want to change anything that starts with fw- in frontend markup I would have to use 10 different files and several filters?

So I am about to trow all of it away.
Don't take any of this personal. I want to spread the word about unyson, I want to use it 150% , but I feel like a moron coming here and asking questions. Docs should save me time , but they dont.

To sum my rant down, this is what I am trying to do

I have my own skeleton , my own grids and columns that I work with for the past 5 years. 
I have my own set of options. 
I have my own css, layouts, js, mega menu. 
I am trying to port this by using unyson. 
So from those 4 "I have's" you can see that I must mess with your core and must extend it.

I dont need unyson frontend css or js, I dont need unyson grid markup . I must make my own work with unyson.  I must HAVE your page builder :) .

If I was going from PSD to unyson it would be easier. But I am porting my framework with my custom options and would love to use unyson for it. I hope you understand me , it is Saturday , I have much on my plate and for the past 4 days I am trying to figure unyson out.

**Comment by moldcraft** [comment]
Thank you for the detailed feedback.

We wrote the docs as good as we could. With time we will realize some gaps that needs to be filled, I think this is normal.

1. Can you please give us a list of main topics that you don't understand?
2. Maybe give us a pattern/rule for how docs should be written (maybe a link to your docs as an example) ?
3. What/how would you change the current documentation (reorganize menu, change the structure of the articles), how would you like to see it?

For now, I will add on [this page](http://unyson-docs.themefuse.com/en/latest/extensions/directory-structure.html#content) examples for how to work with each described file.

**Comment by danyj** [comment]
OK fair enough 

1: Here are things I would like to understand or have example off
* how to change builder options markup. step by step 
* how to change the grid row class names. not only columns but the complete fw-row contents. 
* how to remove unyson css/js in frontend
* is there an array of all theme options or do we have to get them one by one with fw_get_db_ext_settings_option
* how can I use this fw_get_db_ext_settings_option in options admin ? for now im getting  Call to undefined function fw_get_db_ext_settings_option()
* please explain your MVC,, my opinion of MVC is this :
what ever is in plugins/unyson/framework "should" be extendable in themes/themename/framework-customization but apparently there are only few files that work that way. 


2: Here is just an example of my docs which in no way should be a measure for yours , but if you pay attention you can see the way we did it even though the docs are mentioned for devs
http://yjsimplegrid.com/documentation/extend/adding-new-modules-grid.html
Every line in that doc has been tested and if followed step by step you dont have to be a dev to create a grid. 

3:  I am not sure how your docs should be . Looking at it I see that you you did separate them but it could be just me not being able to sum down. Or me being more of a person who learns faster from examples than from reading. 

4  Things you could do
* fix your scratch theme , it comes with some php notifcations bugs , I think something about "slider" option , undefined index
* setup a start folder framework-customizations with all extend examples for developers, 
I see you did it in your video. So just give us that thing. I hate to mention it here ( coding practice compered is not even close to yours ) but redux gives you an admin folder that you copy and get on with it.

**Comment by danyj** [comment]
See this bud , 
This is my markup and columns that I need in frontend
http://jsfiddle.net/6Wb6W/16/
full width http://fiddle.jshell.net/6Wb6W/16/show/light/
Responsive out of the box and as you can see minimal as possible.

**Comment by moldcraft** [comment]
> I try to extend it in my copy of class-fw-extension-builder.php and sure it does not work.

You can't extend/overwrite class files.

It will be not right to do that. The main logic of the extension is in it's class. 
Here is an example:
* We release an extension v1.0.0
* You overwrite extension class (v1.0.0) in your theme
* We fix/change something in the extension and provide an update v1.1.0
* The theme user updates the extension
* The user will still have v1.0.0 because it is loaded from the theme

If you want to change something that is not possible to change, you can request from us to make that thing customizable.

> how to change the grid row class names. not only columns but the complete fw-row contents.

Try to overwrite [this view](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/557989ccf30e0709f448a8b9d1797f06a7ade356/shortcodes/row/views/view.php) (create `framework-customizations/extensions/shortcodes/shortcodes/row/views/view.php`)

> how to remove unyson css/js in frontend

All extensions that has something in frontend enqueue their default asses (through `static.php`) in order to provide basic design (when an user installs Unyson, he must see something nice, not plain html without design).
You can disable any extension assets by overwriting its `static.php` (create the same file in `framework-customizations/extensions/{extension-name}/static.php`) and include your own assets.

Shortcodes also have their own assets (for e.g. ['divider' shortcode `static.php`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/557989ccf30e0709f448a8b9d1797f06a7ade356/shortcodes/divider/static.php)) and you can overwrite their `static.php` in the same way as extensions `static.php` (create `framework-customizations/extensions/shortcodes/shortcodes/divider/static.php`)

> is there an array of all theme options or do we have to get them one by one with fw_get_db_ext_settings_option

Theme Settings options are in `framework-customizations/theme/options/settings.php`, their values can be accessed through [`fw_get_db_settings_option($option_id)`](http://unyson-docs.themefuse.com/en/latest/helpers/php.html#fw-get-db-settings-option), you can call that function without `$option_id` parameter and it will return all options values.

The `fw_get_db_ext_settings_option()` function is used to get an extension settings option value from the database. Some extensions have a settings page with options (for e.g. Page Builder). I don't think in theme development you will need that function, maybe if you will create your own extension in theme that has a settings page.

> please explain your MVC,, my opinion of MVC is this : what ever is in plugins/unyson/framework "should" be extendable in themes/themename/framework-customization but apparently there are only few files that work that way.

The only thing you can overwrite in you theme are [extension files](http://unyson-docs.themefuse.com/en/latest/extensions/directory-structure.html#content)

> how can I use this fw_get_db_ext_settings_option in options admin ? for now im getting Call to undefined function fw_get_db_ext_settings_option()

For what purpose you use the `fw_get_db_ext_settings_option()` function?

----

> how to change builder options markup. step by step includeing extend builder css and js, front and back

Ok, we will add that section in docs.

**Comment by danyj** [comment]
Thank you much for the info and yes I managed to find the way to override all markups, js and css. took me a bit but it did work. about the setting I need db params here is more info. 

In my functions.php I want to remove admin toolbar , like this 
http://davidwalsh.name/hide-admin-bar-wordpress
now I want to add this inside the theme settings to be on/off switch for admins , 
so I need to access that option inside the functions.php and do a simple 

if(fw_get_db_ext_settings_option('disable_toolbar')){

add_filter('show_admin_bar', '__return_false');
}
but as advised I cant "see" the options in functions.php

**Comment by moldcraft** [comment]
> In my functions.php I want to remove admin toolbar , like this 
> http://davidwalsh.name/hide-admin-bar-wordpress
> now I want to add this inside the theme settings to be on/off switch for admins , 
> so I need to access that option inside the functions.php and do a simple

> ```
> if(fw_get_db_ext_settings_option('disable_toolbar')){
> add_filter('show_admin_bar', '__return_false');
> }
> ```

> I added the switch option in my settings.php
> but as advised I cant "see" the options in functions.php
> or better said , I cant see the options in admin area , only in frontend do I get the option output

* The framework is not loaded yet in `functions.php`, so you will get fatal error "undefined function or class" if you will try to use something from framework too early. There is an action called `fw_init` that is fired when the framework is fully loaded.
* Please pay attention to the function name fw_get_db_**ext**_settings_option() this means **extension**, and it is used to get an extension settings option *(and as I said above, I don't think you will have to work with it while integrating themes, it's more for extensions developers)*.
To get a theme settings (`settings.php`) option value, use `fw_get_db_settings_option($option_id)` function.

So your code will look like this:

```php
// file: functions.php

/** @internal */
function _action_theme_hide_admin_bar() {
    if (fw_get_db_settings_option('disable_toolbar')) {
        add_filter('show_admin_bar', '__return_false');
    }
}
add_action('fw_init', '_action_theme_hide_admin_bar');
```

**Comment by danyj** [comment]
ahh, ok the magic bullet. thank you!

**Comment by codalpayalshah** [comment]
No default view (views/view.php) found for shortcode i am facing with error can anyone help to rid out this  issue its very urgent because of this my website stop working.
