### ISSUE TITLE
Unyson extensions

### ISSUE THREAD

**Issue by clusterthemes** [ThemeFuse/Unyson#1601]
Hi. Today in the morning Unyson extensions uninstalled on their own, the website messed up for us and all our customers. This is very annoying having an unstable Framework.

Heard many cases when Unyson deactivates it's own extension. Please fix this.

Thank you.

**Comment by danyj** [comment]
What  is your Unyson version? Please give all environment details including plugins installed.

**Comment by clusterthemes** [comment]
A red message appeared saying: Install theme compatible extensions

Unyson: Version 2.5.5 

Plugins installed: AddToAny Share Buttons, Contact Form 7, MailChimp for WordPress, 	
Slider Revolution

WordPress: Version 4.5.2

**Comment by duongancol** [comment]
weird issue!

**Comment by danyj** [comment]
this is all I know about this https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-131184290
but it was "fixed" long ago

**Comment by danyj** [comment]
@clusterthemes  You hosting with Host Gator?

**Comment by danyj** [comment]
https://wordpress.org/support/topic/i-got-auto-updated-yesterday-broke-my-site-how-to-disable-auto-update

**Comment by danyj** [comment]
see if you have anything like this in your config 
https://wordpress.org/support/topic/i-got-auto-updated-yesterday-broke-my-site-how-to-disable-auto-update#post-6503496

**Comment by danyj** [comment]
interesting , 
https://wordpress.org/support/topic/i-got-auto-updated-yesterday-broke-my-site-how-to-disable-auto-update#post-6847505

    add_filter....

in wp-config is not recommended at all

**Comment by clusterthemes** [comment]
No, I'm with Bluehost

**Comment by clusterthemes** [comment]
No, there is no filter in wp-config

**Comment by ciorici** [comment]
I'm having the same problem, and it happens on different hosting providers: hostgator, even on localhost, so I think it's just a problem with the plugin.

Almost after every update of Unyson plugin, the Page Builder extension is disabled automatically and I have to go to Unyson page and enable it back.

![screen shot 2017-10-13 at 09 45 01](https://user-images.githubusercontent.com/1674706/31533512-5a934902-affb-11e7-8310-278022777a61.png)

It happens on both regular and network WP installs.

This issue is a bit annoying, because if you don't check the website, sometimes after automatic updates of plugins, the page layout get messy unless the Page Builder extension is enabled back.

I'm also having this issue since I started to use Unyson more than 1 year ago, so it happens to me on different installs time from time.

Here's the same problem reported by one of our customer:

![issuepb](https://user-images.githubusercontent.com/1674706/31533672-1a098ee0-affc-11e7-9ca4-ddb1a0faddf1.png)

Thank you.

**Comment by andreiglingeanu** [comment]
Hey @ciorici, that is definitely very strange. It must be something in the update process that somehow mutates the DB value which holds the current active extensions. This has to be checked [somewhere in here](https://github.com/ThemeFuse/Unyson/blob/a1cbbf989ea6d6c0f2c6c3fe56cded0f0822f38a/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L37-L40), this must be a hard-to-catch and very nasty bug.

**Comment by ViorelEremia** [comment]
I tested like [here ](https://gist.github.com/moldcraft/1fe4c3cded8536c66a19)and is fine, before the update unyson create a copy in tmp funtion `theme_available_extensions_copy`, path is definend by constant WP_CONTENT_DIR / tmp, after update   contrary, so here can be many reasons paths, permisions, etc @ciorici can you drop me ftp, admin credentials ( viorel [ at ] themefuse [ dot ] com ) or you can inspect what is happening in [somewhere in here](https://github.com/ThemeFuse/Unyson/blob/a1cbbf989ea6d6c0f2c6c3fe56cded0f0822f38a/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L37-L40)
