### ISSUE TITLE
Multilanguage Plugin Support for Page Builder

### ISSUE THREAD

**Issue by ariona** [ThemeFuse/Unyson#1603]
@moldcraft  It's seems that unyson page builder isn't compatible with any multilanguage plugins since it save the data on custom field.

Any idea for solving this problem? I tried the translation built extension from the repo but it's broken.

**Comment by moldcraft** [comment]
Please give a list of all multilanguage plugins and we will test each if it works or not (if not, why)

**Comment by ariona** [comment]
I just found out that there is different multilanguage plugin method.
I think the one that's not work with Unyson Page builder is the plugin which store the translation in the same post like:

-  qTranslate-X
-  WPGlobus

I use qTranslate-X before, the translation in stored within the same post, I am sure it is stored in custom field. So since the page builder is not content based shortcode but just dynamic json string stored in custom field (Am i right?). This is'nt working properly.

Other multilang plugin that use different post for it's translation is working fine, since it duplicate the post and linked it.

- Polylang
- WPML (i haven't tested it)

I am okay with polylang since i am just starting over my pages & posts. But still this should be resolved for someone that have use first type plugin for a long time.

**Comment by moldcraft** [comment]
> qTranslate-X

How it works:

1. It duplicates the fields for each language:

    ![](http://static.md/c15546f67a933b8d8520eb0d05f30162.gif)

2. In database, each filed is saved in this format:

    ```
    [:en]Hello World![:ro]Salut Lume![:]
    ```

----

Our builder value is saved in a separate post meta, to prevent MySql error when the value is more that 1MB 

* https://github.com/ThemeFuse/Unyson/issues/838
* https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.5/class-fw-extension-page-builder.php#L119
* https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.5/includes/page-builder/includes/option-storage/class-fw-option-storage-type-post-meta-page-builder.php#L13-L58

----

Possible solutions:

1. On every page display, process recursive every shortcode options array and pass the value to qtranslate function.

    That will add too much overhead.

2. Listen javascript events on [qTranslate language switcher](https://static.md/fd5d3b598056f83f8cf5dccaa86f81f8.png) change and switch builder value, so we will need to store multiple builder values for each language in separate post meta only when qTranslate is active, we can't store in one value `[:en]{veryBigJson}[:ro]veryBigJson[:]` because it will reach MySql 1MB limit. But just replacing builder value on language switch is not enough, because the undo/redo functionality will track these changes and you will be able to Undo to previous language while qTranslate is active in another, it is confusing, so the only solution is to create separate instances of builder for each language and hide/show them, the DOM elements ids and names must be prefixed with language name to not conflict (jQuery selectors and POST values).

    There is a lot of work for this and it may cause other problems, so this solution is not good.

So I can sure say that qTranslate is not compatible with Page Builder.

**Comment by moldcraft** [comment]
> WPGlobus

Works [the same](https://github.com/ThemeFuse/Unyson/issues/1603#issuecomment-223597991) `{:en}About Us{:}{:ru}Privet{:}`

**Comment by Sammael1106** [comment]
so how to create multilanguage pages using unyson builder?
