### ISSUE TITLE
Imported Pages not showing page builder content

### ISSUE THREAD

**Issue by ariona** [ThemeFuse/Unyson#1609]
I tried to export my local development pages and importing it on server. But i think the data from unyson framework is not imported property.

- Page builder is not active, all content is missing (I can still see the data in Custom Field) but when the visual page builder is activated,  there only text block.
- All metabox data (From unyson options) is missing/not imported

I have checked the xml, and found all the settings, but somehow it's not imported.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1560#issuecomment-219372596

**Comment by obertscloud** [comment]
why was this closed ?  many users have this problem..  when you export a single page, its there in the xml, but not on the import,  even using a paid version of pro wordpress exporter  still the import is missing the links .. looks like Unyson  uses  child posts (inherit posts) ,  and those are not getting linked or imported or something.. ,  however duplicate page works.. just export and import

**Comment by ariona** [comment]
@obertscloud sadly the WordPress Export/Import plugin is not compatible with Unyson,  so we forced to use backup feature from Unyson.

**Comment by obertscloud** [comment]
ariona - thank you for your response, but the backup feature backs up everything... this is because Unyson has coded not to wordpress codex standards.  more recently a lot of plugins and themes are doing their own thing, breaking the continuity of wordpress.  now we are stuck with a theme we paid for that is broken..  but I would suggest and think that Unyson would be able to enhance their backup to backup selected pages, or selected posts, or other Unyson custom post types.  probably real simple for them.. I noticed in the sql database the inherit posts the link to the parent post for example post id 255..  someone smart with sql, would be able to grab all the content neccessary for the post type and export out and import it back in.. what is sad for us is the money invested in the web design people, we could of chosen another wordpress them that doesn't use unyson and save a lot of money.  hope someone can fix this
