### ISSUE TITLE
mega menu css

### ISSUE THREAD

**Issue by mbtocalli** [ThemeFuse/Unyson#1692]
After installing the Mega Menu extension and create a megamenu in appearance/menu my old menu with dropdowns is broken and new megamenu's submenus are always visible. Should I create my own CSS to make it functional?

**Comment by moldcraft** [comment]
Please give some screenshots and steps to reproduce the problem on our side.

**Comment by mbtocalli** [comment]
Hi moldcraft,
This is the screenshot. ABOUT US was not selected as "mega menu", but PROGRAMS was selected.
This are the steps I followed:
1- install megamenu extension
2- create menu in 'header' location
3- populate the menu, creating submenus and megamenus
4- save it

Should I add a mega menu walker to my functions.php?

![megamenu](https://cloud.githubusercontent.com/assets/10368841/16457484/117c36b0-3df2-11e6-9111-390e644dade6.png)

**Comment by moldcraft** [comment]
MegaMenu extension adds only html classes, you should customize them from your theme http://manual.unyson.io/en/latest/extension/megamenu/index.html

That's why the MegaMenu extension is hidden from extensions list until you set is as supported from your theme, because without customizations it is useless.
