### ISSUE TITLE
Form builder items are hard coded

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1738]
I'm customizing the views of the `form-builder` extension, which is fine but I find them hard coded in the class, I cannot add/change the default options. For instance I would like to have a `min-height` option for the textarea or allow users to set a very specific class to the form fields.

I would recommend having them the usual way:
- `framework-customizations/extensions/forms/form-builder/items/radio/views/view.php` for the front-end view
- `framework-customizations/extensions/forms/form-builder/items/radio/static.php` for the front-end view static files
- `framework-customizations/extensions/forms/form-builder/items/radio/options.php` for the item options

**Comment by thednp** [comment]
Also it would be super nice to be able to customize the form error messages in a template, with the ability to control where they show up in the `form.php` view.

**Comment by moldcraft** [comment]
I can't allow options overwrite because there are required options in class logic used in validation rules

* https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/6ac5e4df78b3e20851198d35c4efb1f2300e4b72/includes/option-types/form-builder/items/number/class-fw-option-type-form-builder-item-number.php#L228
* https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/6ac5e4df78b3e20851198d35c4efb1f2300e4b72/includes/option-types/form-builder/items/number/class-fw-option-type-form-builder-item-number.php#L315-L316
* https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/6ac5e4df78b3e20851198d35c4efb1f2300e4b72/includes/option-types/form-builder/items/number/class-fw-option-type-form-builder-item-number.php#L412-L413

So I added [the possibility to add options at the end of the options](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/6ac5e4df78b3e20851198d35c4efb1f2300e4b72)

**Comment by moldcraft** [comment]
> `framework-customizations/extensions/forms/form-builder/items/radio/static.php`

I will add that later.

**Comment by thednp** [comment]
Thanks for the updates.

**Comment by moldcraft** [comment]
> Also it would be super nice to be able to customize the form error messages in a template, with the ability to control where they show up in the form.php view.

It is a bit complicated. You can do the following:

1. Hook into this action and save `$form->get_errors()` in a global variable. But make sure to check [form id](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/6ac5e4df78b3e20851198d35c4efb1f2300e4b72/class-fw-extension-forms.php#L23) to not affect other forms.

    ```php
    if ($form->get_id() === 'fw_form') {
        global $my_form_errors;
        $my_form_errors = $form->get_errors();
    }
    ```

2. In form item views check the global variable if there is an error for current item then display it.

**Comment by thednp** [comment]
> Hook into this action...

Sorry, which action are you talking about?

**Comment by moldcraft** [comment]
Sorry, forgot to put the link. [Comment](https://github.com/ThemeFuse/Unyson/issues/1738#issuecomment-238222718) updated

**Comment by thednp** [comment]
After more than a year, this is still a thing: the errors look terrible in comparison with the rest of the form and it even adds a `<style>` tag into the site `<head>`.

Come on guys, give us a proper template view for the errors.
