### ISSUE TITLE
Is there a field number?

### ISSUE THREAD

**Issue by eyeswizard** [ThemeFuse/Unyson#1759]
i searched in the documentation for the number field (input type number) but i didn't found it.
Is there a field number?

also there is no padding or margin fields like this : 
![](http://i.imgur.com/6kGuJ9e.png)

Do we will have these features in the future ?

**Comment by moldcraft** [comment]
Hello,

We don't have these options and there are no plans to add them in future.

You can [create your own option-types](http://manual.unyson.io/en/latest/options/create-option-type.html#content)

**Comment by thednp** [comment]
Hint: 
* copy code from `text` option-type (I think this is in the main class file, but you get an idea on other option types)
* find-replace the right stuff
* test it

**Comment by eyeswizard** [comment]
thank you,
i made it before but i'm asking for an official field not my own

**Comment by thednp** [comment]
If it's that important for the community, then it's coming. I asked about a better Google font option type and we got one, a much better one, but it came after quite some time.

**Comment by thednp** [comment]
I am following the development since 2014 and I know there was a boom in the beginning: 
* lots of extensions have been developed (events, sliders, backup, megamenu, etc)
* many bug fixes and Wordpress updates related issues
* improvements all cross the board

Today we have a clear focus on what is important for the community:
* we know what are the extensions that matter the most and devs discontinued most un-important ones 
* we all want a stable and lightweight core
* we all want maximum flexibility in templating

Over time we're gonna have all the tools **everyone** need, just we need to not lose focus on the important aspects and I am happy about it, I got to learn more PHP doing custom option types myself. I even do a small tutorial how to do this and that from time to time, and post it here for the community.

**Comment by warudin** [comment]
It'd still be nice to have a default field limited to numbers only.
