### ISSUE TITLE
[Question] Use CSS Helpers

### ISSUE THREAD

**Issue by Xyr2** [ThemeFuse/Unyson#178]
In the Documentation it says:

Useful css classes for admin side. To use these helpers, add fw to your style dependencies:
wp_register_style(..., ..., array('fw'));

Where do I have to add this, and what exactly do I have to replace the dots for?

Thank you!

**Comment by moldcraft** [comment]
```php
wp_register_style(
    'your-style-id',
    'https://your-domain.com/path/to/your/style.css', 
    array('fw')
);
```

or

```php
wp_enqueue_style(
    'your-style-id',
    'https://your-domain.com/path/to/your/style.css', 
    array('fw')
);
```

**Comment by Xyr2** [comment]
Hey moldcraft,

thanks for your fast reply!

I added
```php
wp_enqueue_style('fw', plugins_url() . '/unyson/framework/static/css/fw.css');
```
to my functions.php and its working. But I'm not sure if this is the right attempt..

If I just add
```php
wp_enqueue_style('fw'); 
```
its not working.

Have I done it right? If yes, is there a way to remove the fw-ext-builder-frontend-grid-css when the Page Builder is used? Because then the grid classes are there 2 times..


And for the record, this framework is really awesome, well done :)

**Comment by moldcraft** [comment]
This

```
wp_enqueue_style('fw', plugins_url() . '/unyson/framework/static/css/fw.css');
```

overwrites [this](https://github.com/ThemeFuse/Unyson/blob/ccce0cb3b10d5a6d81a792a95e563aeefa839c48/framework/core/components/backend.php#L230). It's not the right way to do it.

> If I just add
>
> wp_enqueue_style('fw');
>
> Have I done it right?

No. Admin styles and scripts must to be enqueued on the `admin_enqueue_scripts` action or later (it's not correct to enqueue them earlier). Just adding that code in functions.php doesn't work because the style is not registered in that moment. The right way to do it:

```php
// file: functions.php

/** @internal */
function _action_theme_admin_enqueue_scripts() {
    wp_enqueue_style('fw');
}
add_action('admin_enqueue_scripts', array('_action_theme_admin_enqueue_scripts'));
```

This will enqueue the style on all admin page, I think this is not good. Better to enqueue it only on the pages where it is used.

> is there a way to remove the fw-ext-builder-frontend-grid-css when the Page Builder is used? Because then the grid classes are there 2 times..

Yes. Overwrite [`unyson/framework/extensions/builder/static.php`](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/static.php) in your theme by creating and empty file `{your-theme}/framework-customizations/extensions/builder/static.php`.

> And for the record, this framework is really awesome, well done :)

Thank you :)
