### ISSUE TITLE
Get page content for PDF Builder Plugin

### ISSUE THREAD

**Issue by huepfmonster** [ThemeFuse/Unyson#1798]
Hey There,
I am using a Theme built with Unyson. Now I want to offer PDFs of the pages by using the Plugin "PDF Generator Lite", but when I do that, all pages are empty.
It fetches the content like this:
```
function SSAPDF_getPageContent($page_id) {
	$page_data = get_page($page_id); 
	$content = apply_filters('the_content', $page_data->post_content);
	return $content; 
}
```

Seems like the correct way to me - but which function can I use to get the content built with unyson (has to be outside the loop, because the plugin specifies page IDs)?

Best Regards
Jakob

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1755#issuecomment-231714979

**Comment by moldcraft** [comment]
When the PDF is built, the posts are fetched [here](https://plugins.trac.wordpress.org/browser/pdf-creator-lite/tags/1.2/scripts/build-pdf-admin.php#L123) not

**Comment by moldcraft** [comment]
When the PDF is built, the posts are fetched [here](https://plugins.trac.wordpress.org/browser/pdf-creator-lite/tags/1.2/scripts/build-pdf-admin.php#L123) not in `SSAPDF_getPageContent($page_id)` as you said. I found [a filter which is executed at that time](https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/post.php#L4558) and now the PDF is generated with page content.

Unfortunately we will release an update for PageBuilder extension a bit later because it contains some major changes and we need to test it better.

**Comment by moldcraft** [comment]
This is the fix https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/540c14ec16763902c5e24eb436df1006747d0387
