### ISSUE TITLE
[Icon-v2]Not working on hosting

### ISSUE THREAD

**Issue by ttn10** [ThemeFuse/Unyson#1848]
Hi,
i added `ionicon` font into `icon-v2` type, but this only woking in local. not working on hosting.
please check images:
on local: http://i.imgur.com/UV88bYf.png
on hosting: http://i.imgur.com/yU7YuS2.png

**Comment by duongancol** [comment]
Oop! The same problem here.

**Comment by andreiglingeanu** [comment]
@ttn10 Can you give me your credentials via `andrei.glingeanu@gmail.com`?

**Comment by andreiglingeanu** [comment]
To be honest, I've faced this issue one time on my local setup but I'm pretty sure I've fixed it. Just let me know if you have a clear steps to reproduce the problem and we'll work it out.

**Comment by ttn10** [comment]
I have `options` in shortcode `button`:

> 'icon' => array(
	'type'  => 'icon-v2',
	'label'   => __( 'Icon', 'text-domain' ),
	'modal_size' => 'large',
	'preview_size' => 'sauron',
)

and in function.php file, i added:

> function ionicon($default_packs) {
    return array(
      'ion-pro' => array(
        'name' => 'ion-pro', // same as key
        'title' => 'Ionicon',
        'css_class_prefix' => '',
        'css_file' => get_template_directory_uri().'/css/ionicon.min.css',
        'css_file_uri' => get_template_directory_uri().'/css/ionicon.min.css',
      )
    );
}
add_filter('fw:option_type:icon-v2:packs', 'ionicon');

**Comment by andreiglingeanu** [comment]
@ttn10

Correct way of doing it:

```php
function ionicon($default_packs) {
  return array(
    'ion-pro' => array(
      'name' => 'ion-pro', // same as key
      'title' => 'Ionicon',
      'css_class_prefix' => 'ion',
      'css_file' => get_template_directory() . '/css/ionicon.min.css',
      'css_file_uri' => get_template_directory_uri() . '/css/ionicon.min.css',
    )
  );
}
add_filter('fw:option_type:icon-v2:packs', 'ionicon');
```

<hr>

You mistyped `get_template_directory` with `get_template_directory_uri` for the `css_file`. Please ensure that you really have your file at the correct place. That's mandatory for the `icon-v2` to be able to pick up your easily. Otherwise you will have to list your icons like [this](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/icon/class-fw-option-type-icon.php#L203).

<hr>

Please re-open if this one doesn't help too much, but I'm pretty sure it'll work correctly.
