### ISSUE TITLE
Demo data installation issue

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#1882]
One of my client tried to install demo content and getting this error.

Call to undefined method SplFileObject::seek() in /home/scotchlv/public_html/mamba/wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php on line 135"

**Comment by moldcraft** [comment]
> class-fw-ext-backups-task-type-db-restore.php on **line 135**

Your client doesn't have the latest version of Backup & Demo Content extension because that method is called at [line 151](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.11/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L151)

> Call to undefined method **SplFileObject::seek()**

http://php.net/manual/en/splfileobject.seek.php is available in PHP 5.1. Your client has php 5.0 or the hosting limited access to that method.
