### ISSUE TITLE
Widget that inherits the functionality from shortcode (wrapper)

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1916]
For a while now we can use Unyson shortcodes in the WP editor. And even longer, you can use widget areas in the pagebuilder.

But: is there a way to use Unyson shortcodes in a sidebar as a widget?

The shortcode with its functions is a lot more advanced than the standard possibilities that WordPress offerst.

**Comment by moldcraft** [comment]
For e.g. to set in a config which shortcodes you want to be registered as widgets?

**Comment by noesteijver** [comment]
I've made several custom shortcodes that I would like to use as widgets. 

I came across another thread with 2 options, one via an extension, the other loads the fields directly via a custom widget. 

The nicest way to do this is to load the fields directly via a custom widget. But the example I've found isn't working correctly yet. In the thread I saw you say that you are planning on releasing something for this. Has this happened yet?

The thread I found: https://github.com/ThemeFuse/Unyson/issues/568.

**Comment by moldcraft** [comment]
Ho, I haven't done anything related to that.

**Comment by moldcraft** [comment]
I can't give you any eta.

**Comment by noesteijver** [comment]
I'm sorry, I misread something. You didn't say that. 

Is what I'm asking very different from the two solutions that are posted in the thread I mentioned before?

**Comment by moldcraft** [comment]
Please explain again as short as possible what you want to achieve, how it should work?

**Comment by noesteijver** [comment]
Actually, it's exactly what the title says:

At the moment I can easily make a shortcode that uses Unyson option types. It would be nice to be able to use a shortcode that I made as a widget in a sidebar.

**Comment by andreiglingeanu** [comment]
@noesteijver I don't know how those `WP_Widget` objects really work, but I assume there should be a way to trick `form()` method to output an Unyson popup. And this popup should save its data into one `hidden` field.

Then, the `widget()` method is the one who do the work of doing HTML output. What's hard about rendering a shortcode manually at this point? Be sure to use [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/62#issuecomment-233979434) method in order to also enqueue statics correctly.

<hr>

I don't have time right now to come up with a demo for this, but it should be not that hard to assemble by yourself. If you'll have more questions - be sure to write them up here.

**Comment by noesteijver** [comment]
@andreiglingeanu I wouldn't really want to use it in a pop-up. The best solution would be, in my opinion, that I can use Unyson option types directly in a custom WP_Widget instead of the 'standard fields'. That way I can use the shortcode (= collection of option types) code for my widget. And that will save me a lot of work because I don't have to rewrite my shortcode too much.

 In [this thread](https://github.com/ThemeFuse/Unyson/issues/568) near the end, someone came up with a solution that almost works. But there are some issues with javascript that need resolving.
