### ISSUE TITLE
Shortcodes icon only appears when page builder is activated for particular post type.

### ISSUE THREAD

**Issue by nickcoupland** [ThemeFuse/Unyson#192]
This might be deliberate but I was just curious if the shortcodes toolbar icon is only to appear when the page builder is activated for a particular post type. For example if I want to use the shortcodes tool on my blog posts I have to have page builder enabled for blog posts. Is this how the functionality should work?

Also after a recent update I've noticed the styling for settings tabs to be buggy by including multiple borders incorrect padding.

**Comment by sergiubagrin** [comment]
> Also after a recent update I've noticed the styling for settings tabs to be buggy by including multiple borders incorrect padding.

Can you give me a screen. I tested on my side and it is working fine. Try to disable all plugins and activate default Wordpress Theme

> This might be deliberate but I was just curious if the shortcodes toolbar icon is only to appear when the page builder is activated for a particular post type.

Yes. Editor ShortCode use the same shortcodes like page buider. I decided to add it to page builder because it is more easily to explain users from my point of view how to activate more options for pages with one extension. 

This is the second question today: https://github.com/ThemeFuse/Unyson/issues/191

If you have an example/opinion why we need to create 2 different activate/deactivate boxes add it in a reply.

Thanks
