### ISSUE TITLE
Question about performance of accessing db data

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1927]
While looking at another problem #1905 I've notices that `fw_get_db_customizer_option` function has a lot of stuff going on inside, and honestly I have no idea what that code does.
So my question is:
What is the best way (performance wise) to acces unyson data?
I'm using the customizer here ,but the question is the same for all other functions used to access data.

1. Get it all at once.
```
$all = fw_get_db_customizer_option();
// make $all variable global add access data from there
```

2. Get one option at a time 
```
$option = fw_get_db_customizer_option('option_id', 'default_data');
```

Also is there a performance hit if we supply `default` data and if we don't ?

**Comment by moldcraft** [comment]
1. Db values set and get happens [here](https://github.com/ThemeFuse/Unyson/blob/7ab6b68d842109dab4660aa4c2c1f8014aea5747/framework/helpers/database.php#L518-L524)
2. The set is called every time you call `fw_set_db_customizer_option()`
3. The get is called ideally only once, because they are [cached](https://github.com/ThemeFuse/Unyson/blob/7ab6b68d842109dab4660aa4c2c1f8014aea5747/framework/helpers/class-fw-db-options-model.php#L117-L123) after first get

For sure the fastest is to get all values in a variable and the use that variable (1.) but I haven't done any tests to see actually how fast it is. When you call `fw_get_db_customizer_option('option_id')` [this code is executed](https://github.com/ThemeFuse/Unyson/blob/7ab6b68d842109dab4660aa4c2c1f8014aea5747/framework/helpers/class-fw-db-options-model.php#L102), it is not heavy, so I think that `fw_get_db_customizer_option('option_id')` is more convenient than `$all = fw_get_db_customizer_option()`.

Default value prevents the script to extract default values from options array, when you set a default the executions ends [here](https://github.com/ThemeFuse/Unyson/blob/7ab6b68d842109dab4660aa4c2c1f8014aea5747/framework/helpers/class-fw-db-options-model.php#L129-L150).
