### ISSUE TITLE
Builder is going crazy. 2 Bugs

### ISSUE THREAD

**Issue by Alex-Ascet** [ThemeFuse/Unyson#1982]
Hi team,

The builder is switching to Default Editor on its own on some pages (the page type is totally random). See video. The video displays 2 browser refresh. The builder appears then disappears. No shorcodes, just plain text in Default Editor. This is happening since the last update 2.6.1 
https://frenchyweb.com.au/wp-content/bug-builder.mov

Another bug, this was an old bug that has been fixed months ago but it just appears again on one of my website after the last update. 2.6.1
https://frenchyweb.com.au/wp-content/bug2.png

All up to date of course.

Thank you

**Comment by asklunddesign** [comment]
I have the same problem. But my original text doesn't show at all, in admin. But it works fine for the viewers.

**Comment by Alex-Ascet** [comment]
When I Deactivate the "Wordpress Shortcodes" the builder does not appear at all. I hope it helps.

**Comment by moldcraft** [comment]
Can you give me admin/ftp access? `moldcraft[at]email.com`

**Comment by moldcraft** [comment]
> The builder appears then disappears.

This happens every time on builder initialization.

> No shorcodes, just plain text in Default Editor.

We have fixed those 2 shortcodes.

----

Please check and let us know if there are any problems.

**Comment by Alex-Ascet** [comment]
Hi @moldcraft,

I cannot see any changes. Did you look at the dashboard? (Links into my email) I have got content on the page (front end) but nothing shows up in the editor and I cannot switch between Visual Builder and Default Editor, the blue button is not here anymore. Annoying. The client wants to edit this page and cannot. Please advice.

**Comment by Alex-Ascet** [comment]
Same issue on another website:
http://45.32.245.2:8080/oconnorscaseih.com.au/precision-ag/
I email you the login details.

We have got around 70 websites running with Unyson at the moment and clients start to discover that some pages does not show up the builder anymore even with content on the page.

Thank you for your support.

**Comment by Alex-Ascet** [comment]
Actually, the page template in use is the "Default Template" but it displays an empty builder...
I think with issue comes up when we are using shortcodes into the Default template. Maybe it is because of the new Wordpress Shortcodes extension. The websites involved have been created BEFORE the Wordpress Shortcodes extension. I hope it helps.

**Comment by Alex-Ascet** [comment]
So indeed, when I disable the "Wordpress Shortcodes" extension the switch button comes up... I hope it helps.

**Comment by Alex-Ascet** [comment]
Ok so, after investigation here is the process of this issue:

1- Websites created before the "Wordpress Shortcodes" extension
2- Pages involved, Defaut Editor with shortcodes from Unsyon. 
3- When "Wordpress Shortcodes" is activated an empty builder appears on a "Default Template". No more switch blue button "Visual Builder" "Default Editor".
See > https:frenchyweb.com.au/wp-content/WS_activated.png
4- When "Wordpress Shortcodes" is disabled everything is back but of course all the shortcodes are in plain text and are not interpreted anymore.
See > https:frenchyweb.com.au/wp-content/WS_disabled.png

We have got many website (60) build before the "Wordpress Shortcodes" extension realised, I really hope you will be able to help here. Thank you in advance.

**Comment by moldcraft** [comment]
Regarding this site http://45.32.245.2:8080/oconnorscaseih.com.au/precision-ag/

1. We have released extension updates but **Dashboard > Updates** showed nothing. This is our fault, because v1.0.0 was release without update support, [it was added later](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/commit/b90b9a024816b011e80109887438b9c9f395d211).
2. On that site is installed WordPress Shortcodes v1.0.0, but latest stable release is 1.0.2 https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/releases

    ![screenshot from 2016-09-13 11-58-27](https://cloud.githubusercontent.com/assets/1475489/18468432/9de28f3c-79ac-11e6-9e37-57ca81c7c95b.png)

3. I reinstalled WordPress Shortcodes extension and now it is latest version
4. The fix for this problem is [this](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/commit/c171d0a89699d936f0b9245858f00b3bdc3ae424). I applied it manuall

    ```
    {site-url}/wp-admin/plugin-editor.php?file=unyson%2Fframework%2Fextensions%2Fshortcodes%2Fextensions%2Fwp-shortcodes%2Fstatic%2Fjs%2Fplugin.js&a=te&scrollto=3233
   ```

    and now everything works fine.

----

How to solve this.

1. I released now a new version of WP Shortcodes extension[ v1.0.3](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/releases/tag/v1.0.3) which includes [this fix](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/commit/c171d0a89699d936f0b9245858f00b3bdc3ae424). The update will be fully available for all clients tomorrow (it is cached in WP transient for 24 hours, to reset the cache you must go to Dashboard > Updates > press the Check Again button, but unfortunately this will not work for the clients who has v1.0.0 installed)
2. The clients who have this problem must reinstall the WP Shortcodes extension tomorrow.
3. If it's urgent, you can install the latest extension manually:

    * [Download](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/releases/tag/v1.0.3) it
    * Extract in

        ```
        wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/wp-shortcodes
        ```

We are very sorry for this bug. To prevent such cases please [test extensions before they are released](https://github.com/ThemeFuse/Unyson-Extensions-Approval).

**Comment by Alex-Ascet** [comment]
Thanks a lot Moldcraft. A very good support that confirm we made a good choice by working with Unyson and Theme Fuse. I am going through all our website to check the version installed. All the best.

**Comment by andreiglingeanu** [comment]
🎉
