### ISSUE TITLE
Were there any changes to popup/modal  in 2.6.2

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1998]
@andreiglingeanu  @moldcraft  

Where there any changes to fw.modal or popup option type lately? ( I cant seem to find any ) 
When modal was opening data was coming as json and I used to do json_decode , now is coming as array. 

Please advise. Thnx!

**Comment by moldcraft** [comment]
> When modal was opening data was coming as json

Where? How to test? Again, steps to reproduce.

**Comment by andreiglingeanu** [comment]
Actual BUG in `addable-popup`:

```php
'a' => array('type' => 'addable-popup', 'popup-options' => array('b' => array('type' => 'text')))
```
1. Add an `addable-popup` with any option.
2. Open the modal
3. Save
4. You'll see _two_ options being inserted.

<hr>

Solution:

That's because [by default](https://github.com/ThemeFuse/Unyson/blob/v2.6.4/framework/static/js/fw.js#L1164), `silentReceiveOfDefaultValues` option is `false`, which makes the [setting of `default_values`](https://github.com/ThemeFuse/Unyson/blob/v2.6.4/framework/static/js/fw.js#L1319-L1326) to 
generate an false positive `change:values`.

@moldcraft Didn't wanted to make it `true` by default because I thought it may introduce some problems. It'll be used in the context of other events, that is it doesn't matter that much whether it generates or not a `change:values` event.

**Comment by danyj** [comment]
yes, just saw this to now , click on addable popup button ,   close it without saving , addable popup is added

**Comment by noesteijver** [comment]
I guess the same behaviour is appearing on addable options..

**Comment by danyj** [comment]
There is new issue with addable popups ,  now I must click twice on the button in order to add the popup 

http://take.ms/dtjwn

test 

			'custom' => array(
				'type' => 'addable-popup',
				'value' => array(),
				'label' => __('Custom', 'unyson'),
				'template' => __('Custom','unyson'),
				'popup-title' => null,
				'size' => 'large', 
				'limit' => 1,
				'add-button-text' => __('Add custom options', 'unyson'),
				'sortable' => false,
				'popup-options' => array(
						'ddda' => array(
							'label' => __( 'RGBA Color Picker', 'unyson' ),
							'type'  => 'rgba-color-picker',
							'value' => '#ff6600',
							'desc'  => __( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
								'unyson' ),
							'help'  => sprintf( "%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
								__( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
									'unyson' ),
								__( 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
									'unyson' )
							),
						),
						
						
						'dddaz' => array(
							'label' => __( 'Color Picker', 'unyson' ),
							'type'  => 'color-picker',
							'value' => '#cccccc',
							'desc'  => __( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
								'unyson' ),
							'help'  => sprintf( "%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
								__( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
									'unyson' ),
								__( 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
									'unyson' )
							),
						),
					),
			),

**Comment by danyj** [comment]
tested on latest dev version

**Comment by danyj** [comment]
thnx, works
