### ISSUE TITLE
How can we make Unyson page builder the best WordPress page builder? 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2030]
Current state of mind of all page builder users is so split and most concerns are valid. 

WordPress community loves and hates page builder at the same time and for all the right reasons. 

Here just 2 posts about this but if you are using page builders you know that there are many more. 
http://chrislema.com/drag-and-drop-wordpress-page-builder/
https://purposethemes.com/368041/diy-visual-page-builders-wordpress/

# Page builders pros: 

Easy to use 
Fast  page building
You dont have to code
You dont need to know how to code

# Page builders cons: 

Slowing pages down 
To much code for simple outputs
When you disable it you are left to clean up the garbage ( A LOT OF GARBAGE ) 
Other WordPress plugins incompatibility

# A thought and a question:

Since most page builders shortcodes do nothing but spit out the html, is there a way that we can pre-process the builder code while we are in the builder and insert actual HTML in editor box? 

# What do we get with this? 

One of a kind WordPress page builder
Faster page rendering
Page builder that does not process shortcode on page load
Page builder that leaves clean HTML when plugin is disabled ( give users the CSS/JS and they can still use it ) 
Grateful WordPress community

## Question for developers

What do you think about this and is there any way we can make this happen? 
What would it take to make this happen? 
Can we "pre-process " shortcodes via ajax on shortcode popup save,
retrieve the actual html output  and insert in editor ?

@andreiglingeanu , I know you have made shortcode preview while in editor, can we use something like that for actual output?

**Comment by duongancol** [comment]
I don't think this is the big problem of page-builder 

> Page builder that leaves clean HTML when plugin is disabled ( give users the CSS/JS and they can still use it )

**Comment by danyj** [comment]
@duongancol that is listed as desired result.

**Comment by duongancol** [comment]
> Since most page builders shortcodes do nothing but spit out the html, is there a way that we can pre-process the builder code while we are in the builder and insert actual HTML in editor box

I agree with you but as I remembered @moldcraft tried it but no luck.

**Comment by WPJobs** [comment]
@danyj i think, this is not a big problem too, it is enough to use any of cache plugin to give the already generated static to the users.

it would be better to think about front-end builder to make Unyson in 100000% better than others ;)

**Comment by danyj** [comment]
@WPJobs  frontend builder and page builder in general are just helper tools for anyone who does not know how to code. 

What I am proposing here is forward thinking about issues users have with builders and if we can get rid of all the above mentioned cons ,  Unsyon page builder would be the **only** html friendly page builder and make manyyyyy users and servers happier. 

Currently we are using PHP for all the processing, if we could mix in just a tad of JS for the backend to actually tell us how the shortcode will look like, that output is what can be used in editor. 

Think of your customers, when they disable your theme they are left with garbage to cleanup because we do our shortcodes in the theme. If shortcodes would be HTML block they would not have to clean up anything.

**Comment by WPJobs** [comment]
@danyj and how about styles? If the customer disable my theme, he will stay with a bunch of unstyled (and static) HTML, i don't think that this is exactly what he need :)

**Comment by danyj** [comment]
@WPJobs  http://prntscr.com/cjwrs7

**Comment by WPJobs** [comment]
@danyj oh, sorry. I really do not quite imagine this idea, if the user don't want to use my theme, why he still need the HTML, CSS and JS from theme shortcodes

**Comment by duongancol** [comment]
@danyj In my opinion, we need to optimize the speed at the backend at first. It takes a lot of time when we open shortcode setting, choosing the option then click save. Comparing with Visual Composer or King composer especially, you will see the big different.  
I made the videos so you can see it.
Unyson
http://take.ms/TWUh1

King Composer
http://take.ms/1unjZ

Visual Composer
http://take.ms/fNqp4

**Comment by danyj** [comment]
@duongancol I agree but that is different topic ( speed/optimization ) and you can post that here https://github.com/ThemeFuse/Unyson/issues/1920

**Comment by andreiglingeanu** [comment]
> Since most page builders shortcodes do nothing but spit out the html, is there a way that we can pre-process the builder code while we are in the builder and insert actual HTML in editor box?

The problem with this is that developers lose flexibility.

1. You no longer get defaults from `options.php`
2. You no longer render `view.php` at each request. 
3. If you release an update - the user will have to go through each page and hit update in order to propagate your changes

I **don't** like this idea. Totally a NO from my side. It is doable, but I see no value in it.

<hr>

My 2 cents on this.

First, there was no idea of Unyson Shortcodes before the [WordPress Shortcodes](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension). Now that we somewhat [separated](https://github.com/ThemeFuse/Unyson/issues/1920#issuecomment-246717904) Unyson Shortcodes from Page Builder (we still might have some work to do on that stage) we are open for some improvements we never thought about. The thing is that you can now even release your shortcodes as a separated plugin and the user will be able to use them - you'll just have to give him a nice interface for that. Possible interfaces:

1. Teach the user to copy and paste [this](https://gist.github.com/andreiglingeanu/d00643bc9b59325a11201b04e8e49f7b) syntax into HTML, editors or `textarea`s, just don't forget to [`do_shortcode()`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/62#issuecomment-233979434) that - this will work even if WP Shortcodes extension is deactivated.
2. Hand him the WP Shortcodes extension that will allow to paste (and edit easily) this snippets of strange syntax right in any `wp-editor`.
3. Give him the actual Page Builder that understands shortcodes and allows to combine them via DnD
4. Build some other UI for him. Sky's the limit.

The main idea is that you can separate your Shortcodes from your theme completely and release them in other ways. Then the UI you build for interacting with them is up to you.

Ways to package shortcodes:

1. Via Theme - everyone does that
2. Via Plugin - there a custom hooks to load shortcodes from custom places
3. Via an Unyson extension - which may be potentially paid (who knows, maybe we'll have an Unyson market one day)

Possible ideas for the future:

1. Build a frontend builder
3. Improve the current builder to suit the user needs - you'll have to be aware about backwards compatibility
2. Build Page Builder V2 that will allow to do even fancier stuff with current shortcodes
  1. Better I18n and SEO handling - I don't know what's the current stage on that
  2. Better DnD
  3. Better integration with WordPress Post Editor

The current

**Comment by danyj** [comment]
@andreiglingeanu ,

>The problem with this is that developers lose flexibility.

 thnx for opening my eyes , thus the question for the actual devs.
