### ISSUE TITLE
Feature request: "Ajax button"

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#2074]
Ajax button option, when clicked executes the code on the server. and returns the results in some kind of modal window ( basically some kind of notification)

Also when the ajax request hasn't returned yet it should have a modal window notifying user that the request is being processed.

I know there are a lot of corner cases with the ajax requests, so that's why I'm opening this issue (request) for discussion.

**Comment by andreiglingeanu** [comment]
What really you're looking for? A new **option-type**?

I'm pretty sure you'll be able to achieve what you're trying to do with simple [HTML](http://manual.unyson.io/en/latest/options/built-in/html.html) option type and some custom JS for that.

There's simply too many corner cases to deal with on the JS side in order to build a proper solution for this.

<hr>

Please write a couple of use cases for this feature, let's see if it has any value in implementing a reusable solution for this.

**Comment by ivandotv** [comment]
Will do.

**Comment by llemurya** [comment]
@ivandotv this code as concept was wrote, but for security reasons, this was my fault, it was removed, you can take it and improve it, you just need to check the nonces and maybe the user permissions, [this is the source](https://github.com/ThemeFuse/Unyson/blob/v2.2.3/framework/includes/option-types/runnable/class-fw-option-type-runnable.php).

**Comment by andreiglingeanu** [comment]
@llemurya If you enable this option type, anyone will be able to run any function by issuing a `POST` request to your site and bypass any credentials checking!

**Comment by llemurya** [comment]
@andreiglingeanu I mentioned that this code must be improved, because of security reasons it was deleted, and yes, if you enable this option type as it was wrote anyone can harm your site.
