### ISSUE TITLE
extension installation error

### ISSUE THREAD

**Issue by anisur210** [ThemeFuse/Unyson#2096]
Hi
I am trying to install the Unyson Extensions but theres an error Cannot create temporary directory: /WEB-123WIN/WINPACKAGE22/lifestylebalance.uk.com/www.lifestylebalance.uk.com/web/content/wp-content/plugins/unyson/tmp Can you help please? Can you install the theme please? 

Regards
anisur

**Comment by moldcraft** [comment]
Hi,

Can you send me your admin and ftp details to `moldcraft[at]email.com`?

**Comment by anisur210** [comment]
Hi

Here is the informations :

wp: username: life_style
password: b8l8nce1

host: ftp.lifestylebalance.uk.com
username: lifestyle@lifestylebalance.uk.com
password: JC^NzBsR!

Regards
anisur

**Comment by anisur210** [comment]
Hi

I have already sent my credential login details into your email.

Regards
anisur

**Comment by moldcraft** [comment]
There is something weird:

1. FTP showed no `unyson` directory in `/wp-content/plugins`. Then I did refresh and the directory was there. Then after a few minutes it disappeared again.
2. When I open `/wp-admin/admin.php?page=fw-extensions` I get an error: `Sorry, you are not allowed to access this page.`. I just did a few refreshes and once the page was shown, then again error.
2. On my side the site is loading very slow.

**Comment by anisur210** [comment]
Hi

Please try this time. Now you will get directory `/wp-content/plugins/unyson`

**Comment by anisur210** [comment]
Hi

Have any update?

**Comment by moldcraft** [comment]
The file paths on your server start with `\\`. Instead of `C:\hello\world` or `/var/ww/hello/world`, they are `\\WINXYZ\Hello\world`. Our scripts convert all `\` to `/` and all paths are in Unix style, which in your case breaks the path because `/WINXYZ/Hello/world` doesn't exist. I will think tomorrow on a solution to not change a lot of code.

I have tried to upload all extensions via ftp so you can start working on that site but I can't because the upload speed was very slow `5 kB/sec`. Also your site is loading very slow, every page is loading in 20-30 seconds, it's a pain to test.

**Comment by moldcraft** [comment]
@anisur210 WordPress wp-admin and FTP credentials don't work anymore. Please send me again working credentials and I will inspect the problem.

**Comment by moldcraft** [comment]
Fixed https://github.com/ThemeFuse/Unyson/issues/2310
