### ISSUE TITLE
Get list of theme shortcodes

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2110]
I need to compile shortcodes style.css files , is there a  helper function to get the list of all available theme shortcodes ? Or even better the list of their CSS files ?

**Comment by andreiglingeanu** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/class-fw-extension-shortcodes.php#L27-L36

Then use [`locate_URI`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/includes/class-fw-shortcode.php#L113) (there's also [`locate_path`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/includes/class-fw-shortcode.php#L65)) in order to find their CSS file (which will count for rewrites in themes and child themes).
