### ISSUE TITLE
How to use same settings in customizer and theme options together?

### ISSUE THREAD

**Issue by therakib7** [ThemeFuse/Unyson#2170]
Hello,
This is an awesome framework. I like your framework. I see in the documentation when a user writes code in customizer.php file, it's field  show in customizer and when  same code keeps in settings.php it shows in theme settings panel but I wanna keep both same. That's mean when a user changes a field value in customizer so that it automatically change in theme settings option. In the same way when change value in theme settings option it will auto change in customizer. I saw this type of options works in Redux Framework.

Have you any solution for me to solve this problem?

Advance Thanks

**Comment by andreiglingeanu** [comment]
Hi,

Try to extract your options into a separate file, like `framework-customizations/theme/options/my-common-options.php`.

Then in `settings.php` and `customizer.php` call this file twice:

```php
$options = fw()->theme->get_options( 'my-common-options' ),
```

Please note that those options will be saved in separate place, thus if you perform a change in Theme Settings, this change won't be reflected in Customizer. You should really explore the concept of a [**Options Storage**](http://manual.unyson.io/en/latest/options/storage.html#content) in order to get a proper fix for that.

At the end of the day, you have the tools and power to implement lots of features by yourself. Good luck!

**Comment by moldcraft** [comment]
You can add [`fw-storage`](http://manual.unyson.io/en/latest/options/storage.html#content) parameter to your customizer options that you want to be in sync with settings options.

Settings options are saved in [this wp_option](https://github.com/ThemeFuse/Unyson/blob/4edd8a2d6b03b3b6245dcf4ee1952ca40722cb41/framework/helpers/database.php#L16)

```php
'fw_theme_settings_options:'. fw()->theme->manifest->get_id()
```

In your `customizer.php` you can do

```php
$settings_wp_option = 'fw_theme_settings_options:'. fw()->theme->manifest->get_id();

$options = array(
    'CUSTOMIZER_OPTION_ID' => array(
        'type' => 'text',

        'fw-storage' => array(
            'type' => 'wp-option',
            'wp-option' => $settings_wp_option,
            'key' => 'SETTINGS_OPTION_ID',
        ),
    )
);
```

**Comment by moldcraft** [comment]
Also there is [another solution](https://github.com/ThemeFuse/Unyson/issues/410#issuecomment-101633999)
