### ISSUE TITLE
Errors with Unyson 

### ISSUE THREAD

**Issue by ashleyrb220** [ThemeFuse/Unyson#2183]
Hello, 
I am receiving an error with Unyson causing maximum database load to be hit. I reverted to previous version and I am still having error. I appreciate your assistance.

**Comment by thednp** [comment]
Perhaps [this](https://premium.wpmudev.org/forums/topic/limit-of-wordpress-database?utm_expid=3606929-91.15T0nlf8TFCqo1W_BlZjGg.0&utm_referrer=https%3A%2F%2Fwww.google.ro%2F) explains?

**Comment by ashleyrb220** [comment]
Unfortunately that option will not work.
There was not an issue with the site until this week. Do you have any other thoughts ideas? I know it is related to unyson because I tested all plugins & extension and the errors only appear with unyson. If I don't figure out a solution fast, I will have to build the entire site again not using unyson. Adding another plugin is definitely not the solution I want to take. 

Thank you for your help!

**Comment by ashleyrb220** [comment]
Also that plugin is decommissioned.

Thanks!

**Comment by danyj** [comment]
give more details , how that the max hit happens , in builder , in theme settings , on save , on load. More details please.

**Comment by ashleyrb220** [comment]
Thank you. It happens in the dashboard whenever I try to open any section like pages, tools, etc. Always with pages, sometimes with other sections. The page tries to load, then quits, and I receive the error. First I was seeing a 503 error and sometimes I receive "error establishing a database connection". I spoke to my host last night that said the load was being hit. 

Thank you very much.

**Comment by danyj** [comment]
>  I spoke to my host last night that said the load was being hit

that does not tell us anything , we need the actual server error logs
this is what 503 is http://www.checkupdown.com/status/E503.html

and is more connected to your host and the way they setup/limited the server  than Unyson

other than that Unyson is not messing with your dashboard since nothing in your dashboard is calling Unsyon classes/functions but again if you think it is,  than please provide error logs so that we can see the actual issue. 

You also said that you are making Unyson based site , maybe you have never ending recursion in your Unsyon based script that is overloading your server. But again all this is  guessing, error logs is what we need.

**Comment by danyj** [comment]
one way to eliminate Unyson is to disable the scripts you made based on it and leave the plugin published. If you dont have server issues than , than you know it is something within the scripts you made.

**Comment by ashleyrb220** [comment]
I appreciate that. Thank you. 
I will also get the server error logs.

**Comment by moldcraft** [comment]
Try with a default WP theme. Maybe your theme does inefficient/crazy db queries (without limit parameter).
