### ISSUE TITLE
Contact Form shortcode issues

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#2195]
Hey guys,

A customer that's purchased one of my themes is having some issues with the contact form, I was wondering if you could help identify what's going on here.

First of all the form isn't sending emails, in the network tab the admin-ajax.php is returning the error:
`fw_ext_contact_form_process: "Oops something went wrong. <em style="color:transparent;">Could not send the email</em>"`

Secondly, when opening up the shortcode in the page builder, all the fields appear like this in the screenshot
![image](https://cloud.githubusercontent.com/assets/4599099/20499708/927d821e-b02a-11e6-87b9-82ee2c086a80.png)

as well as having the following issues in the console:
![image](https://cloud.githubusercontent.com/assets/4599099/20499747/bfb41e14-b02a-11e6-9af0-74a8b8f8f6a7.png)

The customer is running the latest WordPress and Unyson (4.6.1 and 2.6.8) with extensions also updated. I'm also running the same versions on my demo site and I'm not having any issues.

Any help much appreciated

**Comment by moldcraft** [comment]
I need to inspect the site. Can you send me the admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by martinburdon** [comment]
Thanks for the reply @moldcraft. I've asked my customer for the details and I'll forward them onto you when I receive them.

**Comment by martinburdon** [comment]
Hey @moldcraft, my customer wouldn't share the info but I've since recreated this issue with one of my demo sites. I've narrowed it down to an issue with upgrading the extensions. WordPress, Unyson and the extensions required an update so I did them one by one, checking the shortcode after each update and it was after the extensions were updated that the issue occurred.
I can share some login details to my theme if you require?

**Comment by moldcraft** [comment]
Sure, send the details to `moldcraft[at]email.com`

**Comment by rawcreative** [comment]
I'm also seeing this, however it's happening when trying to use the form-builder option type in a metabox. 

It appears that the change occurred here: https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/1f0ea1a2eb8737fe980b10d7ba01712fd20a98be which shifts the ```page_builder_item_type_contact_form_data``` js variable to be populated via wp_localize_script rather than getting the data from fw.unysonShortcodesData(). Since the call to wp_localize_script isn't fired when the form builder isn't loaded via a page builder shortcode, that data is never populated and the form builder is broken.

**Comment by andreiglingeanu** [comment]
@rawcreative Nope, we managed to get `page_builder_item_type_contact_form_data` variable back, after realizing the fact that there's no easy way to load data via `fw.unysonShortcodesData`.

**Comment by rawcreative** [comment]
@andreiglingeanu Nope?? I'm not clear what you're referring to. 

To clarify I was stating that the reason the form builder is broken in certain instances (like when using it as an option in a metabox, which previously worked), is because the ```page_builder_item_type_contact_form_data``` is not present and never loaded unless the contact form shortcode is bootstrapped via the page builder

**Comment by andreiglingeanu** [comment]
@rawcreative Ah, I see. Localize for `page_builder_item_type_contact_form_data` is hardcoded inside the page builder item type (which in turn contains the contact form option type) and not in the option type itself, I spot the problem. A fix to come.

**Comment by rawcreative** [comment]
I've taken a look at a couple scenarios on how to approach this, but the only one that really makes sense is to basically revert the changes in this commit: https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/f8fc896cd98c2e7c7ab08b555220b73ac0c7b1e8 so that the item data is populated and registered by the items individually instead of collected and registered by the contact forms extension.

**Comment by andreiglingeanu** [comment]
Are you able to give me an easy way to reproduce this thing? Ideally I'm looking for an option array which I can paste somewhere in the scratch theme and get this error. Only if it's possible.

**Comment by rawcreative** [comment]
Sure. Easiest way is probably to use it the same way I am, forms as a custom post type. Just copy the contents of posts.php in the gist to /inc/posts.php and copy form.php to /framework-customizations/theme/options/posts/form.php and you should be good to go.

https://gist.github.com/rawcreative/0936404decd47eb275087c72b8743d1e

**Comment by andreiglingeanu** [comment]
@rawcreative Thanks for nice reproduction steps! That's how you do a bug repport.

<hr>

The [fix](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/d54b46ce91e54ad070273c3d0af1623cf1463a40).

1. [Do not load data from page builder item type](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/d54b46ce91e54ad070273c3d0af1623cf1463a40#diff-8b578ac582e03cf3baf93deb9f1e757aL35)
2. [Load it from option type instead](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/d54b46ce91e54ad070273c3d0af1623cf1463a40#diff-275dae5e0449a283aa1f74268321fe59R95)

Those two steps will satisfy successful builder init, with meta data like mailer config.

[This](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/d54b46ce91e54ad070273c3d0af1623cf1463a40#diff-ad114b6218cd0f1bf08d294281032197R4) trick will force the [Builder](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/726c600d3e73f4e83dc30135b96415782c67a10d/includes/option-types/builder/static/js/initialize-builder.js#L301) extension to wait till the `fw.shortcodesLoadData()` promise will get fulfilled, so that [contact form items](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/d54b46ce91e54ad070273c3d0af1623cf1463a40#diff-533a641f94a5c0bb9cdd2096357fcbd2R4) will get initialized correctly.

**Comment by rawcreative** [comment]
@andreiglingeanu is this working for you? I'm getting the same result as before. Looking around I don't see [this](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/d54b46ce91e54ad070273c3d0af1623cf1463a40#diff-ad114b6218cd0f1bf08d294281032197R4) being fired by anything.

**Comment by andreiglingeanu** [comment]
Yep, that is working for me indeed. 
I assume you tried to pull all the extensions from GitHub, no?

That event is triggered by theBuilder extension - please re-read mycomment below. 

Let me know how it goes.
