### ISSUE TITLE
change icon pack root class name

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#2205]
Is it possible to change icon pack root class name?

using example below `icon-class` will be `brandico brandico-some-icon` 

I've seen some icon sets do: `glyph-set brandico-some-icon`

```
add_filter(
    'fw:option_type:icon-v2:packs',
    '_add_more_packs'
);

function _add_more_packs($default_packs) {
    return array(
        'brandico' => array(
            'name' => 'brandico',
            'css_class_prefix' => 'brandico',
            'css_file' => get_template_directory() . '/brandico.css',
            'css_file_uri' => get_template_directory_uri() . '/brandico.css'
        )
    );
}
```

**Comment by andreiglingeanu** [comment]
Hm, interesting use case. Can you please provide some concrete examples of packs that will have those rules?

The main idea is that I don't even want to try to adapt `icon-v2` to every pack that exists out there. That's why we've built this [utility](https://github.com/ThemeFuse/Unyson/blob/master/framework/bin/load-latest-fonts.php) that can adapt practically any CSS file to the `prefix prefix-some-icon` format - and the `icon-v2` can digest it afterwards. 

I don't want to harden the parsing logic of CSS (thus the execution time of it) in our runtime just because we'd like to support a bit more formats. I'd suggest you to statically (or using our tool above) convert your CSS to the format we're used to have nowadays practically everywhere -- `prefix prefix-some-icon`.
