### ISSUE TITLE
Shortcode get_options('sub_file') does not work

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2210]
I am testing sub options file call  and if used inside the shortcode/options.php  it creates  never ending recursion

```

fw_ext('shortcodes')->get_shortcode('posts')->get_options('style_settings')
```

where this if used in extension/media/ extensions/slider/slick-full/options/options.php   works

    fw_ext('slick-full')->get_options('styling')

I can get the options with this 

```
$vars = fw_get_variables_from_file(dirname(__FILE__).'/style_settings.php', array('options' => null));
$style_settings = $vars['options'];
```

but the `get_options('sub_file')` if it works for extensions should work for shortcodes

**Comment by Shahab2905** [comment]
@danyj I have had the same issue. It happens when you use one shortcode options array inside another shorcode options array. 

what I did is simply use a helper function which will return options array from the shorcode object get_options; and use the helper function on the shortcode options page where you initially wanted options from another shorcode options array.

The trick is to call the function in options.php file of the shorcode. If you use it anywhere else it will simply generate never ending recursion.

**Comment by GheorgheP** [comment]
I think you understand why it creates a recursion.
My question is, what do you expect the function to return inside of the options array?
Also, why you use it there?

**Comment by danyj** [comment]
I am trying to use options sets in shortcodes the same way we use it in theme which is separate the options files

**Comment by danyj** [comment]
@ViorelEremia  can we get this to work at all ?

**Comment by danyj** [comment]
basically looking to something like 

`
fw->shortcode->get_options('styling');`

where `styling.php` is in same folder as shortocode `options.php`
