### ISSUE TITLE
Nested columns

### ISSUE THREAD

**Issue by aleksandar-p** [ThemeFuse/Unyson#230]
Is it possible to create a shortcode for nested columns or perhaps override the existing column shortcode to accept nesting?

**Comment by sergiubagrin** [comment]
@aleksandar-p 

We don't have this feature in our to do list. We plan to change page builder in a different way. Working with shortcodes for end user is a bad solution.

**Comment by danyj** [comment]
@sergiubagrin can you give us more info about the change you are suggesting ?
I would love to see actual div's being used for rows/columns instead of shortcode.

**Comment by thednp** [comment]
Not a big fan of WP shortcodes system, but I managed to work around this on my shortcode code, using a different framework, but as for shortcode system, here's how I think of it: in order to be able to have nested columns, you need to make sure the tags are unique.

Example:
<pre>
[row]
  [column]
    [row1]
      [column1][/column1]
    [/row1]
  [/column]
[/row]
</pre>

For each nested row and column level you increment the number that you see in this example.

**Comment by sergiubagrin** [comment]
@aleksandar-p - Why you need Nested columns. Can you give me a example?

**Comment by thednp** [comment]
@sergiubagrin 
Everybody is trying to do well structured content, and columns is a No1 way to go, and currently most SC cannot handle nested structures. I gave you my solution I use, I know it's not the best but it's a good start.

**Comment by sergiubagrin** [comment]
> and currently most SC cannot handle nested structures.

Can you give more details?

>  I gave you my solution I use, I know it's not the best but it's a good start.

From technically point of view we know how to make it. We want to understand why you need it as a end user?

>@sergiubagrin can you give us more info about the change you are suggesting ?
I would love to see actual div's being used for rows/columns instead of shortcode.

We plan (not soon) to use shortcodes in a different page builder in future. A block page builder something like this one: http://designmodo.com/qards/

**Comment by thednp** [comment]
The quards is VERY interesting for a ONE TYPE DESIGN ONLY.

About your info requests: I used many SC in the past, at that time, each of them failed to do nested columns. That's partly because Bootstrap 2, now with BS 3 we can have a single row to hold all nested columns, without the need to include the nested into another row. Similar issue, I think, was present with other CSS frameworks or custom designer made CSS.

I think I covered some technical as well.

**Comment by sergiubagrin** [comment]
> About your info requests: I used many SC in the past, at that time, each of them failed to do nested columns. That's partly because Bootstrap 2, now with BS 3 we can have a single row to hold all nested columns, without the need to include the nested into another row. Similar issue, I think, was present with other CSS frameworks or custom designer made CSS.

I understand what you mean. I want to know what kind of pages you need in order to use nested columns? Maybe problem is in design not in shortcodes/ columns? You can use comumns + shortcodes + columns + shortcodes but it is nessesary? End user will understand how to use this kind of structure?

**Comment by thednp** [comment]
What I am talking about is also coming from my users. I do alot of columns nesting myself
http://antares.pcadviser.ro/

**Comment by sergiubagrin** [comment]
1. We plan to extend shortcodes like tabs, accordions in order to be possible to add different shortcodes in each tab. 

2. We don't plan to create columns nested 

I will open a new issue with point (1)

Thanks
