### ISSUE TITLE
WP-Shortcode Extension in Textarea Option Type

### ISSUE THREAD

**Issue by IronLady** [ThemeFuse/Unyson#2324]
Hi, 

I just try the WP-Shortcode extension. It works well in Post/Page editor but the "shortcode button" doesn't showed up in Text Block element in page builder or my custom shortcode element which use textarea (wp-editor) option type. 

```php
array(
    'type'  => 'wp-editor',
    'label' => __('Example Content', 'fw'),
)
```

I looked at the docs in http://manual.unyson.io/en/latest/extension/wp-shortcodes/, but it's not a complete documentation. 
Did I missed something?

Thanks

**Comment by moldcraft** [comment]
Hello,

Yes, the docs are incomplete because this feature was added recently.

You have to [add this parameter](https://github.com/ThemeFuse/Unyson/blob/43b6a1e1dee556c9934dd2acc065d53948cb4d15/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L23-L33) in your option array.
