### ISSUE TITLE
After active required extensions

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#2330]
Hello!
I want to redirect user to demo content installation page instead of Unyson extension page after they install extensions successfully.
Are there any ways or filter?

Thanks!

**Comment by moldcraft** [comment]
On that action you can't do a regular `header()` redirect because the page html has been already printed. You can only do [js redirect](https://github.com/ThemeFuse/Unyson/blob/f24ed92d186298ad19596c5daa5354b10a1a7cfd/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L797-L800)

**Comment by duongancol** [comment]
ok, I'll test and let you the result soon.

**Comment by danyj** [comment]
@duongancol , @moldcraft  has anyone make this work ? 

this does not fire for me 


```
function _thz_action_redirect_to_demo()	{
	
	echo
		'<script type="text/javascript">'.
			'window.location.replace("'. esc_js(self_admin_url('tools.php?page=fw-backups-demo-content')) .'");'.
		'</script>';
}
add_action( 'fw_after_supported_extensions_install_success', '_thz_action_redirect_to_demo' );
```

**Comment by duongancol** [comment]
@danyj it works for me. Did you upload to the latest version of plugin?

**Comment by danyj** [comment]
@duongancol   I have latest files and hook is there , did  you try this , 

activate another theme 
uninstall  Unyson , 
activate your theme 
install required plugins


are you redirected now?
