### ISSUE TITLE
Show unique type value in html type shortcode in same shortcode

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#2349]
Hi
I have tried to print  unique_id value in another  HTML type option in the same shortcode
```
'html' => array(
		'type' => 'html',
		'label' => __( 'Label', '{domain}' ),
		'html' => "$unique_id"
	),
	'unique_id' => array(
		'type' => 'unique'
	),
```

I have tried with fw_ext_shortcodes_decode_attr() but its not working

```
$shortcode	 = 'twinkle';
$atts		 = shortcode_parse_atts( $data[ 'atts_string' ] );
$atts		 = fw_ext_shortcodes_decode_attr( $atts, $shortcode, $data[ 'post' ]->ID );
$unique_id = $atts[ 'unique_id' ];
```

Can you please share some idea how I can get the option value in same another shortcode option.

**Comment by moldcraft** [comment]
Hello,

You can't do that because:

1. Shortcode options are loaded only once and used for all shortcodes.
2. Unique value can have duplicates in builder shortcodes and they are [update on post save](https://github.com/ThemeFuse/Unyson/blob/7b202c8f9ca207f311c72e50afe2b6a1c4b0a598/framework/includes/option-types/simple.php#L1072-L1113).
