### ISSUE TITLE
Unyson Translation Extension Bug ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#2366]
Hello @moldcraft @llemurya 
Its my second ticket that i have been raising now since you guys might be on busy schedules.
But i have to remind you guys once again. 
I have the following issue that the unyson translation extension did not work on wordpress menus.
When i tried to create the menu the page refresh and did not do anything.
My menu items left side bar still disable.
![c4830546-e490-11e6-9eb4-7e9a47d1aae6](https://cloud.githubusercontent.com/assets/12461946/22395825/25e96e58-e56b-11e6-82bb-17a6f2049419.png)
See this reference Image.

Kindly respond my query in your valuable time.
Kind Regards.

Looking Forward to hear from you soon.

**Comment by wpthemes786** [comment]
Hello Everyone.
Is there someone who cared to respond my ticket.

**Comment by moldcraft** [comment]
Hello @wpthemes786 

I am not familiar with how Translation extension works (because I haven't used it and I am not its author). @llemurya is not working on Unyson anymore.

Also this extension was excluded from extensions list https://github.com/ThemeFuse/Unyson/issues/874

So unfortunately the only way is to inspect the extension code yourself, find the problem and come up with a solution (as a pull request).

**Comment by wpthemes786** [comment]
Thanks @moldcraft
