### ISSUE TITLE
No access to Demo Import page

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#2376]
Hi,
One of my customers had installed Backup & Demo Content Install extension, but for some reason it doesn't appear in menu  - http://imgur.com/a/nWFTA and direct link to the page returns: “Sorry, you are not allowed to access this page.”

Any thoughts? Thank you

**Comment by mowshon** [comment]
I think your customer don't have `ZipArchive` php extension. He have capability to do `export` but `Backup` extension also check if `ZipArchive` class exists.

https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/58fc2e273b053eaeeae48a7ad7c62695949ef008/class-fw-extension-backups.php#L423

**Comment by onebelarusianguy** [comment]
@mowshon thanks I will ask him about this.

**Comment by moldcraft** [comment]
@mowshon The `ZipArchive` is available because the Backup menu is there.

[This is the required condition](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/58fc2e273b053eaeeae48a7ad7c62695949ef008/extensions/backups-demo/class-fw-extension-backups-demo.php#L95-L99) in order for the Demo Content Install menu to appear
