### ISSUE TITLE
How to bring option_theme to the file style.css

### ISSUE THREAD

**Issue by pava467** [ThemeFuse/Unyson#2383]
Hello.
I do theme for Envato
Framework Unyson

How to use the styles from the admin?
fw_get_db_settings_option ( 'custom_style');
How to bring them to the file style.css
Not in the <style> </ style>

Maybe it will be .php file
Like this:
a {  
color: <?php echo esc_js($the_core_less_variables['link-color' ]); ?>;  
}  

How to include this?

**Comment by GheorgheP** [comment]
Hmmm, the simplest option is to print the style in the HTML head, but this is not so correct due to the fact that on every page load you will access database to extract the value and then print in body.

You can do another way. Every time the theme settings are saved you can generate the a `.css` file that you'll enqueue latter in frontend.

**In case you do not want to read all instructions, scroll down to the final 2 function after space line, copy them and test out.**

For this you'll use the `fw_settings_form_saved` action that is triggered when the theme settings are saved.

```php
function _action_styling_settings( $old_values ) {
	//...	
}

add_action( 'fw_settings_form_saved', '_action_styling_settings' );
```

The `fw_settings_form_saved` provides one parameter, `$old_values`, the old values before saving so you'll compare them with new values, in case they are the same, there is no need to generate the css file again.

```php
$key = 'THE-OPTION-KEY';
if ( fw_akg( $key, $old_values ) == ( $values = fw_get_db_settings_option( $key ) ) ) {
    return;
}
```

Then you have to define the directory where the the `.css` file will be generated, I would recommend the `uploads` directory. It is good for multisite support and backups, also on some advanced secured hosting providers this is the only editable directory from wordpress installation.

```php
$dir = fw_akg( 'basedir', wp_upload_dir() );
```

Also you have to define the file name, and make sure it willl not conflict with other plugins may generate CSS file in `uploads` folder. So better use the theme name, you can use the `wp_get_theme()` functions for this. In this example I did not use it:

```php
//Refer wp_get_theme() https://developer.wordpress.org/reference/functions/wp_get_theme/
$file_name = 'my-theme-stylesheet';
```

Then you'll need some kind of function that will parse your options and generate the CSS string, I did not define that function here as it up to you depending on your option complexity. I will be really good if your CSS generator function will throw an exception or at least return `false` in case the option value is invalid or some values are not correct (usually users tend to insert invalid color codes). I would recommend throwing an exception so you can tell in the exception message what was the specific problem and write this in `error.log` file. 

```php
try {
	$css = my_css_generator_function( $values );
} catch ( Exception $e ) {
	error_log( $e->getMessage(), E_USER_WARNING );

	return;
}
```

**Important:** Do no forget to replace the `my_css_generator_function` with your own.

Then initialize the `W_File_System` to generate the CSS file and try to write it:

```php
/**
 * @var WP_Filesystem_Direct $wp_filesystem
 */
global $wp_filesystem;

if ( ! $wp_filesystem || ! $wp_filesystem->put_contents( "$dir/$file_name.css", $css ) ) {
	error_log( 'Could not generate the dynamic stylesheet', E_USER_WARNING );
}
```

**=======================================================================**

You should get something like this:

```php
function _action_styling_settings( $old_values ) {

	//Check if there was made any changes in your specific options(s)
	//Mostly users will not change those options but play around with other settings options
	//So there's not need to re-generate every time the CSS file.
	$key = 'THE-OPTION-KEY';
	if ( fw_akg( $key, $old_values ) == ( $values = fw_get_db_settings_option( $key ) ) ) {
		return;
	}

	//Directory where the the file will be generated
	//Recommended to use the uploads directory, in case of multisite/backups ...
	//Never use the theme directory to generate the style file
	//In case of theme update, the style will be erased,
	//also on multisite if one user will save settings, all other sites will get same style
	$dir = fw_akg( 'basedir', wp_upload_dir() );

	//Better use a unque name, to avoid conflicts with other files.
	//A good practice will be to use the theme name
	//Refer wp_get_theme() https://developer.wordpress.org/reference/functions/wp_get_theme/
	$file_name = 'my-theme-stylesheet';

	//Replace my_css_generator_function with a real function that can parse and generate the CSS
	// from provided option value

	try {
		$css = my_css_generator_function( $values );
	} catch ( Exception $e ) {
		error_log( $e->getMessage(), E_USER_WARNING );

		return;
	}

	/**
	 * @var WP_Filesystem_Direct $wp_filesystem
	 */
	global $wp_filesystem;

	if ( ! $wp_filesystem || ! $wp_filesystem->put_contents( "$dir/$file_name.css", $css ) ) {
		error_log( 'Could not generate the dynamic stylesheet', E_USER_WARNING );
	}

}

add_action( 'fw_settings_form_saved', '_action_styling_settings' );
```

After that, sure you have to enqueue that `.css` file in frontend:

```php
function _action_enqueue_dynamic_stylesheet() {
	$dir       = fw_akg( 'basedir', wp_upload_dir() );
	$file_name = 'my-theme-stylesheet';

	if ( file_exists( "$dir/$file_name.css" ) ) {
		wp_enqueue_style( 'my-theme-dynamic-stylesheet', fw_akg( 'baseurl', wp_upload_dir() ) );
	}
}

add_action( 'wp_enqueue_scripts', '_action_enqueue_dynamic_stylesheet' );
```

**Comment by pava467** [comment]
Thank you!
I try it

**Comment by pava467** [comment]
Call to undefined function my_css_generator_function()

**Comment by GheorgheP** [comment]
That's why you have to read the instructions :D :D :D 

**Important:** Do not forget to replace the `my_css_generator_function` with your own.

**Comment by pava467** [comment]
This function must to echo css code?

**Comment by GheorgheP** [comment]
Yes, you need to process your option value and generate the necessary CSS from it.

**Comment by pava467** [comment]
Sorry, I need to example

**Comment by ivandotv** [comment]
This is not a unyson issue.
