### ISSUE TITLE
Portfolio tag view should be in extension view folder not theme

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2394]
I need tag view so this file should work within the portfolio views 

    taxonomy-fw-portfolio-tag.php

but it works only within the theme folder

**Comment by danyj** [comment]
or  the taxonomy.php that we can place in override should also account for fw-portolio-tag

currently portfolio tags are displayed in default post archive

**Comment by danyj** [comment]
this  https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/master/hooks.php#L46


needs something like 


    } else if ( ( is_tax( $portfolio->get_taxonomy_name() ) || is_tax( 'fw-portfolio-tag' )) && $portfolio->locate_view_path( 'taxonomy' ) ) {


to  display taxonomy.php from   portfolio/views  if tags

**Comment by danyj** [comment]
or additional check 


	} else if ( is_tax( 'fw-portfolio-tag' ) && $portfolio->locate_view_path( 'taxonomy-fw-portfolio-tag' ) ) {

		if ( preg_match( '/taxonomy-' . '.*\.php/i', basename( $template ) ) === 1 ) {
			return $template;
		}

		return $portfolio->locate_view_path( 'taxonomy-fw-portfolio-tag');
		
	}

wich ever you prefer

**Comment by danyj** [comment]
can this be added in or do we need to add own filter?

**Comment by danyj** [comment]
@GheorgheP  bump

**Comment by GheorgheP** [comment]
Ho, because the Portfolio extension doesn't have defined by in it's core the `tag` taxonomy, only the category, so if you decided to include the `tag`, you need to define the template for it.

This [line of code](https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/master/hooks.php#L46) was added there because of other reasons, as initially we loaded the `category` taxonomy view from the `views` folder only and the users asked to maintain the wordpress compatibility, so if the `fw-portfolio-category.php` is define din theme root folder, it should take it, but in other had we had to keep the compatibility with current version where other developers was using the `views` folder, so we first check for taxonomy file in theme root, then for taxonomy view in `views` folder.

Since the `tag` taxonomy you created doesn't have this problem, it behaviors like normal taxonomies in wordpress. But there is not reason to add it in extension core, as initially we don't need it.

**Comment by danyj** [comment]
ok makes sense, i defined it my self n hooks, thnx
