### ISSUE TITLE
When installing required extensions we need additional notice

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2421]
If you have a set of extensions that need to be installed the Unyson installation process take bit longer , but for the user it "seems" like it is finished , 

![8639ac3460b94e6992fa6c0183aa3c60](https://cloud.githubusercontent.com/assets/2340172/23263147/9de8173e-f9dd-11e6-9d05-7244845cc035.png)

I think we need something like 

`   Installing required extension please wait.. 
`

after **Successfully installed**  if the required extensions are being downloaded and installed

**Comment by danyj** [comment]
@GheorgheP  bump

**Comment by GheorgheP** [comment]
Hmmm, but this doesn't have to do anything with Unyson as you install it with TGM plugin and even if you set the `force_activation` to `true` in the TGM configuration, it still doesn't install the extensions.

**Comment by danyj** [comment]
> >  but this doesn't have to do anything with Unyson 
it does for me 

`$manifest['requirements'] `  has required extensions listed so they are being installed

**Comment by GheorgheP** [comment]
Installing plugin and extensions is a synchronous process, so there cannot be something like this, that you get the success page, but the extensions are still installing. 
There is other thing, that your extensions are never installed, so the user has to click on **Install compatible extensions** button, manually, am I right? 

This happens because after the activation Unyson tries to install the extensions, for this it checks if the file system is [ready](https://github.com/ThemeFuse/Unyson/blob/9669344fa56c25e2434af2f79d365579fcde81df/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L3459), but it is not, so the extensions are not installed.

If you'll replace the [return](https://github.com/ThemeFuse/Unyson/blob/9669344fa56c25e2434af2f79d365579fcde81df/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L3460) with `WP_Filesystem();` and the al will be fine with your file system, then they will get installed.

**Comment by danyj** [comment]
> n Install compatible extensions button, manually, a

no , not anymore

https://github.com/ThemeFuse/Unyson/issues/2122
https://github.com/ThemeFuse/Unyson/issues/2117

they are auto installed

**Comment by GheorgheP** [comment]
I know that they are installed, in case the file system is initialized, but as I mentioned, this is a synchronous process, **unyson installation > unyson activation > extensions installation > response message** .

In the message is not specified that the extensions are installed, but you can change this in the TGM plugin.

**Comment by danyj** [comment]
look at this ,  you think this is ok? 
http://take.ms/HPAdb

it is waiting for 8 Unyson extensions to be installed and you dont know what is going on. 

a simple indicator , icon loading , or something would be sufficient.

**Comment by GheorgheP** [comment]
Hmmm, 

On my side it is behaviors differently, the response page appear after plugin nad extensons installation.
Anyway, I will review this, but you can do on your own in your themes TGM, as this depends on the  TGM plugin, we do not have any controls from Unyson.
