### ISSUE TITLE
error: Bad Gateway

### ISSUE THREAD

**Issue by roseyazman** [ThemeFuse/Unyson#2425]
![error bad gateway](https://cloud.githubusercontent.com/assets/26060178/23359930/780afb14-fd0a-11e6-9de1-61d7b6b62aef.png)
![error not found](https://cloud.githubusercontent.com/assets/26060178/23359931/7816a6e4-fd0a-11e6-9732-21d46bcebab7.png)

The problem is that when I make some changes on any page using unyson page builder, and click edit on any Content Element, I received an error message "error: Not found" and sometimes "error: Bad Gateway"

waiting for an early reply, please.

**Comment by GheorgheP** [comment]
When the popup opens, Unyson makes an ajax call to the server in order to render the options from popup.
There are some specific cases when some servers refuses that ajax request due to some of their configuration restrictions.

You can open the Chrome Developer Tools (F12) and in the Network section to the request and response headers when you try to open the popup. You can contact the hosting provider to ask why the serer refuses  the request.

What hosting provider are you using?

**Comment by roseyazman** [comment]
thanks for your support 
the issue has been resolved it was due to some restrictions from host server 
I'm using ntc.net.pk hosting 
regards

**Comment by GheorgheP** [comment]
What are the restrictions?

**Comment by roseyazman** [comment]
I don't know what were the restrictions, I asked my hosting provider for support, they simply told me that they had applied some restrictions on directories, they informed after removing those restrictions... 
regards
