### ISSUE TITLE
Visual Composer 5 not compatible with Unyson page builder?

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#2456]
Hello,

Few of my clients are complaining that Visual Composer functionality is broken when Unyson page builder is activated.

Are there any solutions for this issue?

Thanks

**Comment by danyj** [comment]
and what is the exact issue?

**Comment by pear1** [comment]
When using Visual Composer both builders are active (Visual Composer at top and Unyson builder at bottom) and Unyson page builder overwrites Visual Composer.

**Comment by danyj** [comment]
is beyond me why would anyone use both builders at the same time. should be either or ,  is like you want to have 2 theme panels at the same time

**Comment by pear1** [comment]
Well Unyson page builder is very outdated and very limited at the same time (thats what theme users say). I hoped that this builder will improve it's functionality, but I was wrong.

All our demo pages are made on Unyson page builder, therefore users must use it, but for new page creation more advanced users want to use VC for new page creation and broken VC plugin is a dealbreaker.

**Comment by danyj** [comment]
> very outdated

builder comes with **base**  setup ,  it is up to you to give you users more , not to tell them get VC.

**Comment by danyj** [comment]
thus it is called a framework , so that you can build on it if base is not enough for you

**Comment by pear1** [comment]
I built **many many** new elements for this framework, but it is not enough when it works pretty slow and there is no option for live preview like most of the other new page builders.

But I have never told any of my theme users to use VC, just when they complain about it's flaws I can argue a lot.

**Comment by duongancol** [comment]
actually, I used to get the same situation. My clients use 2 page builders at the same time. Some use  Visual Composer and Someone use Site Origin. Luckily, They don't have many conflicts. 
Maybe you should try to test at localhost to make sure the conflict doesn't come from another 3rd plugin.

**Comment by danyj** [comment]
>  when they complain about it's flaws

I am sorry to be harsh but you must understand that those are your "flaws"  not Unyson. You are presenting Unyson to your users and if you dont build something that will make them go "awwwww"  sure they will find a reason to complain. 

Top sold themes on TF dont have visual page builder , but have theme options and builder , 

here https://themeforest.net/popular_item/by_category?category=wordpress

first 5 except X  no visual but everyone is using them so again , it is what you make out of it. 


>  works pretty slow

again , is how you build the options arrays ,  we have many posts here  about performance issues and we are always trying to optimize our options so that we dont overload. 


Here is my dumb example , 

For 2 years now I am workin on my theme and this hole time I have a background option made that saves array of 30 elements every time , 

complete theme panel options export was usually 145 / 160KB  

until my dumb ass figured out why do I save 30 bg elements if user has picked   background type color and color , that is just 2!  not 30 , 

so I did a revision and now theme options export is 75KB , not to talk about 40 builder elements that use same option minimum 3 times. 

this is what I mean under  our "flaws"  and our mistakes.

**Comment by pear1** [comment]
@duongancol Thanks, I will do that

@danyj I can understand that, but I was talking more about backend and drag and drop browser itself.
About output loadtime I understand that thats all up to me.
Also can you show your theme? I would like to see that what you managed to build with Unyson.

**Comment by danyj** [comment]
>would like to see that what you managed to build with Unyson.

not done bud ,s till on it

**Comment by pear1** [comment]
Ok then, if anyone from Unyson page builder developers can look in to this issue, that would be great.

**Comment by GheorgheP** [comment]
So, I want to understand how the Page builder specifically breaks the VC?

I made some tests with VC and Page Builder and all seems to works fine, unless you do not use them both on the same page.

In case you use them both on same page, sure they will not work, as both overwrites the page content input.

Page Builder overwrites always VC because it processes the shortcodes on server, not directly in browser like VC is doing.

But I thinks it makes not sense to use 2 page builders on same page, it's a normal thing to conflict with each other, as they have to edit same input, but the formats are different.

**Comment by kaxigt** [comment]
One of many reasons why I chose to use Unyson it's the clever handle with codes. IF I (for some reason) want to unistall Unyson it NEVER left any braking codes in posts or pages. It's excellent handle and I can save this little line until I re-install, and voliá, my context are still there =) Compare this to what VC are left behind...

However, sure it would be nice with some more features like nested grids, ability to change gutter, use of light box, perhaps some animation abilities on posts, images, and links. Just to mention some features. Beside that I'm satisfied with this framework =)

**Comment by GheorgheP** [comment]
About nested columns, you can refer this issue https://github.com/ThemeFuse/Unyson/issues/2485#issuecomment-292802003

Here @andreiglingeanu implemented a solution for this.
