### ISSUE TITLE
Is this filter removed?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2459]
@GheorgheP   is this filter `fw_db_big_data_update_enable `not to be used anymore https://github.com/ThemeFuse/Unyson/issues/838  ? 

I see there were changes https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/search?q=fw_db_update_big_data&type=Commits&utf8=%E2%9C%93

so is the big data method now part of the builder core and if yes is it enabled by default or?

**Comment by GheorgheP** [comment]
I'm nor really familiarized with the `fw_db_update_big_data` function as it was developed by @moldcraft and was added as an internal functionality. 

But it was removed because the `fw_db_update_big_data` didn't really help with anything, as the main feature of the `fw_db_update_big_data` was to use the **SQL** `CONCAT` functions, as has it's own limitations, and we came back to same problem.

**Comment by danyj** [comment]
> didn't really help with anything

in this case it helped alot since I was hitting the limit https://github.com/ThemeFuse/Unyson/issues/838#issuecomment-163227965

I also see this  in the note http://prntscr.com/eq8npe  so wondering if he incorporate the same method somewhere else

**Comment by GheorgheP** [comment]
Here is the original commit where the function was removed https://github.com/ThemeFuse/Unyson/commit/7d4e43c5c7820ed74f7b249644c18adca53b1c02.
As you can see from description: `it doesn't help with big data because CONCAT() has limits`.
Also in [meta.php](https://github.com/ThemeFuse/Unyson/commit/528a075d08bef95613dc4b0a6c20d3a1f26de1b0) function was not changed the `fw_db_update_big_data()` was replaced with `$wpdb->update`, same thing is doing wordpress.
So I think the `fw_db_update_big_data()` was just removed.

The other thing is that we mostly can get this problem because of page builder, but now the page builder saves the content under another meta key, to the `fw_options` is not so big.

**Comment by danyj** [comment]
> saves the content under another meta key

I think that one "fixed"   the issues I had , and we did not notice thinking big data was doing it
