### ISSUE TITLE
Can't save any new settings

### ISSUE THREAD

**Issue by BDAPete** [ThemeFuse/Unyson#2460]
Hi, hope you can help!

I can't seem to save any settings within Unyson. So I'm trying to include our site's social API info and when I try to save, the fields get wiped. The same goes for any checkbox settings I try to change, for example, I need to include the Visual Page Builder on the Product element, but again, when I check the box and save, it gets wiped. 

I've already tried deactivating all plugins to see if there is a conflict, but no joy.

Any ideas? 

Cheers, 

Peter

**Comment by GheorgheP** [comment]
Hmmm, are you able to provide dashboard login details and ftp details to investigate this?
Send them on `pisarenco.gh[[at]]gmail.com`

**Comment by BDAPete** [comment]
Sure, that would be great, thanks. I'll fire them through to you now. Much appreciated, 

Peter

**Comment by GheorgheP** [comment]
I fixed, but the problem is from us, specifically from `fw_current_url()` function, your domain name was prefixed with `www.` but `fw_current_url()` return the domain without `www.` prefix, so when the form is submitted, it is submitted to a non valid address. What I've done now, just removed the `www.` prefix from **Settings>General**, but in case you need with `www.` you can add it back. 

I will investigate this issue.

**Comment by dinhtungdu** [comment]
+1 for this. I currently have this issue on my dev machine.
WordPress Version 4.7.3 | Unyson 2.6.15. All extension is latest.
This is what happened when I tried to save extension setting: http://prntscr.com/el67dj

**Comment by BDAPete** [comment]
Ah that's fantastic, thanks so much for that! I'm going to be installing an SSL tomorrow and will obviously  need to update the htaccess file and WP site fields to include a https prefix - Will this have an impact or is this ignored by the fw_current_url function?

Thanks again :-)

Peter

**Comment by GheorgheP** [comment]
It doesn't have to affect the SSL any ways
