### ISSUE TITLE
Backup both users and usermeta table.

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#2477]
Is there any hooks so that when we create a content backup by extension BackUp and Demo Content we can keep both data from the 2 table users and usermeta.
I tried to create a Full Backup, but it always skip user data.

**Comment by GheorgheP** [comment]
At the moment this is not possible, but I will review.

The fact is that it is easy to change that but setting the [fw:ext:backups:db-export:tables](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/ff794c86b060bd36e65837f14626c797cb0046e6/includes/module/tasks/type/class-fw-ext-backups-task-type-db-export.php#L326) filter below the code where the tables are [excluded](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/ff794c86b060bd36e65837f14626c797cb0046e6/includes/module/tasks/type/class-fw-ext-backups-task-type-db-export.php#L347). But the problem is that during the backup restore process, the database restore, we check if is full backup or content backup, by checking ig the [users table](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/a0dc705c9c9333458dffecce28eea6e47e8218e6/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L361) is in tables list. I need to find another solution for that, as you'll add the users table back in tables list during backup export, then, during restore, the backup will be trated as full backup instead of content.

**Comment by andreiglingeanu** [comment]
@TrangDinhVan Refer to #2666 and enter your input there.

@GheorgheP in the example you gave, the `users` and `usermeta` tables are not excluded at all from the backup. See the whole condition [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/ff794c86b060bd36e65837f14626c797cb0046e6/includes/module/tasks/type/class-fw-ext-backups-task-type-db-export.php#L330-L351).
