### ISSUE TITLE
curl 7

### ISSUE THREAD

**Issue by randyshane** [ThemeFuse/Unyson#2512]
no matter what i do, what computer I'm on, or how many times i do this, i cannot get the unyson plugin extensions to work. they all say the cannot connect curl 7 error code, and its every single extension, not just one. and its making mad because i have been trying for days now, and all i want is this d*mn theme that i bought to work. and i want someone to respond like i was told they would when i bought the theme to begin with.

**Comment by danyj** [comment]
CURLE_COULDNT_CONNECT (7)

Failed to connect() to host or proxy.

if this is your own server make sure that outside connections are allowed 
it could be firewall or hosting setup  that is not allowing connection to git. 

@GheorgheP worth looking at 
http://stackoverflow.com/a/9923212/594423

**Comment by GheorgheP** [comment]
Usually this happens because of server security restrictions.
The extensions are downloaded from `http://github-api-cache.unyson.io` url, and for some hosting providers this URL is not safe. You can ask the hosting provider to open access to that resource.

In case they refuse to do this, you can add this code in `functions.php` of your theme:

```php
function _action_fw_remove_the_unyson_extensions_update_resource() {
	remove_filter( 'fw_github_api_url', '_fw_filter_github_api_url' );
}

add_action( 'init', '_action_fw_remove_the_unyson_extensions_update_resource' );
```

But I really insist on the first option as the second one may create problems, as you can easily reach the github download limit and you will get blocked for few hours.

**Comment by uhlhosting** [comment]
cURL error 7: Failed to connect to github-api-cache.unyson.io port 80: Connection refused 

@GheorgheP, I am my own provider, and nothing blocks my outgoing connections, unless BitNinja, or CSF does. I checked those and were not the source of the trouble... Anyone any fix for this?

**Comment by ivanblazevic** [comment]
why is this closed ?

**Comment by ivanblazevic** [comment]
@ViorelEremia
