### ISSUE TITLE
Backup mkdir(): File exists bug

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2513]
Last evening I setup backups schedule to test it. Than shut computer down  , schedule was for 3am 

![screenshot_9](https://cloud.githubusercontent.com/assets/2340172/24916811/8ac95b68-1edb-11e7-91c8-052098ec97ad.jpg)

just now I saw that backup was created at 4:28am , ( how , computer was off? ) 

so I clicked on create contet backup and the spiner showed up and was gone , error log says 

`PHP Warning:  mkdir(): File exists in T:\wamp64\www\xxxxx\wp-content\plugins\unyson\framework\extensions\backups\includes\module\tasks\type\class-fw-ext-backups-task-type-dir-clean.php on line 35`

so it looks like it was trying to do a cleanup from previous backup when I clicked on  create content backup. 

Second time the backup ran. This is just heads up to make sure that there are no bigger issues..

**Comment by GheorgheP** [comment]
First of all the time that shows you the computer depends on the Wordpress/Php timezone configuration.
What abut error, I cannot tell specifically what it may be, but I think is very simple. You enabled the backups schedule, it started to work, but during the process you turned off the computer, so it was interrupted in the middle of process. When you started the server back and run the page, the backup wanted to continue the work, and there it remained at the step for creating he directory. In few words, the problem was from that interruption.
After all this sholdn't affect your system, as the backup process doesn't remove anything except the data from `uploads/bf-backup/temp` directory that you shouldn't need to care of.
