### ISSUE TITLE
Selectize.js with Unyson

### ISSUE THREAD

**Issue by 9585999** [ThemeFuse/Unyson#2533]
Hello, does not work Selectize.js, what could be the problem? Help solve this problem.

The plugin did not change anything in the files ...

![img 2017-04-16 23 28 08](https://cloud.githubusercontent.com/assets/16165904/25074177/1f8e8e64-22fe-11e7-9016-ef74e309caa1.png)

**Comment by GheorgheP** [comment]
What do you mean that it doesn't work? We don't use Selectize on font size and font wight.

**Comment by 9585999** [comment]
Truly, I'm sorry, I just thought that selectize.js is used for all select, but then after watching some videos from the documentation, I noticed that this is not true.

And even I think it would be good to selectize.js was at all select.

**Comment by GheorgheP** [comment]
We will think about this, but the fact is that is affects the page speed and memory usage.

**Comment by 9585999** [comment]
It will be cool if you connect this script to all the selections.

But while it's not there, can you tell me the correct solution as I can do it myself, I tried to initialize it through jquery, but jquery does not see the select which are generated by your framework...

**Comment by danyj** [comment]
> will be cool if you connect this script to all the selections.


I dont agree , selectize is not using select on change event and forces us to use their change event, other devs scripts that might do something on select change would not work anymore, 

https://github.com/selectize/selectize.js/issues/102

http://stackoverflow.com/questions/24666297/how-to-get-the-value-of-the-currently-selected-selectize-js-input-item


even if they have fixed this in meantime changing default selects to 3rd party lib just because they might look nice is not something framework should do. 

now days select can be easily styled with CSS  only. 

you can easy make own select option with selectize and than use that in your theme 
http://manual.unyson.io/en/latest/options/create-option-type.html
