### ISSUE TITLE
Multi picker improvement suggestion 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2560]
@mowshon @andreiglingeanu @GheorgheP 

can someone  please explain why is it that we keep all array keys if only one is used in frontend? 

for example you have multi-picker   with 2 sets of 5 options each ,  
![screenshot_17](https://cloud.githubusercontent.com/assets/2340172/25596605/4338e418-2eca-11e7-8d44-f56af2657331.jpg)

in case above youtube can be unset and its default loaded  in backend.

This would lower the data usage tremendously and at the same time improve the option itself.

**Comment by danyj** [comment]
The current for does this , 

imagine above option with 5 or 10 sets , you switch each set , save each set option and they are always there no matter if they used or not.  

Unseting the unused keys would never save them if they are not picked

**Comment by danyj** [comment]
Here , test this, add this to multi 


```
    /**
     * @internal
     */
    protected function _unset_unused($value,$picker_key){
		
		foreach ( $value  as $key => $val){

			if($value[$picker_key] !== $value[$key] && $key !== $value[$picker_key]){
				
				unset( $value[$key] );
			}

		}
		return $value;
		
	}
```


in _get_value_from_input  before the value return https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/multi-picker/class-fw-option-type-multi-picker.php#L399 add 


    $value = $this->_unset_unused($value,$picker_key); 


I checked backend  no issues , front comes back clean with picked option and depending key with values.

**Comment by danyj** [comment]
is not tested 100% but you get the idea , dont send all that unused data to DB and front , send only what is used.

**Comment by GheorgheP** [comment]
I understand you idea, but what will happen with other values?
I don't think that users will like the fact that you erased options `a,c,d,e` because you chose the `b` option.
Imagine that you made a test about how it will looks with option 2, and all settings from option 1 was erased.

For example in The Core: 

![](https://static.md/8cb0650cb0b33c435d517678666d143c.png)

All selected options are related to the fixed width picker. So if I choose the full width just to test how it will look like, I lose all values from the fixed width.

Your idea is good, but I think it should be implemented by the developer specifically, or to set in picker option type a parameter to enable such functionality and every developer will enable it consciously.
But erasing users data because we want to optimize, is not acceptable.

**Comment by danyj** [comment]
> I understand you idea, but what will happen with other values?

I dont see how they erased,  here is video of your setup 
http://take.ms/MtWzb


>   or to set in picker option type a parameter to enable such functionality


yes that would be great!

**Comment by andreiglingeanu** [comment]
> I don't think that users will like the fact that you erased options `a`,`c`,`d`,`e` because you chose the `b` option.

Totally. This should never be happening.

**Comment by danyj** [comment]
that is why I asked for someone to give me the idea of the unused options use. 

are any of you using  the options that you have not picked? how and why are you using it? 
Are you using multi picker as a storage ? 

to me it makes no sense thus I asked 

> can someone please explain why is it that we keep all array keys if only one is used in frontend?

**Comment by andreiglingeanu** [comment]
Well no one's using options for unselected keys. The idea is that it is convenient for the user to have them saved - you don't loose work by making a single click on a image. I love the fact that they're not loosed.
