### ISSUE TITLE
Conflict with visual composer?

### ISSUE THREAD

**Issue by xttn** [ThemeFuse/Unyson#2589]
Hi, i use visual composer for page builder, i am trying to edit page by FRONTEND EDITOR mode (visual composer) and have issue, in my page have one shortcode use post type `fw-portfolio`.
It seems to have some conflict with Unyson, this is an error message:

> Notice: map_meta_cap was called incorrectly. The post type fw-portfolio is not registered, so it may not be reliable to check the capability "edit_post" against a post of that type. Please see Debugging in WordPress for more information. (This message was added in version 4.4.0.) in My-path\wp-includes\functions.php on line 4138

Can you try and tell me if it is a conflict?

**Comment by GheorgheP** [comment]
I cannot tell if there is a conflict or not, as I cannot test the VC plugin, because I do not have it.
But reading from in the error, it seems the `map_meta_cap` is called too early.

The `fw-portfolio` is registered on `init` action: https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/7d70b20ec9d1cbf4ba7e5aff3794a8148a7f7822/class-fw-extension-portfolio.php#L189
