### ISSUE TITLE
multi-picker option type loosing value

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#2606]
How to reproduce:

<details><summary>options.php</summary><p>

```php
<?php if ( ! defined( 'FW' ) ) { die( 'Forbidden' ); }

$options = array(
	'general' => array(
		'title'   => __( 'General', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			'general-box' => array(
				'title'   => __( 'General Settings', 'unyson' ),
				'type'    => 'box',
				'options' => array(
					'wego' => array(
						'type'  => 'multi-picker',
						'label' => false,
						'desc'  => false,

						'picker' => array(
							// '<custom-key>' => option
							'gadget' => array(
								'label'   => __('Choose device', '{domain}'),
								'type'    => 'select', // or 'short-select'
								'choices' => array(
									'phone'  => __('Phone', '{domain}'),
									'laptop' => __('Laptop', '{domain}')
								),
								'desc'    => __('Description', '{domain}'),
								'help'    => __('Help tip', '{domain}'),
							)
						),

						'choices' => array(
							'phone' => array(
								'price' => array(
									'type'  => 'text',
									'label' => __('Price', '{domain}'),
								),
							),

							'laptop' => array(
								'price' => array(
									'type'  => 'text',
									'label' => __('Price', '{domain}'),
								)
							),
						),
					)
				)
			),
		)
	)
);

```

</p></details>

<p></p>

1. Copy options and put them in `framework-customizations/theme/options/general-settings.php`
2. Make sure you reset theme settings
3. select `Phone` selected and insert `100` in price field - [screen](https://cl.ly/kThf)
4. Select `Laptop` and insert `200` in price. Leave `Laptop` selected - [screen](https://cl.ly/kTxk)
5. Save Theme Settings and refresh. Actually do a refresh here - very important.
6. After refresh you should see `Laptop` selected with `200`. Don't do anything - [screen](https://cl.ly/kTs7)
7. Click Save on Theme settings and refresh
8. After refresh, select `Phone` and watch the `Price`. The value will be lost. - [screen](https://cl.ly/kTa7)

Is that an expected behavior? Should we allow losing values in such a way?

<hr>

This is happening because of that [optimization](https://github.com/ThemeFuse/Unyson/blob/dbe86229984c812dc7529585f35f5e2a9814462b/framework/includes/option-types/multi-picker/class-fw-option-type-multi-picker.php#L84-L88) - we don't have all inputs in HTML when we are proceeding with the save, that is important.

cc. @danyj Do you think we should not allow losing that value?

**Comment by danyj** [comment]
> Is that an expected behavior

yes , that is exactly what I would expect since my chosen  option was laptop and not phone. 

The phone value is still there until you refresh the page. So while working adding values , switching back and forth all your values should be there.  Once you save , only saved value should be in DB . 

I dont see an issue here at all , 
you want to use multi picker as a storage facility as I advised earlier. 
If there is only one option that you can pick , than that is the option that we should save. 

If this was a multi check option and you loose one checked value that would be a bug , 

but thin of this ,  in a multi radio option you get to pick and save one option at the time , and output is exactly that , one option.

**Comment by GheorgheP** [comment]
No guys, this is a bug, and I have to say a serious one.
As I mentioned in other issue, we don't have to remove the user settings in any way.

Here is just an input and you may remember what was the value of the phone previously, but if there would be a lot of options, why would bring back them?

@danyj I understand your arguments, as we need only the value that we use. But as I mentioned, in case you just change for a moment to test how it looks like with other options, who will bring back the phone options? Yes, you may say that you should not refresh the settings page. Ok in this case this is just an excuse for why we did not made the things work properly, also this issue is everywhere, I men on page settings too, where you have to refresh the page when you update settings.

Other use case is that in `multi-picker` you may have some presets and depending on your disposition or position of Jupiter against other planets to select a preset or other. Let's say we have some discounts predefined and everyday or in every few days you picker and discount then another and every discount has configurations of **value**, **color**, **size**... How do you think the user will feel like when he/she 'll choose another discount and it will be empty?

No, this is an but and we have to solve it.

**Comment by andreiglingeanu** [comment]
@GheorgheP Agreed. You can solve that by not including the groups of options that are not selected as `data-options-template` - you just have to render them as you normally would.

That is, we can afford having a couple of options to not be rendered inside the page (look `lazy tabs`). But we can't afford having options only partially rendered, just like we have for `multi-picker`, and this bug is a clear example of what I mean by that.

**Comment by GheorgheP** [comment]
@andreiglingeanu I think everything is even easier.
The problem will solve this guy: https://github.com/ThemeFuse/Unyson/tree/feature-reactive-options
After we will introduce it, on `getValue()` `multi-picker` will look in his descendants and init them and receive the value of everyone.

**Comment by GheorgheP** [comment]
Or we can make it even smarter, in case it will be possible, to provide the value to it on render and on submit it will send the provided value on render. In case something will be changed, the the updated one too. But this is not so important for now.

**Comment by andreiglingeanu** [comment]
We can in theory implement `_get_value_from_input()` on frontend in `getValue()` but that is not the point of this discussion. We'll hold on for this bug until we get reactive options working.
