### ISSUE TITLE
Error Syntax error: Unexpected token in JSON at position 0

### ISSUE THREAD

**Issue by skenzo34** [ThemeFuse/Unyson#2616]
Hello!
We have this error when we try to save the theme parameters. How we can fix it?

**Comment by GheorgheP** [comment]
Please open browser developer tools and provide the file and line where this error is thrown.

**Comment by danyj** [comment]
could be https://github.com/ThemeFuse/Unyson/issues/2494

**Comment by GheorgheP** [comment]
Yes, may be that, but there are a lot of possibilities.

**Comment by skenzo34** [comment]
We haven't any error in the Console http://c2n.me/3KImsjO

**Comment by danyj** [comment]
@skenzo34  Open chrome , hit F12 and see this video to find out how to troubleshoot the ajax.
http://take.ms/8WgPm

click on admin-ajax.php  link , click on response tab , copy/paste the msg


@GheorgheP ,   I think is time a new issue contains small instructions on how to do this.  instead of just this 

> Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.

**Comment by GheorgheP** [comment]
@danyj I agree, your video is good, but to make it better I think you should use the Chrome request filter and to check `XHR` requests only, so you'll see only ajax requests.
