### ISSUE TITLE
Unyson WordPress theme example

### ISSUE THREAD

**Issue by guydumais** [ThemeFuse/Unyson#2624]
Not an issue, just to let you know that Unyson is an awesome framework, really! 
Here's a sneak peak of my upcoming WordPress theme:

![digex-apace-theme-version-2-beta-1-theme-settings-header-preview](https://cloud.githubusercontent.com/assets/3584604/26663763/f3ffaa6e-465a-11e7-857a-f9f16ae8dece.png)

Will let you know once released, see you!

**Comment by onebelarusianguy** [comment]
nice customization!

**Comment by guydumais** [comment]
Thanks onebelarusianguy 👍 

A lot of work though, but users and website developers will love. The Unyson Documentation and Forum helped me a lot to shorten the learning curve :P

**Comment by onebelarusianguy** [comment]
@guydumais I know :D I also did something like this :)

**Comment by danyj** [comment]
Congrats to all who are doing this ,
https://github.com/ThemeFuse/Unyson/issues/2415

 I did it 2 years ago but I also pushed this which  no one supported at the time
https://github.com/ThemeFuse/Unyson/issues/1092
but everyone is making custom changes to theme admin which seem like we all made it  a first task when we started using Unyson. 

Lets think forward and make sure that our changes will not be wiped out with some forced WP or Unyson change.  

I am still up for a full decoupling of theme admin CSS so that developers are free to customize it instead of doing endless CSS overrides and use of !important rule because of the over deceleration of class names. 

If you are up for it + the post and I can create new request but this time lest all push together.

 @guydumais  sorry for a small hijack.

**Comment by guydumais** [comment]
@danyj,

What I've found so far to do this customization with minimal impact on the framework and WP is by overriding the **FW_Theme_Settings** class and then change the **_form_render** function in it to load my own view file instead of the default one, using this ligne of code:
`$view = fw_get_template_customizations_directory( '/admin/views/backend-settings-form.php' );

This way, I have full control on the layout of the form and no needs to do endless CSS coding :P
`
