### ISSUE TITLE
Extensions deactivating themselves, Idea ? 

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#263]
Hello,
I got a really weird issue with Unyson from a customer that I can't figure out : 

> The Unyson extensions are not sticking. It seem to reset back after a day or two. What I mean by this is that my homepage is set to use the "Page Builder" extension, however after that day or two you only see the shortcode. What do I need to do to fix this.

>More like deactivating themselves. It appears that the Unyson is still active throughout the issue, but the extensions somehow are deactivated. I then reactivate them and after a day or two, they deactivate again.

>After I find that they have been deactivated, I'll find them again in the "Available Extensions" area. I then need to download them again so that they are activated on the theme once more.

Weird, no ? Do you have any idea ?  maybe server issue ? 

Thanks :)

2F

**Comment by danyj** [comment]
I am on it straight for 6 weeks or so. Did not run in to this issue. Possible issue I do see and it was fixed was this #256 and yes on update some extensions did not make it so they ended up being disabled or uninstalled and that might be what you customer has seen but did not pay attention to unyson msg's. Other than that I did not run in tot his.

**Comment by moldcraft** [comment]
Yes weird. I don't know why.

The only thing that comes in my mind is WordPress auto-update functionality that was added in 4.0 or 4.1. I never used/experienced it because on my localhost, FTP credentials are required every time the code wants to change some files (update WordPress, install/update extensions), I think the auto-update works only on servers where from code you can change any file you want at any time.
So when the WordPress auto-update starts in background, some weird things may happen (extensions are disabled or removed). **This is just my guess.**

**Comment by danyj** [comment]
@moldcraft I use autoupdate and today got msg that it did update WP but Unyson was ok.

**Comment by moldcraft** [comment]
@danyj Thanks for the info.

Then I have no idea what could cause that. Maybe other plugins, server backup/restore?

**Comment by danyj** [comment]
Reading it again

**Comment by 2Fwebd** [comment]
Thank you for the fast replies guys ! ;) 
I'll ask my customer to give more details and ask him to see also with hist host provider.

**Comment by moldcraft** [comment]
WordPress updates plugins automatically in background?

**Comment by dustinface** [comment]
Hey guys, its actually my site @ dustinface.com that is having this issue.  At this time the website is being hosted via HostGator with their "Baby Plan".  I just had to download the extensions again because the extensions were deactivated again on their own.  I did have an issue with the HostGator DB not saving and resetting, however that issue appears to be fixed.  The issue could be with plugins, but at the same time this was going on prior to me installing any other plugins, so although a viable option it doesn't seem possible.  I have found that the only extension that sticks all of the time is the Mega Menu extension, but I was also told that was the only extension that is actually pre-installed with the them files.  Is there a way to directly install these into the theme file?  Could the connection between my websites theme and the location of the Unyson extensions be somehow dropped?

**Comment by moldcraft** [comment]
Hello @dustinface 

As a temporary solution:
1. Install all extensions you need for your site
2. Open FTP
3. Move `{parent-theme}/framework-customizations/extensions/` to `{child-theme}/framework-customizations/extensions/`
4. Move `plugins/unyson/framework/extensions/` to `{parent-theme}/framework-customizations/extensions/`

As a result `plugins/unyson/framework/extensions/` will remain empty.

`FrameworkExtensions` -> `ParentThemeExtensions` -> `ChildThemeExtensions`

-----

I hope we will find the cause of this weird extensions disappearing.

**Comment by dustinface** [comment]
Ok.  I will go through those steps this weekend.  I will be sure to keep you all informed.  Thanks for the help thus far.

**Comment by moldcraft** [comment]
Only on plugin update all extensions are moved to a temporary directory, after the plugin was updated/replaced, they are moved back in `framework/extensions/`.

* [The action that is fired on plugin update](https://github.com/ThemeFuse/Unyson/blob/014f19aa198004e9cc60ec02cec86b2023b317f1/unyson.php#L110)
* [The code that moves the extensions to a temporary directory](https://github.com/ThemeFuse/Unyson/blob/014f19aa198004e9cc60ec02cec86b2023b317f1/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L240-L287)

No other code touches/deletes/moves the `framework/extensions/` directory *(except the Delete extension button)*.

So I have only 2 assumptions:
* The WordPress fires plugin update in background and some weird things happens
* The hosting does something with the files.

----

To check if plugin update start in background, you can change [this code](https://github.com/ThemeFuse/Unyson/blob/014f19aa198004e9cc60ec02cec86b2023b317f1/unyson.php#L107-L110) to:

```php
/**
 * Before plugin update
 */
file_get_contents('http://putsreq.com/VgsyN4aW56YDl1eOy3d1');
do_action( 'fw_plugin_pre_update' );
```

Then if the extensions will disappear, you can check [this link](http://putsreq.com/VgsyN4aW56YDl1eOy3d1/inspect). If a request was made, then the plugin update is the cause.

**Comment by 2Fwebd** [comment]
Thank you @moldcraft for all the help ;)

**Comment by danyj** [comment]
@2Fwebd bud what did you put in manifest.php as required extensions?

**Comment by 2Fwebd** [comment]
Hello Dan,
Nothing, just supported_extensions.

**Comment by danyj** [comment]
is bit strange that mega menu stays active. can you show is the manifest?

**Comment by 2Fwebd** [comment]
No that's normal because all the files of this extension are within the theme files ;) Because I changed it for the theme needs.

**Comment by danyj** [comment]
wait a sec , what are the folder permissions. maybe unyson is not getting access back to the folder to put extensions back after the update.  what I had an issue and you guys can test on local is this. 

open plugins/unyson folder, pick any file and open it in your favorite ide,
while the file is open try to update unyson, it will delete everything and fail to update because the file is open in ide and the folder  is  open in explorer. 
i ran in to this on dw and sublime
il be in office on  Monday and will show you screencast of this.

**Comment by moldcraft** [comment]
@danyj on local machine this can happen as you described with IDE open and you update the plugin manually (by clicking on Update button). But he is telling that this happens without pressing any button or doing something with extensions or plugin, he just goes to the admin side after a few days and all extensions are gone.

**Comment by dustinface** [comment]
That would be correct @moldcraft.  Good summary BTW.  : O)

**Comment by moldcraft** [comment]
> It seem to reset back after a day or two.

It's already a month after first message. Does it still happens every 2 days?

**Comment by moldcraft** [comment]
I'm closing this. Reopen (or comment) if the problem will happen again.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/588#issue-80054097
> I have setup a site in justhost server. after few min saw unyson deactivate automatically.
> 
> and then again yesterday night setup again. and now morning again plugin deactivate. o.O
> 
> what is the cause about this issue ??

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/745#issue-96442775
> Hi, I bought a Wordpress theme (Exposure by ThemeFuse) with the Unyson plugin.
> 
> The extensions are deactivating every day or every 2 days and I don't know why, I have to download and re-activate every single extensions of my webpage (christianbodensiek.com) because without those extensions my page is useless, what can I do?

**Comment by ddhouk** [comment]
I am having the same issue with the extensions deactivating every 2 days. I also have to download and reactivate them every time too. Then, my sidebar disappeared today at the same time. I got the buttons back, but can't figure out why my sidebar is gone or why the extensions keep deactivating. I don't know what else to do.

**Comment by dustinface** [comment]
Yup, mine is still doing the same thing.  Its pretty annoying.  It was working for about a month and then bam, same issues as described above.

**Comment by ddhouk** [comment]
Yes, it is annoying. There has to be a fix for this. I can't believe you haven been dealing with this for so long.

**Comment by dustinface** [comment]
Actually, they also said to move the "Plugins", but from their latest theme.  I did not see any Plugins folder.

My temporary solution:
1. Install all extensions you need for your site (you'll need to do this because it grabs the latest files)
2. Open your FTP client
3. Move {parent-theme}/framework-customizations/extensions/ to {child-theme}/framework-customizations/extensions/
4. Remove the /framework-customizations/extensions from parent

As a result the parent extensions folder stays empty.

I'd assume this will become an issue again if there is another update to the theme because you will need to do the same process again.  If you do not, than you will get an error and your child theme will crash.  Pretty shameful when you pay $53.00 for a theme and it does more harm than good.  The developers should try to find a more suitable way to fix this.  

My two cents: 

1. I'd assume the best way to fix this is to actually activate and provide the child theme with a WORKING version of the Unyson plugins out of the box.  
2. Maybe some type of "force open" even if the files will still need to be in parent, or a failsafe in the child if a check sees the files are not operational in parent.  
3. The last idea I had was to simply add the Page Builder and Breadcrumbs into the theme without activation, then add in the theme options to remove either one of those options.

The issue is that they are being deactivated after a few days, instead they should be as default activated with an option to deactivate.  Once deactivated the complete theme is a big pile of garbage because its reliant on the Unyson to make the theme functional.

**Comment by danyj** [comment]
@ everyone here ,   looks like all of you have the issue with same theme + unyson, does that theme comes with additional plugins beside unyson ? did developer combine some kind of auto theme update or something ?

**Comment by dustinface** [comment]
I'm not too sure.  I do know Unyson is a 3rd party developer and this theme actually integrates Unyson within its theme.  The question is whether the theme is the issue or the Unyson plugin is the issue.  I wish I had the time to sit there and figure it out, but I've got quite a bit on my plate already (which is why I purchased the theme rather than build it to begin with).

**Comment by danyj** [comment]
@dustinface  din't the theme come with customer support? I think @2Fwebd  is taking care of that.

**Comment by 2Fwebd** [comment]
Here I'am :) Of course it does !! 

Well, after 600 + themes sold working with Unyson and my themes, it's the only issue reported so I don't think it's caused by the theme. In my mind, as @danyj suggested it should be caused by a conflict with another plugin... @dustinface can we have please a screenshot of your plugins page ?

**Comment by danyj** [comment]
@dustinface  there u go bud , u did not pay $53.00 for no reason, unyson team would have figured it out if they can "see" the issue but as everyone else described seems like it is random and I can only assume incompatibility with some plugin or some kind of auto update site feature

**Comment by dustinface** [comment]
![screen shot 2015-07-25 at 12 08 13 pm](https://cloud.githubusercontent.com/assets/11093864/8890941/758b4532-32c8-11e5-90f2-b4d38e8ef68a.png)

There we go.  See attached.  

Just to be clear, I think I counted 3 people experiencing this issue in this thread, mine being the first in February.  I did get communication prior stating that I would need to move extensions to child theme, however I just assumed that between this time that we/I would have a longer suited resolution.

Also... I commend the theme, and I paid for it because I was willing to pay for it.  I like it.  However, just as anyone else I just dont like a broken theme on my website.

**Comment by llemurya** [comment]
@dustinface , @ddhouk  can you describe more concrete what actions you do before the all extensions are disabled.Maybe you install something or make updates or maybe you have cron jobs on the server, because the main problem for us is that we don't have the clear description of the bug.We don't know how to reproduce this issue. Please help us in order to fix us

**Comment by ddhouk** [comment]
I personally realized just by checking my website randomly and noticed the buttons and extensions were deactivated. I am not even doing anything at the time (i.e. installing a new plugin or working on my website), so it's very random. This last incident was interesting. I lost my sidebar and had to fix my menus under appearance because my widget was gone (where you customize your theme). I had to put everything back in my menu to appear again on my sidebar. I am not sure if that is related or not, but it happened at the same time. After I reactivated the extensions this last time, my pages also disappeared. I went to my webhost for help, but they couldn't figure it out either. They disabled the theme and plugins. I went back in when they were done and my pages were there by luck, but then I had to download and reactivate Unyson again. I lost my pages again!!! So, I knew it was something with the plugin. 

After process of elimination I found out it was the Translation extension causing my pages to disappear. Once I deactivated that extension my pages returned. However, the icon for Unyson was completely gone and I cannot edit anything or add anything without Uynson installed on my pages. Although I loved  Unyson, it's too much of a hassle, so I am trying Shortcodes Ultimate. I need to be able to rely on my website and find it too frustrating to deal with Unyson every other day. For the record, I don't believe I have the same theme. I use Dynamic News Lite. I hope this information helps someone.

**Comment by llemurya** [comment]
@ddhouk the pages don't disappear it remains, but the query of the posts is changing when you enable the translation extension and you can't see it, if you want to see the pages , posts  that you already create , you must set Convert data option value to yes from Translation Settings ,see this [printscreen](https://static.md/fcf9a818c35d11980de45dc0eafc0f8d.png).

**Comment by ecanziba** [comment]
Any solution on this, for me it deactivates all the plugins, and also deletes them, I need the page builder otherwise the dummy short-codes are displayed all over my live website.

**Comment by llemurya** [comment]
@ecanziba can you please say if you have the translation extension enabled?

**Comment by llemurya** [comment]
@ecanziba and if you can please send the ftp details at dev-team@unyson.io and don't enable the plugins , we want to see what is in the database. Thanks.

**Comment by ecanziba** [comment]
@llemurya The only plugin Enabled is the Unyson itself and inside Unyson the Page Builder Plugin, nothing else, it happens every 1-2 days it disabled automatically, and also it deletes all the plugins inside Unyson

**Comment by llemurya** [comment]
@ecanziba can you say if the extensions are disabled or you must download it after this bug happens? see the difference between these 2 types in this [printscreen](https://static.md/a1f4106e6f80f2c531ec460e76979e01.png)

**Comment by ecanziba** [comment]
@llemurya I need to download first, than it activates automatically. But after 1-2 days, I have to do the same process every day, we have a bunch of customers using our service, but they start complaining when they see the shortcodes of page builder.

**Comment by ecanziba** [comment]
@llemurya So the second example DOWNLOAD, it appears to me.

Thanks again for your time.

**Comment by moldcraft** [comment]
Do you have WordPress background update enabled? When you install a plugin, your site asks you FTP credentials or the dowload starts right away?

**Comment by ecanziba** [comment]
Yes everything is up to date, and for plugin install, it doesn't ask me for any credentials of FTP, but just downloads it as always.

**Comment by moldcraft** [comment]
> Yes everything is up to date

Good, but I am asking if your site makes WordPress updates in background https://codex.wordpress.org/Configuring_Automatic_Background_Updates

**Comment by moldcraft** [comment]
I see on that page the `auto_update_plugin`, I will use it to stop background updates for Unyson plugin. Maybe that will help

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/107

**Comment by moldcraft** [comment]
> https://wordpress.org/support/topic/extensions-are-deactivating-every-2-days?replies=3#post-7238820
> 
> yes, I have the 2.4.3 version and still auto-deactivating the extensions.
>
> WordPress and all plugins (including Unyson) are updated.

**Comment by moldcraft** [comment]
http://wordpress.stackexchange.com/questions/196118

**Comment by ecanziba** [comment]
Have been three days in a row now, and everything looks great with last update 2.4.3 , and I also disabled all Auto Updates of Wordpress, try to do the same, and replace files manually on Unyson Folder. Thanks to moldcraft update looks good till now, hope this will solve you the problem.

**Comment by moldcraft** [comment]
> I also disabled all Auto Updates of Wordpress

I heard a client that this helped him too, but this is not a good solution, we can't require all Unyson users to disable auto updates, we need to find the problem and fix it.

**Comment by ecanziba** [comment]
It is very unusual, I have the same theme in two different websites, but in the same hosting provider. On first website this never happens, on the second one, it happens every 2-3 days.

**Comment by moldcraft** [comment]
WordPress has a background action, the auto-update.
But the Backup extension also does background actions, maybe the problem is in it?
All users with "extensions disappearing every 2-3 days", do you have the Backup extension installed?

**Comment by moldcraft** [comment]
I will try to get deeper in WordPress core to understand how the automatic update works, when and how it is started, to be able to start it manually and debug the code.

If you are already familiar with how it works, please share, to save my time.

**Comment by danyj** [comment]
Just brainstorming . 

Check this out 
https://codex.wordpress.org/Configuring_Automatic_Background_Updates

In special cases plugins are updated on autoupdate
and according to this guy  plugins are deactivated on failed update 
http://wordpress.stackexchange.com/questions/51024/can-a-plugin-deactivate-itself

can it be that our Unyson extensions are about to be updated via wp autoupdate and they fail to reach git or simply dont have link for it?

**Comment by moldcraft** [comment]
they don't need git. on update start the extensions are copied (not moved) to a temporary directory, then on update end they are moved from that temporary directory in the newly downloaded and extracted plugin (that contains only those 2 pre-installed extensions `blog` and `update`).

----

I just found [the function that makes the auto-update](https://github.com/WordPress/WordPress/blob/731c255aee26a309a734a88680b8793e7fff3069/wp-includes/update.php#L488-L499), and where it is set on cron [1](https://github.com/WordPress/WordPress/blob/731c255aee26a309a734a88680b8793e7fff3069/wp-admin/includes/class-wp-upgrader.php#L3031), [2](https://github.com/WordPress/WordPress/blob/731c255aee26a309a734a88680b8793e7fff3069/wp-includes/update.php#L659)

**Comment by moldcraft** [comment]
Yes! I was able to make the extensions disappear.

Inspecting why this happens...

**Comment by danyj** [comment]
@moldcraft :+1:  glad u find the start. let me know if u need some testing

**Comment by moldcraft** [comment]
I found an interesting/bad situation 

*This is not affecting auto update because the plugin is not auto-updated if it's disabled. At least this is what I realized inspecting the code, not sure 100%*

![](https://static.md/6a1db29840a69e1eb1dfc9138840eacf.png)

**Comment by moldcraft** [comment]
P.S. [This filter](https://github.com/ThemeFuse/Unyson/blob/1c7d7214002311d370676fb34049bc8d6252b05e/unyson.php#L153-L166) actually works. When I debug I do `return true;` to allow auto-update.
So those who are still experiencing extensions disappearing, maybe they have an older version of Unyson, because that fix was added in [v2.4.3](https://github.com/ThemeFuse/Unyson/releases/tag/v2.4.3) 15 days ago, quite recently, taking in consideration that we had a bug report with Unyson v2.**2** [1 week ago](https://wordpress.org/support/topic/all-layout-elements-now-are-inside-a-text-block?replies=5#post-7248090) (so I don't know the percentage of people which are updating right after we release a new version, and those who have installed *ancient* versions of the plugin)

Right now I will add just some improvements in handling WP update actions, but the main logic will remain.

P.P.S. I haven't found how to reproduce https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-130012760 auto-update works fine (extensions do not disappear). I don't rembember, maybe I interrupted the update while debugging the code, so the extensions were not restored.

**Comment by danyj** [comment]
@moldcraft  thnx for all the info and hours of debugging. so the logic now is  ( since  2.4.3 )   
disable plugin autoupdate via 
https://github.com/ThemeFuse/Unyson/blob/1c7d7214002311d370676fb34049bc8d6252b05e/unyson.php#L153-L166
 before the update kicks in or WP autoupdate will try to do it for us. Right ?

**Comment by moldcraft** [comment]
### How to test auto-update

1. Open `wp-content/plugins/unyson/unyson.php` and decrease the version

    ```php
    /**
     * ...
     * Version: 2.0.0
     * ...
     */
    ```

2. Change [here](https://github.com/ThemeFuse/Unyson/blob/1c7d7214002311d370676fb34049bc8d6252b05e/unyson.php#L161) to `return true;`

3. Add in `{theme}/functions.php`

	```php
	if (isset($_GET['test-auto-update'])) {
		add_action('init', function () {
			wp_maybe_auto_update();
		});
	}
	```

4. Open `http://your-site.com/wp-admin/?test-auto-update=1`

5. Check if the version in `wp-content/plugins/unyson/unyson.php` has been changed, and if extensions did not disappear :)

**Comment by danyj** [comment]
@moldcraft  shutting down for today as we speak , will do few test on it tomorrow,  thnx for instructions.

**Comment by moldcraft** [comment]
> @danyj so the logic now is ( since 2.4.3 )
>
> disable plugin autoupdate via 
> https://github.com/ThemeFuse/Unyson/blob/1c7d7214002311d370676fb34049bc8d6252b05e/unyson.php#L153-L166
> before the update kicks in or WP autoupdate will try to do it for us. Right ?

Like I said in https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-130067795 I still can't reproduce this.

At the moment I know only two ways to make extensions disappear:

1. Update the plugin manually while it's disabled
2. Break the execution between [these two actions](https://github.com/WordPress/WordPress/blob/dc4c2fa0bfed16cb20065568f704050c620268f4/wp-admin/includes/class-wp-upgrader.php#L423-L546) `upgrader_pre_install` and `upgrader_post_install` (that are used as before and after plugin update).

    So breaking the execution will result in the second action to not being executed.
    But on what I am working now, I found [another (better) action](https://github.com/WordPress/WordPress/blob/dc4c2fa0bfed16cb20065568f704050c620268f4/wp-admin/includes/class-wp-upgrader.php#L697) that is executed even if the plugin update fails (I will use it instead of the `upgrader_post_install` action)

*P.S. Shutting down too.*

**Comment by danyj** [comment]
@moldcraft   ok , test with instructions above and  unyson is deactivated after autoupdate
http://prntscr.com/83pey7

after activation 
I did not loose any extensions
http://prntscr.com/83pf2z

**Comment by danyj** [comment]
note , I'm testing on wamp, win10 ,
Unyson was same version 2.4.4 , 
performed the test 3 times and did not loose any extensions

**Comment by moldcraft** [comment]
> 2 . Break the execution between [these two actions](https://github.com/WordPress/WordPress/blob/dc4c2fa0bfed16cb20065568f704050c620268f4/wp-admin/includes/class-wp-upgrader.php#L423-L546) `upgrader_pre_install` and `upgrader_post_install` (that [are used as before and after plugin update](https://github.com/ThemeFuse/Unyson/blob/1c7d7214002311d370676fb34049bc8d6252b05e/unyson.php#L104-L128)).
> 
> So breaking the execution will result in the second action to not being executed.
> But on what I am working now, I found [another (better) action](https://github.com/WordPress/WordPress/blob/dc4c2fa0bfed16cb20065568f704050c620268f4/wp-admin/includes/class-wp-upgrader.php#L697) that is executed even if the plugin update fails (I will use it instead of the `upgrader_post_install` action)

Sorry, that affirmation is wrong.

On first action, the extensions are **copied** (not moved) to a temporary directory, if the execution is interrupted, the plugin is not updated at all and the extensions are still there (the actual plugin replace happens [here](https://github.com/WordPress/WordPress/blob/dc4c2fa0bfed16cb20065568f704050c620268f4/wp-admin/includes/class-wp-upgrader.php#L483-L523))

**Comment by moldcraft** [comment]
I can't start auto-update when [this filter](https://github.com/ThemeFuse/Unyson/blob/1c7d7214002311d370676fb34049bc8d6252b05e/unyson.php#L153-L166) is removed. I tried with plugin enabled and disabled, I installed other plugins and decreased manually the version (the third, second or first part of the version `v1.2.3`) but the update won't start.

I found that [this](https://github.com/WordPress/WordPress/blob/dc4c2fa0bfed16cb20065568f704050c620268f4/wp-admin/includes/class-wp-upgrader.php#L2635) `$item->autoupdate` is not defined and `$update` becomes `false`, that's why it son't start. If you hook in [this filter](https://github.com/WordPress/WordPress/blob/dc4c2fa0bfed16cb20065568f704050c620268f4/wp-admin/includes/class-wp-upgrader.php#L2656) and `return true;` (like I explained in https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-130073501) then it will start, but this is 'force start' that will not happen in production.

I can't find where that `$item->autoupdate` comes from. I did a search in all WordPress/project files for word `autoupdate` and there is no place where it is assigned/created
![](https://static.md/6883a22d868ea018f7f81f9098c8e3a5.png)

I added [here](https://github.com/WordPress/WordPress/blob/dc4c2fa0bfed16cb20065568f704050c620268f4/wp-admin/includes/class-wp-upgrader.php#L2872) `var_dump($plugin_updates);` and it contains the same info as that `$item` (that is checked for `$item->autoupdate`)

```
object(stdClass)#155 (6) {
    ["id"]=> string(5) "55635"
    ["slug"]=> string(6) "unyson"
    ["plugin"]=> string(17) "unyson/unyson.php"
    ["new_version"]=> string(5) "2.4.4"
    ["url"]=> string(37) "https://wordpress.org/plugins/unyson/"
    ["package"]=> string(55) "https://downloads.wordpress.org/plugin/unyson.2.4.4.zip"
}
```

I searched `set_site_transient( 'update_plugins'` and I found that [those objects are coming from wordpress.org](https://github.com/WordPress/WordPress/blob/dc4c2fa0bfed16cb20065568f704050c620268f4/wp-includes/update.php#L281-L331) so it looks like **wordpress.org decides which plugin should make auto-update by setting it that `autoupdate` property**.

**Comment by danyj** [comment]
@moldcraft  This you see this 
https://github.com/WordPress/WordPress/blob/c9027b00babeb36a58b233ae290e190beecbd655/wp-admin/includes/update.php#L79-L91

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-130287690

@danyj Sorry, I don't understand, what that has to do with plugin updates?

**Comment by danyj** [comment]
Sorry  just saw it up ,
https://github.com/WordPress/WordPress/blob/c9027b00babeb36a58b233ae290e190beecbd655/wp-admin/includes/update.php#L64

 it is for core , still searching

**Comment by moldcraft** [comment]
> still searching

Searching for what? :)

**Comment by danyj** [comment]
>  I can't find where that $item->autoupdate comes from

**Comment by moldcraft** [comment]
Continuing https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-130286386

### How to set `$item->autoupdate`

Run this code

```php
$plugin_updates = get_site_transient( 'update_plugins' );

if (
    !empty($plugin_updates->response)
    &&
    !empty($plugin_updates->response['unyson/unyson.php'])
) {
	$plugin_updates->response['unyson/unyson.php']->autoupdate = true;

	set_site_transient( 'update_plugins', $plugin_updates, 60 * 3 );

	print_r($plugin_updates);
}
```

After setting it, auto-update started (without [this filter](https://github.com/ThemeFuse/Unyson/blob/1c7d7214002311d370676fb34049bc8d6252b05e/unyson.php#L161)).

**Comment by moldcraft** [comment]
@danyj https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-130292715 But [I found that it comes from wordpress.org](https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-130286386)

... this also looks confusing for me.

What we have at the moment:

* Auto-update works fine, extensions are not lost, if plugin is enabled.
* Extensions are lost only when the plugin is updated while it is disabled.
* Why the plugin is disabled after auto-update?
* Maybe on some clients happens this:

    * The plugin is auto-updated and it is disabled (all pages on the site are not working)
    * While it is disabled, after a few days (when we release a new version) it auto-updates again (note: **while it is disabled**), then extensions are lost.

* Why wordpress.org decided to send that `$item->autoupdate` in api responses and how they decide when to set that property or not?

**Comment by moldcraft** [comment]
> Why wordpress.org decided to send that $item->autoupdate in api responses and how they decide when to set that property or not?

http://wordpress.stackexchange.com/a/172764/60424

It seems that parameter is used only for core updates, for e.g. to specify that an update is critical (contains security fixes) and should be made automatically.

I am thinking that autoupdate actually never happens for plugins, it never happened for Unyson and the problem may be in something else (not autoupdate).

**Comment by danyj** [comment]
@moldcraft  well I dont know how others construct their themes but  so far I know if plugin is disabled builder shortcodes are not functional so they must have noticed Unyson being disabled but did they report on time is another thing.  


Maybe we can detect update finish and run the code to activate plugin ?  Just in case is deactivated.

**Comment by moldcraft** [comment]
There is [a plugin to enable auto-updates for plugins](https://wordpress.org/plugins/automatic-plugin-updates/) so it demonstrates that auto-updates are not enabled by default for plugins.

**Comment by moldcraft** [comment]
Here we are again at the point when I have no idea why on some clients extensions are disappearing.

If I remember correctly, they are saying (also this happened on our test server) that only extensions disappeared, but Unyson is active, I never heard/remember someone saying that Unyson was disabled.

**Comment by danyj** [comment]
OK sorry about all this back and forth but I want to understand  Unyson update process in detail, 
in Joomla extensions/plugins/templates/modules update is simple files override zip extracted in tmp , than moved to destination , in Unyson is this 

User clicks on update 
Unyson copies extensions to tmp 
Unsyon folder is removed ( ? not sure if this is true ) 
Git downloaded  and extracted 
Tmp extensions copied back 

Is this accurate ?

**Comment by moldcraft** [comment]
* User clicks on update
* WordPress downloads the new Unyson version from wordpress.org and extracts it to a tmp dir
* Unyson **copies** extensions to tmp (it's a new created directory, it doesn't conflict with WP's tmp dir)
* WordPress removes Unyson folder
* WordPress moves the new Unyson version from tmp to plugins/ directory
* Unsyon moves extensions from tmp back to unyson folder

**Comment by danyj** [comment]
Thnx for the info , very helpfull 
If autoupdate is messing it up than we might have a hint 
The last part 

> Unsyon moves extensions from tmp back to unyson folder

is not happening and it could be due to

1.  Unyson inactivation  ( cant move if it is inactive )
2. folder permission

**Comment by moldcraft** [comment]
> If autoupdate is messing it up

We just concluded that plugins don't have autoupdate.

> it could be due to: Unyson inactivation ( cant move if it is inactive )

Yes, that sure is happening. But this happens only when the user updates the plugin manually while it is inactive.

> it could be due to: folder permission

very unlikely, because wordpress and we (Unyson) uses WP_Filesystem that takes care to create files and folders with right permissions.

**Comment by moldcraft** [comment]
I tried core auto-update with Unyson enabled and disabled, extensions did not disappear.

P.S. Core version is in `wp-includes/version.php`. Decrease the third part `'4.2.X'`

**Comment by danyj** [comment]
@moldcraft   works ok for me but I never seen this issue either so looks like wamp is ok with it. WP is on autoupdate anyway. It would help more if some of the users that have the issue let us test on their server.

**Comment by moldcraft** [comment]
We found this in `wp-config.php` on a site, hosted on Hostgator, that has this problem

```php
add_filter( 'auto_update_plugin', '__return_true' );
add_filter( 'auto_update_theme', '__return_true' );
```

Hostagor has this [automatic WordPress install](http://support.hostgator.com/articles/specialized-help/technical/wordpress/how-to-install-wordpress) and maybe it puts those lines there.

What is weird, we tried to reproduce the problem, and we succeded, but only a couple of times. For e.g. we do some steps, extension disappear, then we try again the same steps, and the auto-update doesn't start (so it still happens randomly).

In `ABSPATH /fw-update.log` we got this

```text
[2015-08-13 13:34:08] fw_plugin_pre_update
[2015-08-13 13:34:08] fw_plugin_post_update
[2015-08-13 13:34:09] fw_automatic_update_complete OK
```

[This filter](https://github.com/ThemeFuse/Unyson/blob/0050bd21d4918e9dc68587284cee8fd2c797c0f5/unyson.php#L185-L196) is not executed.

Anyway, `fw_plugin_post_update` is executed, so extensions should be copied back. Maybe the update happens multiple times when Unyson somehow is deactivated (updated and extensions disappear) then reactivated .... weird

We will inspect further and will let you know when we will be able to find a stable way to reproduce the problem (the disappearing extensions).

----

Also there is soft the is installed in cPanels http://www.softaculous.com/softaculous/ that has these options

![](https://static.md/f508da7ba30c24d6c0660a78792149c9.png)

**Comment by moldcraft** [comment]
@dustinface Do you have in `wp-config.php`

```php
add_filter( 'auto_update_plugin', '__return_true' );
```

? 

If yes, please delete that line to stop plugins auto-update.

**Comment by dustinface** [comment]
Hello.  If its in there by default I'm sure the little pest is in there.  When deleting, will WP ever write over this upon a new update or is WP-Config one of the files that does not get updated during a WP core update?

**Comment by danyj** [comment]
@dustinface  @moldcraft  check this out 
https://wordpress.org/support/topic/i-got-auto-updated-yesterday-broke-my-site-how-to-disable-auto-update

**Comment by moldcraft** [comment]
> @dustinface When deleting, will WP ever write over this upon a new update or is WP-Config one of the files that does not get updated during a WP core update?

wp-config can't be replaced on update because is contains database connection info, so your site will not work if it will be replaced on update.

----

@danyj Thank you for confirming our info.

----

Replacing that line with

```
add_filter( 'auto_update_plugin', '__return_false' );
```

si the same as removing it, because by default it is false.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-130718207
>
> In ABSPATH /fw-update.log we got this
>
> [2015-08-13 13:34:08] fw_plugin_pre_update
> [2015-08-13 13:34:08] fw_plugin_post_update
> [2015-08-13 13:34:09] fw_automatic_update_complete OK
>
> [This filter](https://github.com/ThemeFuse/Unyson/blob/0050bd21d4918e9dc68587284cee8fd2c797c0f5/unyson.php#L185-L196) is not executed.

Wrong. It is executed, but before the filter set in `wp-config.php`

```php
add_filter( 'auto_update_plugin', '__return_true' );
```

so its value (`false`) is overwritten by the filter from `wp-config.php` (`true`). I [fixed](https://github.com/ThemeFuse/Unyson/blob/4ada6571c2c0dba220d4bb65dd70327614e6d3f8/unyson.php#L134) that (set filter priority `9999`).

Why `fw_plugin_auto_update_stop` is not in `fw-update.log`? Because at that point `$wp_filesystem` is not initialized.

[ ![](https://static.md/b647853e435f24f899bbe509731aaac7.png) ](https://static.md/b647853e435f24f899bbe509731aaac7.png)

**Comment by danyj** [comment]
nice one , was about to ask if priority would override wp-config.php filter , but you got it. Let's hope this fixes it.

**Comment by moldcraft** [comment]
This sure will stop the auto-update.

But I am curious why extensions disappear. We tried to simulate auto-update but extensions did not disappeared. I am inspecting this now...

**Comment by moldcraft** [comment]
### How to test auto-update

Your WP installation must not require FTP credentials on plugins or extensions install.

1. Decrease Unyson version in `wp-content/plugins/unyson/unyson.php`

    Important: Decrease only the last digit (third).

    ```php
    /**
     * ...
     * Version: 2.4.0
     * ...
     */
    ```

2. Make sure you don't have `add_filter( 'auto_update_plugin', ...);` in `unyson.php` (comment or delete it).

3. Open phpMyAdmin and delete `wp_option` named `cron`. You can run this SQL:

    ```sql
    DELETE FROM `wp_options` WHERE `option_name` LIKE 'cron'
    ```

4. Open admin page (plugins page) and repeat:

    1. Refresh
    2. Wait 1 second

    until Unyson will be auto-updated.

    If after 10 refreshes nothing happens. Run the steps 3. and 4. again.
