### ISSUE TITLE
[bug] Missing single project and single events in menu

### ISSUE THREAD

**Issue by pionir** [ThemeFuse/Unyson#2634]
We are missing single project and single events inside the menu, only thing available are their categories.
http://prntscr.com/fgaf22

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Events-Extension/issues/17
Specifically for events, I think it makes no sense at all to add them in menu, as events are temporary.
This is the reason we did not add them. But you can add them easily with above solution.

**Comment by danyj** [comment]
@GheorgheP  OK , will you add for projects in core?

**Comment by danyj** [comment]
projects are in menu ,  need to be turned on in Screen options

**Comment by danyj** [comment]
@GheorgheP   

>  I don't think that is necessary

3 developers are asking for it please add it in core 

if portfolio has it events should have it also  or any CPT  that allows single post view.  It should be at the admin discretion to enable/disable it in Screen Options.  We cant add single event in menu so that we could display  it as theme feature. 

The action you advised to add is not allowed according to Theme check plugin and ThemeForest will not let it fly.

`REQUIRED: The theme uses the register_post_type() function, which is plugin-territory functionality.
`

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Events-Extension/commit/698873d12fb75eccf4aadbff382e76105fe20c39
