### ISSUE TITLE
DB options not being removed when option is gone. 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#266]
I used this approach #265  to add several custom options to pages. 

After playing with settings I decided to remove them for time being while I work on something else. 
But once they are saved even if you remove those settings from the page the ones in DB are still there and cannot be removed unless you manually go in DB and remove them. 

Same thing goes for theme options , I removed 3 tabs with sets of options and saved again , the removed options and their values are still in DB.

**Comment by moldcraft** [comment]
Database values are merged with old values so you cannot remove them anymore.
We did that because in the past we didn't have separate settings pages for extensions and all extensions "injected" their options via filters in theme settings options once activated (so all theme settings and extensions settings were in one page). The problem was: If you disable an extension, save theme settings, all extension settings were removed, then you enable it back and have to configure it again.

But now I think we can remove those `array_merge` from [theme settings](https://github.com/ThemeFuse/Unyson/blob/845f66826afe3fc7bb0663f359ca4e92295804ba/framework/core/components/backend.php#L910-L927), [post](https://github.com/ThemeFuse/Unyson/blob/845f66826afe3fc7bb0663f359ca4e92295804ba/framework/core/components/backend.php#L603-L612) and [term](https://github.com/ThemeFuse/Unyson/blob/845f66826afe3fc7bb0663f359ca4e92295804ba/framework/core/components/backend.php#L703-L712) save

**Comment by danyj** [comment]
I see. But now it kinda seems to be a problem as you see so it would be great if you can remove it.
