### ISSUE TITLE
Few questions about backup process

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2671]
@GheorgheP  can you please explian backup process. 

If schedule is created, how is it activated? 
By visiting the backup page or? 

Do we need to stay ( leave browser open ) on admin backup page for backup to finish? 

Asking because I have several demos I am  working on , have schedules set to daily , server on about 18h per day and none of them run until I go to the backup page. and than I cant even stop the backup  #2663

**Comment by andreiglingeanu** [comment]
The backup schedule gets activated using regular WordPress CRON capabilities ([`wp_schedule_event`](wp_schedule_event) function) -- see [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/f46f93c867c1ec2eb52f3084b2243a2b35414cfa/includes/module/schedule/class--fw-ext-backups-module-schedule.php#L158-L175). Thus, it should be launched when someone visits the website, both the frontend and backend. 

But, it also depends on your standard WordPress CRON configs. You may happen to disable the WordPress CRON at all, because many websites do so in favor some other mechanisms for background processing.

<hr>

> Do we need to stay ( leave browser open ) on admin backup page for backup to finish?

No. That is not required at all. The process is totally running on itself without the user needing to keep the browser window opened.

This will work on most multi-threaded web servers (nginx, apache). And it won't work for single threaded ones (like the server from PHP interpreter `php -S localhost:3000`, and the one from WP CLI `wp server`) -- you'll be required to keep your browser window opened to keep the process alive.

<hr>

Stoping the backup process is a whole story. Long story short, it can't be stoped easily. The `Abort` button seems to appear inconsistently, when you first try to observe its behavior. It does depend a lot on the way [`is_cancelable()`](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/d108eb88c93ab498a31e94e7db9bf8aa730ee53f/includes/module/tasks/entity/class-fw-ext-backups-task-collection.php#L120-L151) method is implemented on collections. It basically allows you to stop the process only you are at the start of execution of a sub-section. Very tricky stuff.
