### ISSUE TITLE
FW_Settings_Form not saving data

### ISSUE THREAD

**Issue by treashdox** [ThemeFuse/Unyson#2676]
I made the Theme Settings/Theme Options like on the page http://manual.unyson.io/en/latest/helpers/settings-form.html
but how can I save data from input fields to show out in my theme with 

`<?php echo fw_get_db_settings_option('copyright_text') ?>`

**Comment by danyj** [comment]
in the tutorial it says update option 

    test_fw_settings_form

so your settings should be there 

try 

`fw_get_db_settings_option('test_fw_settings_form/copyright_text');`

**Comment by treashdox** [comment]
First of all great thanks for the hint but unfortunately  
`fw_get_db_settings_option('test_fw_settings_form/copyright_text');`
still not working..will you have any idea yet?

**Comment by danyj** [comment]
do` fw_print( get_option('test_fw_settings_form', array()) );`  and see what is coming out 

I dont think you can get the custom admin page options via   `fw_get_db_settings_option`

**Comment by treashdox** [comment]
When I do `fw_print( get_option('test_fw_settings_form', array()) ); ` I have this:

```
array
(
    [opt1_1_1] => ''
    [opt1_1_2] => ''
    [opt1_1_3] => ''
    [opt1_1_4] => ''
    [opt1_1_5] => ''
    [social_media] => array()
    [copyright_text] => 'All Rights Reserved. GrandSimple@2017.'
)
```

**Comment by treashdox** [comment]
If i insert  `<?php echo fw_get_db_settings_option('test_fw_settings_form/copyright_text'); ?>` I have nothing out

If I insert `<?php echo fw_get_db_settings_option('test_fw_settings_form', 'copyright_text'); ?>` I have "copyright_text "

what am I doing wrong???

**Comment by danyj** [comment]
second example returns the default because it cant find the option

as said before you need to use `get_option  `instead if you are making custom admin options page 

look here the fw_get_db_settings_option is calling the model 

https://github.com/ThemeFuse/Unyson/blob/d9bc9acb56bd98ce4ec99e35945ae84f1fec88b3/framework/helpers/database.php#L64

which gets the 

https://github.com/ThemeFuse/Unyson/blob/d9bc9acb56bd98ce4ec99e35945ae84f1fec88b3/framework/helpers/database.php#L16

and that is using get_option here 

https://github.com/ThemeFuse/Unyson/blob/6a127e5b4d306469cd57974543f3d76bbfe441c1/framework/helpers/class-fw-wp-option.php#L24

to get_option by name   fw_theme_settings_options:theme_name


so your `test_fw_settings_form`  cant be called via `fw_get_db_settings_option` 
because it is **not** saved within `fw_theme_settings_options:theme_name`

use 

`get_option('test_fw_settings_form');`

**Comment by treashdox** [comment]
`get_option('test_fw_settings_form'); ` nothing has changed and still displays me Array..can You help me more, please? I will be very grateful that solving because this problem blocks me creating a theme :(

**Comment by danyj** [comment]
```
$theme_options = get_option('test_fw_settings_form');

$cp_text = fw_akg('copyright_text',$theme_options,'some_default');

fw_print($cp_text);
```

**Comment by treashdox** [comment]
For sure `fw_print($cp_text);` ?

**Comment by treashdox** [comment]
Ok, everything works :) Without your help it would be hard to finish it so once again thank you very much. How do I create a fully functioning Them Option to make it available on the forum or in other place.

**Comment by danyj** [comment]
I am wondering why are making custom admin page? If your theme will not have over 100-200 options than use default admin page. Right now all options are saved in custom option, than if yo need another tab or page you would go trough same thing again. If there is no need for custom admin page than stick with default.

https://github.com/ThemeFuse/Scratch-Theme/tree/master/scratch-parent/framework-customizations/theme

**Comment by treashdox** [comment]
Mayby that I like to know everything from the lining and have full control over what I create .. so I learn the most, and after all it is to keep learning new things.
