### ISSUE TITLE
Why Icon-v2 not working in Customizer?

### ISSUE THREAD

**Issue by treashdox** [ThemeFuse/Unyson#2679]
It uses icons-v2 and Customizer by using 
`<?php echo fw_get_db_customizer_option('contact_phone_icon') ?>`  
but does not display the icon. Can the problem be the UNYSON 2.6.16 version I use? When is the official update to version 2.7.0?

**Comment by Jlomaka** [comment]
The trouble is that you just brought out the icon, but if you have not yet been rendered on the page by the page builder, then the style for it, that is, the fonts did not connect.

**Comment by treashdox** [comment]
But simple icon works, only icon-v2 did not work..what is the simplest solution to this problem?

**Comment by treashdox** [comment]
Can I count on some help with the problem of displaying Icon-v2 icons in my own pan using Customizer?

**Comment by treashdox** [comment]
anyone?

**Comment by Jlomaka** [comment]
Look in order to call up the icons 2 you need to add in your style.css thos string

`@import "../../plugins/unyson/framework/static/libs/entypo/css/entypo.css";
@import "../../plugins/unyson/framework/static/libs/font-awesome/css/font-awesome.min.css";
@import "../../plugins/unyson/framework/static/libs/linecons/css/linecons.css";
@import "../../plugins/unyson/framework/static/libs/lnr/css/lnr.css";
@import "../../plugins/unyson/framework/static/libs/typcn/css/typcn.css";
@import "../../plugins/unyson/framework/static/libs/unycon/unycon.css";`

And everything will work properly, this is a kind of crutch better until the option is not thought of.

**Comment by treashdox** [comment]
I had previously included "font-awesome.css", "entypo.css" etc. But I do not know how and in what file to call fw () -> backend-> option_type ('icon-v2') -> packs_loader-> enqueue_frontend_css ();

**Comment by andreiglingeanu** [comment]
@treashdox Put that in `functions.php` and remove those nasty `@import`s from your CSS.

```php
function enqueue_icon_v2_css() {
	if (defined('FW')) {
		fw()->backend->option_type('icon-v2')->packs_loader->enqueue_frontend_css();
	}
}

add_action( 'wp_enqueue_scripts', 'enqueue_icon_v2_css' );
```
