### ISSUE TITLE
shortcode static.php run twice

### ISSUE THREAD

**Issue by kovalenko-anton** [ThemeFuse/Unyson#2715]
I create shortcode, and file static.php run twice, first time before rendering page and the second time when shortcode is executed. This is normal script behavior or I have a bug in the code?

**Comment by andreiglingeanu** [comment]
It runs twice for me too. I think this is mostly because of the [dynamic CSS](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head) filters.

That's probably not normal behavior but anyway, your code should be fine, framework is responsible for that.
