### ISSUE TITLE
LearnDash Quiz functionality disabled when Unyson / PageBuilder is enabled

### ISSUE THREAD

**Issue by anthonybrenton** [ThemeFuse/Unyson#2731]
Hi all,

I've encountered an issue where while the Page Builder extension is enabled my LearnDash quiz 'Publish' button is hidden.  In addition I have have found the LearnDash quiz settings being restricted with the error 'You don't have sufficient permissions to view this content'.

Having already spoken to the LearnDash support team, they helped me troubleshoot the issue down to the Unyson plugin by disabling all plugins and one-by-one enabling theme to see which was the instigator of the issue.  Having solved which plugin, I was happy before realising the Woffice plugin requires (non-negotiable) the Unyson plugin to be enabled.  Sad times.  The final advice from LearnDash was to to post my issue here for your insights and assistance.

I am using 'Unyson v2.6.16', 'LearnDash LMS v2.4.6' and Woffice v5.2.5

Screenshots of my issue can be [viewed here](http://imgur.com/a/DWodB).

**Comment by ViorelEremia** [comment]
Hi Anthony, 
I want to inspect this problem but I don't want to buy plugin and theme :) so can you to do for me temporary credentials from your dashboard and ftp. 
Or you can create a subdomain for testing and Ii will inspect this problem on it.
viorel@themefuse.com

**Comment by anthonybrenton** [comment]
Hi Viorel,  I have sent you an email to viorel@themefuse.com with the associated credentials you listed above.  Looking forward to seeing what you can find out.

**Comment by ViorelEremia** [comment]
I have found the problem, this is not from unyson.
After a heavy inspection code from plugin sfwd-lms i found that you don't have permissions "wpProQuiz_show" cap is added then in get global array is key "ld_fix_permissions" then this cap is added.
I did not continue to look for the problem because it happens from plugin LearnDash LMS. 
Now your advanced options is worked because i added these roles. 
Try to ask LearnDash support team about this issue. 
Inspections:
includes/quiz/ld-quiz-pro.php line 47 - register all caps user roles
includes/vendor/wp-pro-quiz/lib/controller/WpProQuiz_Controller_Quiz.php  line 369 - here is called function wp_die which kills footer but all files js are loaded in the footer that meanss is not corrrect to use this function wp_die.

**Comment by anthonybrenton** [comment]
You're amazing,  thank you for resolving this issue.  Well more-so giving me a talking point that LearnDash Support can directly target as there would be no chance of me being able to provide such detailed accurate information.

Best Regards

Anthony Brenton
Multimedia Design & Digital Optimisation
1800 092 948
www.waxit.net.au<http://www.waxit.net.au/>

Download our Wax It Loyalty App (Android <https://play.google.com/store/apps/details?id=com.sdi.waxit&hl=en> | iPhone<https://itunes.apple.com/au/app/wax-it-loyalty/id904899195?mt=8>)
or Like Us on Facebook<https://www.facebook.com/waxit.salons/>

________________________________
