### ISSUE TITLE
[QUESTION] - moving framework-customizations folder to another folder

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#276]
I am not against branding the framework or something, I just don't like to have the options files in the theme root folder and the folder name is really long.
 
Is this possible, how can I achieve this?

**Comment by danyj** [comment]
"folder name is really long"
:+1:

**Comment by moldcraft** [comment]
It was made like that when the framework v1 was placed in theme folder, and it was convenient because folders in IDE or FTP browser would stay always together because of alphabetical directory sorting

```
...
css/
framework/
framework-customizations/
images/
js/
...
```

Now we can't change this folder name because it's everywhere: docs, comments, code, links. https://github.com/ThemeFuse/Unyson/issues/208#issuecomment-72363293

> Is this possible, how can I achieve this?

At the moment, no, it's hardcoded.
I will see if I can add a filter on this folder name and if it will not affect/break something.

**Comment by thednp** [comment]
I am looking at the theme includes template here
https://github.com/ThemeFuse/Theme-Includes/blob/master/init.php

Wouldn't this work if I move the framework-customizations to this folder?
self::include_all_child_first('/includes');

**Comment by moldcraft** [comment]
No. Theme includes has no connection with the framework.

**Comment by thednp** [comment]
Damn, this framework is too cool not to be able to do this.

**Comment by thednp** [comment]
I believe the Theme_Includes class could manage the framework-customizations location property.

**Comment by moldcraft** [comment]
> I believe the Theme_Includes class could manage the framework-customizations location property.

Yes, it could (not `framework-customizations/` but `framework-customizations/theme/`), because theme-includes was actually a part of the framework, but was moved to theme-includes because the theme must work when the plugin is not installed ([changelog v2.1.0](https://wordpress.org/plugins/unyson/changelog/)).

**Comment by thednp** [comment]
Lemme know if you get anything on this.

**Comment by moldcraft** [comment]
Please [download the latest Unyson from Github](https://github.com/ThemeFuse/Unyson/archive/master.zip) and try this code in your theme `functions.php` or `inc/hooks.php`:

```php
function _filter_theme_custom_framework_customizations_dir_rel_path($rel_path) {
	return '/customizations';
}
add_filter(
	'fw_framework_customizations_dir_rel_path', 
	'_filter_theme_custom_framework_customizations_dir_rel_path'
);
```

**Comment by danyj** [comment]
Looks ok , works.

**Comment by thednp** [comment]
When having child themes it's not ok (testing with scratch), even having the filter function inside the init.php file at the top, instead of functions.php

I need to test further.

**Comment by thednp** [comment]
No no, it's totally fine, fixed. I had <code>'inc/customizations';</code> instead of <code>'/inc/customizations';</code

**Comment by danyj** [comment]
I just tested scratch and works fine for me , 
I placed the filter in hooks.php , 
moved and renamed framewrok-customizations  to  
inc/framework

copied :
functions.php
header.php
index.php
screenshot.png
style.css /// with template addition

works ok

**Comment by moldcraft** [comment]
@thednp @danyj Thank you
