### ISSUE TITLE
manifest framework max_version  does not work 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2765]
In light of latest issue 
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323129169

with updates I went ahead and tested the  manifest max_version for framework and it does not work 

on install I have   2.7.1  in manifest.php

```
$manifest['requirements'] = array(
    'wordpress' => array(
        'min_version' => '4.0'
    ),
    'framework' => array(
        'min_version' => '1.0.0',
		'max_version' => '2.7.1'
    ),...
```

and I can still see the update in backend that is forcing me to go to 2.7.4 

after the update I see the admin notice 

> Theme requirements not met: Current Framework version is 2.7.4, minimum required version is 1.0.0 and maximum required version is 2.7.1

the update should not be visible at all, that was the point of max_version , not the notice

**Comment by danyj** [comment]
Something like this should be in place for max_version checks 


```

/**
 * Disable Unyson update 
 * if new update is bigger than max version
*/

function _thz_filter_disable_unyson_update( $updates ) {

   $requirements = defined('FW') ? fw()->theme->manifest->get('requirements') : false;
   
   if($requirements && isset($updates->response)){
	   
	   $response = $updates->response;
	   
	   if(isset($response['unyson/unyson.php']) ){
	   	 
		 $new_version = $response['unyson/unyson.php']->new_version;
		 $max_version = $requirements['framework']['max_version'];
		 
		 if (version_compare($new_version, $max_version, ">")) {
			 
			unset( $updates->response['unyson/unyson.php'] );
		 }
		
	   }
   }
   
   return $updates;
}

add_filter( 'site_transient_update_plugins', '_thz_filter_disable_unyson_update' );
```

**Comment by ViorelEremia** [comment]
Here is a big problem with max/min version. It is happening then you have multi site wordpress installation.
For exemple if you have a site with max version lets say 2 and another site with max version 1.5 but latest version of that extension is 3 in this case it is a conflict between versions(in the multisite installation the files are the same used on all sites). I have some users that have that problem but until I don't see a solution. I tried to do something like that let say for extension backup - in path framework/extesnisons/backup/1.2=1.6=etc to be folders with different versions of backpup extension depending of needs of each site. I tried, but is awful, there are many problems with update, render, install, remove etc. So I think in the future we must not longer support these params like max_version min because I don't see any solution how to make them work well on multisite.

**Comment by danyj** [comment]
>  I don't see any solution how to make them work well on multisite.

not everyone has multisite , in fact  there are less multisites than normal installs , and removing a feature that is in place since 2 years was never Unyson thing. If is there we leave it for users who use it already.
