### ISSUE TITLE
Reactive should work with option ID

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2812]
@andreiglingeanu  I tested reactive option and this should work with option ID
but it requires me to find descriptor on my own 

![jqj0u3vxrncpqvomydjgsw](https://user-images.githubusercontent.com/2340172/29612836-889abdf0-8803-11e7-84d2-bdd9d8fb9337.png)

here is html 

http://prntscr.com/gc0taa

**Comment by andreiglingeanu** [comment]
Use [that](https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw-reactive-options-registry.js#L76-L82):

```javascript
fw.options.getValueForEl(
  fw.options.findOptionInSameContextFor(
    document.querySelector('#fw-backend-option-fw-edit-options-modal-post_media'),
    // put here the path to your option (even if it is nested under a multi picker)
    'PATH/TO/OPTION_ID'
  )
).then(function (result) {
  // use result
});
```

Check #2689 in order to see how to compose a `PATH` to an option.

That's all I can give right now. This API is quite stable even if it is not yet documented. And, this thing is feature complete already but I don't feel like polishing up the API _right now_, I might do that sometime in the future.

**Comment by andreiglingeanu** [comment]
And yes, and ID is not enough information for correctly identifying an option within a _single_ form, they can repeat inside multi pickers or other nested option types. That is why we introduced the idea of a context and a _path_ to an option. We are talking here about the same path as used in `fw_ack` and other helpers like it.
