### ISSUE TITLE
The problem with the visual editor of the pages

### ISSUE THREAD

**Issue by Kazzi85** [ThemeFuse/Unyson#2818]
Hello. There was a problem. I created a site based on the storevilla template using your plugin. But today  I tried to add content to the page, opened it in the editor, but the content was gone. None of the items I added. I looked at the remaining pages, they are also empty. In this case, the content itself remained. That is, the pages on the site are still filled with the content that I added, but it's not in the editor, and I need to add and edit it. How to fix this problem?

**Comment by Kazzi85** [comment]
When I add new content to a page, nothing changes. And there are no new items in the visual editor window.

**Comment by tmhalbert** [comment]
Same issue today to a site I am in the middle of developing. All pages are empty, but still show correctly live. If I attempt any change at all to any page, then I lose all content on the page. If I create a new page, and use the Unyson page builder to add ANY content, when I publish and go back into the page, everything is gone again. I've disabled ALL pugins, including Unyson in order to get the HTML that exists to show in the Wordpress page editor. When I reactivate Unyson, all of my pages show as blank again in the editor.

**Comment by danyj** [comment]
browse issues please

https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

https://github.com/ThemeFuse/Unyson/issues/2790

**Comment by tmhalbert** [comment]
Just found this ... it worked https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242 .. sorry about that. When the top of the issues list has your issue and it's only 10 min old, it's easy to not keep looking down the list before commenting!

**Comment by Kazzi85** [comment]
Everything worked for me)) Thanks ! 
Here's the problem - https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by jkherman** [comment]
This didn't work for me.  Anything else that could be causing it.  My pages where all my content was at is gone.  Thanks.

**Comment by Burger32** [comment]
I'm experiencing the same problem and none of these solutions have fixed the issue. Everything is up to date as well. If I reinstall the plugin will I have to start from scratch?

Sorry, I don't know much about this. I am just trying to update my site that someone else set up for me.

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/issues/2732
https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242
