### ISSUE TITLE
Extension for Maps - can't save settings, Over limit in 5 minutes & Map - API 100% errors

### ISSUE THREAD

**Issue by GlobalAffects** [ThemeFuse/Unyson#2868]
I am working with the latest Wordpress core + WOffice - a theme that relies upon Unyson to provide a community like (facebook sort of) theme for use with Buddypress

The MAP FUNCTION & MAP MARKERS were a key reason to purchase 

We have two issues - both related to google map api & map markers

1.  The latest version 2.7.6 of the plugin - when installed - has a "bad" link on every extensions settings page - when you attempt to change settings and save - it comes back with a 404 page error and no settings are saved

2.  The theme developer asked me to back up to version 2.6.16 - which I did - to find things get reset - however - I could then add the proper api codes and get the markers working but other things with the site are in conflict - i would prefer to be on current Unyson version - theme developer said they have no other fix at this time other than going back to 2.6.16 - any ideas here?

3.  GOOGLE MAP API - ERRORS & Marker over limit in 5 min  -- We have approx 200 markers now - with hopes of 1000-2000+ on the map - however - even with only 50 markers - we kept going over the limit so I went with a trial account with google api to help provide higher quota limit - however - we consistently go over within 30-45 minutes (it resets every day at midnight (PST))- i see a high number of errors - but google api doesn't provide why the errors occur.

Theme developer says each new memeber or person that updates and saves new LOCATION - they "rewrite the location file to show the markers - is this from Unyson code or their idea? Could be the root of my errors?  2504 requests to 2504 errors - on my Google API dashboard last night

Theme developer says they have run out of answers - any help or guidance would be welcome!

Thank you , in advance

Annie

**Comment by ViorelEremia** [comment]
1. Next update will solve this issue a prerelase is already done.
2. You can download next version to test https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/359
3. Something I understand but not all without seeing your site and i don't have this theme. From documentation google i see [25000 loads per 24 hours](https://google-developers.appspot.com/maps/documentation/javascript/usage), why did you specify about markers?
a map with multiple markers create one request, google get one request by one loaded map. 
About the new member you mean that every user who registers or updates his location is "rewrite the location file to show the markers" what file we dont have any file which can be rewritten. In short to find out where the problem is, I'll need your credentials from your dashboard : viorel [ at ] themefuse [ dot ] com
