### ISSUE TITLE
Extra P tags in unyson

### ISSUE THREAD

**Issue by Alecto** [ThemeFuse/Unyson#2878]
on unyson pages, when inserting shortcodes, the DIV's are wrapped in tags P
https://image.prntscr.com/image/UsSumrWWQv_vTevfg4s5eg.png

I tried this solution:
remove_filter( 'the_content', 'wpautop' );
add_filter(    'the_content', 'wpautop' , 12);

it helps, but sometimes it works incorrectly, removing only opening <P> tags and leaving closing </P>, because of what it can not be used.

help fix the bug that the validator curses.

**Comment by thednp** [comment]
I'm experiencing a similar issue, I will investigate further and provide proper steps to reproduce, possible some solutions as well.

**Comment by ViorelEremia** [comment]
@Alecto I do not know what you did but in my end everything is fine with shortcodes in tinymce. To remove tags <p> I do not recommend because it cna change the behavior completely such as embed media like youtube, vimeo soundcloud shortly many many bugs which you can not predict from the beginning. This is default wordpress behavior. @Alecto I think you tried to remove tags from text regime editor this can cause.
This is also recommended by Envato market see here: https://help.market.envato.com/hc/en-us/articles/202822450-WordPress-Theme-Submission-Requirements

8. Modification of filters in wptexturize() is not allowed.
9. Modification of filters in wpautop is not allowed.

**Comment by Alecto** [comment]
```
I tried this solution:
remove_filter( 'the_content', 'wpautop' );
add_filter( 'the_content', 'wpautop' , 12);
```

this solution doesnt work, it crash site sometimes.

> @Alecto I do not know what you did but in my end everything is fine with shortcodes in tinymce. To remove tags

but the problem exists and not only for me.

It is a great pity that you close the error messages without providing a solution.
at the moment, the problem was decided to create a гтныщт unicode shortcode for inserting other shortcodes.

**Comment by ViorelEremia** [comment]
Try to add a new page without adding hooks to editor if you have the same issue with validator then it may be somewhere a unclosed/closed lost tag but to touch default behavior of tinymce we will not do that. I closed because this can mislead other users to do that.

**Comment by Alecto** [comment]
there are no unclosed/closed  and lost tags. if I insert a shortcode (I'm working with Shortcodes Ultimate plugin) it wrapped into an extra P tag

**Comment by ViorelEremia** [comment]
Ok, then the problem is with plugin: https://wordpress.org/plugins/shortcodes-ultimate/

**Comment by thednp** [comment]
@ViorelEremia I have a similar issue with all editors using `'shortcodes' => true,`, most shortcodes get `autop`ed right away, I decided to go `'shortcodes' => false,` because it interferes with my additional button shortcode options.

**Comment by ArturoGallegos** [comment]
this topic should be into wordpress forum, unyson not insert the p tag in the content, the problem is with the wordpress editor and have some years of this.
