### ISSUE TITLE
NEED HELP. Adding events to calendar from customize menu

### ISSUE THREAD

**Issue by gigit95** [ThemeFuse/Unyson#2887]
Is it possible to add events from customize menu to calendar?
If it's possible, how can I do that ? Please explain !
I'm trying to develop a site for my exam and I have troubles.
I've made some "customizations" in customizer.php and options.php  with built-in options, but can't find information about calendar in customize menu.
Would be great to have something like this ...

![fythdrghd](https://user-images.githubusercontent.com/11440530/30453615-b65ea81c-9999-11e7-86d8-2cf533684d17.JPG)

which sends the info to calendar.

**Comment by gigit95** [comment]
Common guys ! No body can help me ???

**Comment by ViorelEremia** [comment]
From your image, I see what you added addable option and you want to extract in shortcode calendar? You can do that but you need to work hard what I do not recommend for you if you insist I can only give you some indications how to do. Try to understand how the code works from shortcode calendar and maybe you need to overwrite it, you need to replace population whit your population extracted from customizer, all these things are described in dev manual unyson(how to overwrite shortcodes, get from DB value customizer etc). My opinion about what you trying to do is very hard for you and you will encounter many problems and I do not think many will try to help you, So before to start building this you have to think very well - you will have the power to go all the way :) because I very well understand what you trying to do. As I see you try to do a mini live builder you try to send values from customizer to builder this is very complicated you need to override many things. I hope I understand you well.

**Comment by gigit95** [comment]
Thank you for your answer. I've searched a lot about the overriding the shortcodes etc. , but there is not much information about calendar here. Ok, so I'll try it a bit later. We learn much more by doing hard and complicated work ;) . Thanks for your answer, again.
