### ISSUE TITLE
Can't change section background color

### ISSUE THREAD

**Issue by CardotRomain** [ThemeFuse/Unyson#2895]
Hi, I can't change the background color for my section.

After I pick a color with the colorpicker and save I can see on the HTML source code of my page the new style ="..." but with a double " (see on my snapshot)

Any help ?

![image](https://user-images.githubusercontent.com/10893816/30520979-e40d53d8-9bb7-11e7-99de-b2bc17eedb88.png)

**Comment by ViorelEremia** [comment]
From our code is not possible, but some devs build haks to hook attribute_escape from esc_attr to easier pass control on themforest, why is this happened try to ask your developer or you need to find file unyson/framework/extensions/shortcodes/shortcodes/section/views/view.php maybe this file is rewritten see here: http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content try and inspect yourself why this happens because I cant reproduce this
