### ISSUE TITLE
Install extension using github ? 

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#2900]
Hello @moldcraft 

We have created the custom unyson extension and we want to install this custom made extension via github repository just like you did for your plugins.

Any help would be much appreciated...

**Comment by etwordpress01** [comment]
Hi, We also created a Unyson Extension for our theme, And we want to install this extension directly from github but didn't found any solution. 

We created this extension for our [Article Extension](https://github.com/etwordpress01/articles)

Is it possible to install via github?

There should be an option to install extensions from github same like Unyson Builtin extensions.

If any one can help?
Thanks

**Comment by wpthemes786** [comment]
@moldcraft  Any help ?

**Comment by etwordpress01** [comment]
Hi, Yes i need a little help if  you can help me ? We have develop a theme for our customers and also develop extension in Unyson. If we put it in theme folder then it shows at back-end. We want to give only compatibility and every user should download it from github and it should installed automatically in Unyson plugin. Same liek Unyson extension does.  [Link](http://prntscr.com/gnci91)

[Here is extension we develop : ](https://github.com/etwordpress01/articles)

Is it possible?

Thanks

**Comment by ViorelEremia** [comment]
Hi guys I tried to do this with @etwordpress01 Extension  [Article Extension](https://github.com/etwordpress01/articles) so I may find problems that you may encounter, first you need to do is to register your extension, therefor you need to create a file in: framework-customizations/theme/available-extensions.php and here do:
`<?php defined( 'FW' ) or die();

$extension = new FW_Available_Extension();
$extension->set_title( __( 'My extension', 'fw' ) );
$extension->set_name( __( 'My extension', 'fw' ) );
$extension->set_description(  __( "Bla bla bla.", 'fw' ) );
$extension->set_thumbnail( fw_get_framework_directory_uri( '/core/components/extensions/manager/static/img/thumbnails' ) . '/page-builder.jpg' );
$extension->set_download_source( 'github', array( 'user_repo' => 'etwordpress01/articles' ) );

$register->register( $extension );
`
all functions: Unyson\framework\core\components\extensions\manager\includes\available-ext\class-fw-available-extension.php
class github here you can check what errors github returns : Unyson\framework\core\components\extensions\manager\includes\download-source\types\class-fw-download-source-github.php
That will make to show in avaible extensions your extension now for this extension created by @etwordpress01 not working because you do not commit any tag, so if you want to download from github you need to commit the first version (releases).

**Comment by etwordpress01** [comment]
Hi, Thank you @ViorelEremia 

I just add first commit and everything is working fine. I downloaded this extension via github. 

Thanks for your help :+1:

**Comment by notrealdev** [comment]
Hi @ViorelEremia this option support Bitbucket?

**Comment by etwordpress01** [comment]
Hi, Yes these options support. We have article extension on github and our customers install this extension directly from git repository. https://github.com/etwordpress01/articles

let me know if i can help?
Thanks

**Comment by notrealdev** [comment]
Oh, instead of using Github can I use Bitbucket?
```php
$extension = new FW_Available_Extension();
$extension->set_title( __( 'My extension', 'fw' ) );
$extension->set_name( __( 'My extension', 'fw' ) );
$extension->set_description( __( "Bla bla bla.", 'fw' ) );
$extension->set_thumbnail( 'fa fa-user' );
$extension->set_download_source(
    'github', // if bitbucket ??
    array(
        'user_repo' => 'etwordpress01/articles'
    )
);

$register->register( $extension );

```

**Comment by etwordpress01** [comment]
Hi, bitbucket needs authentication to get repository, i think it can't be possible. I am not sure, might be possible, @ViorelEremia can help regarding this point. He helped me to get it work.

Thanks

**Comment by notrealdev** [comment]
@ViorelEremia Can you help me with Bitbucket? Our repo is in Bitbucket
