### ISSUE TITLE
Unyson hide update button

### ISSUE THREAD

**Issue by itlike** [ThemeFuse/Unyson#2919]
Helo. I have the same problem like it:
https://github.com/ThemeFuse/Unyson/issues/2537

How can I solve it?

**Comment by ViorelEremia** [comment]
do you have the latest versions unyson & extensions?

**Comment by itlike** [comment]
Yes. I have the latest version unyson & extensions also. Unyson 2.7.7 WP 4.8.2

**Comment by ViorelEremia** [comment]
Send me some credentials and a link to this page: viorel [ a ] themefuse [ dot ] com

**Comment by itlike** [comment]
OK. I send from biuro [a] itlike [dot] pl

**Comment by ViorelEremia** [comment]
Ok i checked and the issue is not from Unyson is a server issue, I do not have access to the server or cpanel but i think is a security issue and folder don't have correct permissions  /wp-includes/js/tinymce/wp-tinymce.php. You can see main issue that causes all errors, contact your hosting support and show them this image:
![iisssss](https://user-images.githubusercontent.com/28967378/30920388-74f6e6ce-a3ac-11e7-8375-8a367a0c2010.png)
