### ISSUE TITLE
Unyson page builder not working

### ISSUE THREAD

**Issue by chill1234** [ThemeFuse/Unyson#2926]
Page content no longer visible.  Unable to save any changes. Builder not working. I'm using the TOPSEO theme with unyson page builder.

**Comment by chill1234** [comment]
Seems to be same issue as #2764. Can't see any content from my pages within the editor but pages still are still working fine on front-end.  I can't edit anything because I can't see any of the content ie: page builder content.

**Comment by jmc-nabb** [comment]
I have the same issue, started a few hours ago. Can't create a new page or edit. 
![aaa changed file](https://user-images.githubusercontent.com/9558017/30951551-f9b56736-a466-11e7-8f41-03ea4cf26ddd.JPG)
the files was replaced. Not sure where the error came from. Didn't fix it, rescanned and all OK.
I can still see the pages, my other two sites are fine. All versions the latest. When I go to edit there is nothing there, I create a new page save it and nothing there.

**Comment by jmc-nabb** [comment]
I am using Unyson with Jevelin from Shufflehound.

**Comment by ViorelEremia** [comment]
do you have the latest versions of extensions?
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by jmc-nabb** [comment]
yes everything is up to date

**Comment by ViorelEremia** [comment]
@jmc-nabb try these steps https://wordpress.org/support/topic/important-support-is-on-github-not-here/

**Comment by jmc-nabb** [comment]
Please follow the next steps before you open a support ticket, so we can help you solve the issue faster:

Make sure you are using the most updated versions of Unyson plugin & Extension, WordPress & your theme. - done
Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin. - there are no new plugins or versions, my other sites are using the same plugins
If you have a caching plugin, make sure you deactivate it, or even better – purge the cache. - done that a long time ago
Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme). - it's a live site ... really?
On your WordPress root folder, edit the wp-config.php and set the value of WP-DEBUG to true or you can install plugin Debug Bar or Query Monitor - seems to mess things up, will investigate tomorrow
Some of issues might be caused by server configurations that do not meet the minimum plugin or theme requirements like Maximum File Upload Size, Maximum Input Variables Limit, Maximum Execution Time, – please look through this articles to find out how you can configure the minimum requirements. - done
If you have followed all these steps and you’re still encountering difficulties, please open a ticket by following these steps:

Describe the issue and what led to it. Please be as accurate and detailed as possible.
If you suspect the issue was caused by the theme/plugin and your theme/plugin is premium, please contact theme author, if theme/plugin is free please attach the name + URL of the theme/plugin. - there is nothing that lead to it other than editing posts i.e SEO

**Comment by ViorelEremia** [comment]
@jmc-nabb console errors?

**Comment by jmc-nabb** [comment]
It's update related my other site was fine, I updated it and now I have the same problem.

**Comment by chill1234** [comment]
When I switch over to the Twenty 15 wordpress theme, the builder appears when editing a page....it's something with the TOPSEO theme.

**Comment by jmc-nabb** [comment]
I have disabled all the plugins expect Unyson, no difference

**Comment by jmc-nabb** [comment]
SWhen I change twenty seventeen no difference

**Comment by jmc-nabb** [comment]
I have done a restore of the other site and the editor is showing evenrything. I have updated all the plugins except Unyson and it's still working. It's the Unyson update. 


UnysonUnyson \| Deactivate \| Edit | A free drag & drop  framework that comes with a bunch of built in extensions that will help  you develop premium themes fast & easy. 						Version 2.6.16 \| By ThemeFuse \| View details
-- | --
There is a new version of Unyson available. View version 2.7.7 details or update now.

How can I go back on the site that is not working?

**Comment by jmc-nabb** [comment]
re change debuging to true this is the only message:
Notice: Constant WP_POST_REVISIONS already defined in /home/xaraskinau/public_html/wp-config.php on line 104

Notice: Use of undefined constant http - assumed 'http' in /home/xaraskinau/public_html/wp-content/plugins/https-switcher/https-switcher.php on line 36

Notice: Use of undefined constant https - assumed 'https' in /home/xaraskinau/public_html/wp-content/plugins/https-switcher/https-switcher.php on line 37

Notice: Use of undefined constant http - assumed 'http' in /home/xaraskinau/public_html/wp-content/plugins/https-switcher/https-switcher.php on line 36

Notice: Use of undefined constant https - assumed 'https' in /home/xaraskinau/public_html/wp-content/plugins/https-switcher/https-switcher.php on line 37

Notice: Use of undefined constant http - assumed 'http' in /home/xaraskinau/public_html/wp-content/plugins/https-switcher/https-switcher.php on line 36

Notice: Use of undefined constant https - assumed 'https' in /home/xaraskinau/public_html/wp-content/plugins/https-switcher/https-switcher.php on line 37

**Comment by jmc-nabb** [comment]
what is interesting is I have two sites that say everything is up to date yet they have different versions?

![image](https://user-images.githubusercontent.com/9558017/30998882-de6f181a-a514-11e7-8c65-3985694cc085.png)

**Comment by ViorelEremia** [comment]
@jmc-nabb send me some temporary credentials ftp and dashboard: viorel [ at ] themefuse [ dot ] com

**Comment by jmc-nabb** [comment]
https://xaraskinclinic.com.au/wp-admin/

login bbb      hn9I&%L^&3#3WJJzDD4*@C(J

 

the ftp account is the asme

 

 

Kind Regards

John Mc Nabb

 

-- 

Copyright John Mcnabb 2015 © All rights are reserved.

**Comment by jmc-nabb** [comment]
There is a compressed update of Unyson in the directory already uploaded and a backup of what is running

 

 

 

 

Kind Regards

John Mc Nabb

 

-- 

Copyright John Mcnabb 2015 © All rights are reserved.

**Comment by ViorelEremia** [comment]
@jmc-nabb credentials dont work

**Comment by jmc-nabb** [comment]
Changed password   B$mC)p#$p@UH9LuQrP*FK6zq    bbb

 

 

I have tried this one

 

Kind Regards

John Mc Nabb

 

-- 

Copyright John Mcnabb 2015 © All rights are reserved.

**Comment by jmc-nabb** [comment]
ftp user name bbb@xaraskinclinic.com.au

 

 

 

 

Kind Regards

John Mc Nabb

 

-- 

Copyright John Mcnabb 2015 © All rights are reserved.

**Comment by ViorelEremia** [comment]
@jmc-nabb check if everything is fine: https://xaraskinclinic.com.au
you use plugin Easy Updates Manager that does not allow to update plugins be careful how you use the plugins because I noticed you're using too many security plugins they can conflict with each other plus you do not update them because is plugin Easy Updates Manager 
If everything is fine please remove the credentials you showed here.

**Comment by anandspybs** [comment]
I had the same problem, but I have fixed it. You need to do:
1. Deactivate the plugin (Unyson)
2. Delete the plugin
3. Delete the cache
4. Install again. 

I hope this will work for you.
