### ISSUE TITLE
How can I see if FW_Cache is caching?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3009]
I have this big function that is processing all css and would like to cache it , 

testing like , 

```
	$cache_key = 'test_cache';
	try {
		$value = FW_Cache::get($cache_key);
		fw_print($value);
		
	
	} catch (FW_Cache_Not_Found_Exception $e) {
		
		fw_print('no');
		FW_Cache::set($cache_key, 'ok I am in');
	}
```

but always get no back , am I using this wrong ?

**Comment by ViorelEremia** [comment]
I suppose that your function is executed only once? In this case is nonsense to save value in the cache.
This cache is created only for one instance php, so if you have something what is called several times in one instance php then you can set this value in the cache. This cache is not working how physical cache works but is somethnig ..... i don't now how can I call it maybe memory cache or virtual cache. The meaning is this: each time you call a new instance php this cache is again created, and when php is finished chache is removed.
The cache is set as a static variable see class: framework/helpers/class-fw-cache.php variabile static
`/**
	 * The actual cache
	 * @var array
	 */
	protected static $cache = array();`
here are all vars cache, so if you set a big value with css in a static var php then this var is kept until the end of php execution, consuming memory that you will never use(because you need it once).
Explanation for your code:
`$cache_key = 'test_cache';
		try {

		    // here we try to extract value from cache if value not exists in static key $cache when is triggered an exception that is catched in the block catch.
			$value = FW_Cache::get( $cache_key );
		} catch ( FW_Cache_Not_Found_Exception $e ) {
            // Extract your value here, some big execution php
            // When you call this code for the second time this code should no longer be executed:
            $value = your_function_with_css();
			FW_Cache::set( $cache_key, $value );
		}
        
		$value = 'your css here';`
