### ISSUE TITLE
After Update to Wordpress 4.9.1 I received a  Synchronous XMLHttpRequest error

### ISSUE THREAD

**Issue by ArtStarts** [ThemeFuse/Unyson#3078]
I use the Unyson builder as part of my ThemeFuse package. I do have knowledge of back end web dev, however not at an extremely high level. I stick more to the front end side of dev staging. 

Following an update to wordpress 4.9.1, select actionable items (a few buttons & videos) lost their interactive features on the web page; https://artstartsto.com/cartography-17/ . I contacted my host and they referred me to a Synchronous XMLHttpRequest Deprecation that was located on the page I am concerned about. Referring me to here, I am following up to see if it is a communication error on behalf of the Unyson plugin. 

I took the typical front end trouble-shooting steps - creating backups throughout - updating my theme, then plugins and than finally purging my caches and it seems that the problem still persists. 

If someone could point me in the direction of how to solve this it would be appreciated, I am skilled enough that if a code needs to be inserted into my FTP, I can implement this. 

![screen shot 2017-12-13 at 1 03 41 pm](https://user-images.githubusercontent.com/34519133/33954375-182d584c-e006-11e7-92b7-db19770d1009.png)

**Comment by ViorelEremia** [comment]
Warning is from shortcode calendar, unyson uses this script: https://github.com/Serhioromano/bootstrap-calendar/ this is happening because jQuery has deprecated synchronous XMLHTTPRequest param that i think can be removed in future:
```
$.ajax({
	url: self._templatePath(name),
	dataType: 'html',
	type: 'GET',
	async: false,   // ----------------------- Deprecated 
	cache: this.options.tmpl_cache
}).done(function(html) {
	self.options.templates[name] = _.template(html);
});
```
Also they know that: https://github.com/Serhioromano/bootstrap-calendar/issues/723
This warning deprecated is not so serious to destroy your site(buttons, video), so I think that your lost interactive features is not because of this warning.

**Comment by ViorelEremia** [comment]
About your losses contact your theme developer.
