### ISSUE TITLE
Problems with events

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson#310]
Hi,

I have some problems with "events" and I would like help.
That's a list of my problems:

- How to have a list of events in a "page"? I would like something like that: http://image.noelshack.com/fichiers/2015/10/1425521697-event.png (sorry, picture in french)

- Why my calendar is not working? I created a test event with a category called "event", but my calendar is not showing this event. My calendar is linked to the category "event" too.

- Is it possible to have a link like that: .com/atelier-no-1/
instead of that: .com/fw-event-slug/atelier-no-1/

- How to change calendar language?

- Can we select differents colors for differents events (on calendar)?

I know it's a lot, but thank you for your help :)

**Comment by sergiubagrin** [comment]
Hi @Nic787 

I'm ok with french :) 

> How to have a list of events in a "page"? I would like something like that: http://image.noelshack.com/fichiers/2015/10/1425521697-event.png (sorry, picture in french)

https://wordpress.org/support/topic/list-posts-from-custom-post-types-anywhere

> Why my calendar is not working? I created a test event with a category called "event", but my calendar is not showing this event. My calendar is linked to the category "event" too.

1. http://screencast.com/t/s27Ok8uAj
2. http://screencast.com/t/qhV7a6SKto
3. http://screencast.com/t/5vonXfLoLcL
4. http://screencast.com/t/VMO1neNXd3

> Is it possible to have a link like that: .com/atelier-no-1/ instead of that: .com/fw-event-slug/atelier-no-1/

I added a new issue with this: https://github.com/ThemeFuse/Unyson-Events-Extension/issues/3

> How to change calendar language?

I will investigate this in a separate issue: https://github.com/ThemeFuse/Unyson-Events-Extension/issues/4

> Can we select differents colors for differents events (on calendar)?

I will investigate this in a separate issue: https://github.com/ThemeFuse/Unyson-Events-Extension/issues/5

**Comment by Nic787** [comment]
Thank you.

For my calendar, I tried to put the "calendar" in my default editor, and I have something like this: http://image.noelshack.com/fichiers/2015/10/1425578748-bug.png

Also, can you explain me more in details what the first link is about. I don't understand everything in php, so where do I need to add this and how it will work?

Thank you

**Comment by sergiubagrin** [comment]
> Also, can you explain me more in details what the first link is about. I don't understand everything in php, so where do I need to add this and how it will work?

Each time an events is added it is needed to add Date + Time + Location for your event after Event description like in this screen: http://screencast.com/t/VneGjFgn

Event will be displayed in calendar only if you add Date+Time intervals

**Comment by Nic787** [comment]
Hum... I added a date, but it doesn't work.

See those pictures :
http://image.noelshack.com/fichiers/2015/10/1425658348-event1.png
http://image.noelshack.com/fichiers/2015/10/1425658348-event2.png
http://image.noelshack.com/fichiers/2015/10/1425658348-event3.png

Also, for my events list idea, do you think it could be possible for the devs t make a new option for events (where we can add date) to show a small description and decide to put a list on top of the calendar showing only the next 3 events. Maybe a list like that : http://www.paolini.net/events/ but you should be to click on the title to go on the full page.

**Comment by Nic787** [comment]
So for my problem, nothing work. I tried reinstalling the "event" plugin, but I have the same problem. I don't understand.

Do you want to login in my admin panel to see it by yourself?

**Comment by Nic787** [comment]
Hi,

I don't know if I found the problem, but can you look into that?

Based on that : http://manual.unyson.io/en/latest/extension/events/index.html
I found in wp-content/extensions/plugins/unyson/frameworks/extensions/events/ (not in wp-theme/themename/...) some files and as an example, I opened "hook.php" and I didn't find .fw_theme_ext_events_after_content in it.

Do I need to add it myself?
Maybe it could solve my problem... What do you think?

**Comment by Nic787** [comment]
Nobody want to help me?

**Comment by GheorgheP** [comment]
Hi @Nic787,

There is a lot discussed here, also there was solved some of problems you related ( Look above )

Could you tell what other problems with events remained? Also provide your log-in details on dev-team@unyson.io and I will take a look.

**Comment by designhouse-git** [comment]
![screen shot 2016-04-21 at 11 11 41 am](https://cloud.githubusercontent.com/assets/18598433/14714495/25f56d52-07b3-11e6-87e6-3e5abb4f29cd.png)

I have installed and activated the Unyson Events plugin. 
I have created a new EVENT.
However, when I Add New Page, I do not have the option of creating a CALENDAR as per your screen shot: http://screencast.com/t/qhV7a6SKto
Have I missed a step in the set up process?

Many thanks,

Betty

**Comment by codesman** [comment]
One difference is that you are in the text editor and not the visual editor.  What happens if you click on the  "Visual Page Builder" button?  I suspect there should be an option to add the calendar shortcode.  Or, what happens if you just type in `[calendar]` and preview the page?

**Comment by designhouse-git** [comment]
Hmm. Not sure.

http://shauna.he166.vps.webenabled.net/calendar-test/

Do you mind loging in and giving it a try?

See code in Visual Page Builder > Text Block.

un: 
admin

pd: 
Q8XioCJ6T0a4PGw0@cvMJYFl


tx
b

Betty Biesenthal | 613-732-9273

**Comment by codesman** [comment]
Hi Betty,

I did log in and poke around a bit. Unfortunately, I don't have anything good to report.  It appears that there are multiple issues. There was a notification that there was an update for Unyson extensions so I updated them.

The first thing that came up, is that it appears that the event extension is not compatible with your theme.  I am assuming the fact that most of the other extensions have a compatibility statement makes this true.
![screen shot 2016-04-21 at 12 33 57 pm](https://cloud.githubusercontent.com/assets/1653589/14721845/83c01036-07bd-11e6-8f52-696be665473d.png)

There are 2 things I found that confirm the hypothesis that the theme is not compatible with the Events extension.

First, there is no Calendar shortcode/content type that appears in any of the tabs in the page builder.
![screen shot 2016-04-21 at 12 30 10 pm](https://cloud.githubusercontent.com/assets/1653589/14721773/1ce29e38-07bd-11e6-9d7e-b23868cc9fb2.png)

Second, as you can see, I added the map element and set it to be populated with event items:
![screen shot 2016-04-21 at 12 30 27 pm](https://cloud.githubusercontent.com/assets/1653589/14721887/c9f044fe-07bd-11e6-955a-f09d2c1c1854.png)

However, when you go to that page, there is no map.  Just a blank page and and 2 errors in the javascript console:
![screen shot 2016-04-21 at 12 39 04 pm](https://cloud.githubusercontent.com/assets/1653589/14721972/1d9447ae-07be-11e6-8f86-97107adc0610.png)

So it looks like you are going to have to figure out how to make your theme compatible or find another solution.  I certainly could be wrong and this could be a simple config issue, but it does not appear to be that way.

Also, I noticed you are running WordPress 4.5 and there have been changes in that version that have to do with jQuery that breaks things that use jQuery.  For instance, I have a site that is using a theme with the VisualComposer plugin and I can't update that site to 4.5 because the version of VisualComposer I am using is not compatible with the changes in WP 4.5.  Unfortunately, I have needed to make customizations to the theme that makes it impossible for me(without much pain) to update to the newer version of the theme(that fixes the issue).  I have been considering building a new theme that doesn't use VisualComposer for a while.  Now the decision has been made for me...

Anyway, I digress...  I feel your pain.  Doesn't look like there is an easy fix for this.

The only other thing that I can add is that I have used the The Events Calendar plugin by Tribe on a client's site and it did the job nicely.  You might want to disable the Unyson events extension and see it it will work with your current theme.

Tom

**Comment by designhouse-git** [comment]
Thanks for this update.

See notes inline...


Betty Biesenthal | 613-732-9273





> On Apr 21, 2016, at 4:01 PM, Tom Holland <notifications@github.com> wrote:
> 
> Hi Betty,
> 
> I did log in and poke around a bit. Unfortunately, I don't have anything good to report. It appears that there are multiple issues. There was a notification that there was an update for Unyson extensions so I updated them.
> 
> The first thing that came up, is that it appears that the event extension is not compatible with your theme. I am assuming the fact that most of the other extensions have a compatibility statement makes this true.
>  <https://cloud.githubusercontent.com/assets/1653589/14721845/83c01036-07bd-11e6-8f52-696be665473d.png>
> There are 2 things I found that confirm the hypothesis that the theme is not compatible with the Events extension.
> 
> First, there is no Calendar shortcode/content type that appears in any of the tabs in the page builder.
>  <https://cloud.githubusercontent.com/assets/1653589/14721773/1ce29e38-07bd-11e6-9d7e-b23868cc9fb2.png>
> Second, as you can see, I added the map element and set it to be populated with event items:
>  <https://cloud.githubusercontent.com/assets/1653589/14721887/c9f044fe-07bd-11e6-955a-f09d2c1c1854.png>
> However, when you go to that page, there is no map. Just a blank page and and 2 errors in the javascript console:
>  <https://cloud.githubusercontent.com/assets/1653589/14721972/1d9447ae-07be-11e6-8f86-97107adc0610.png>
> 
Interesting. This probably explains why the map on the Contact page doesn’t work anymore.

> So it looks like you are going to have to figure out how to make your theme compatible or find another solution. I certainly could be wrong and this could be a simple config issue, but it does not appear to be that way.
> 
> 
> Also, I noticed you are running WordPress 4.5 and there have been changes in that version that have to do with jQuery that breaks things that use jQuery. For instance, I have a site that is using a theme with the VisualComposer plugin and I can't update that site to 4.5 because the version of VisualComposer I am using is not compatible with the changes in WP 4.5. Unfortunately, I have needed to make customizations to the theme that makes it impossible for me(without much pain) to update to the newer version of the theme(that fixes the issue). I have been considering building a new theme that doesn't use VisualComposer for a while. Now the decision has been made for me...
> 
> 
Can I back-save to a previous version of WP, or should I wait for them to make the fix?
> Anyway, I digress... I feel your pain. Doesn't look like there is an easy fix for this.
> 
> The only other thing that I can add is that I have used the The Events Calendar plugin by Tribe on a client's site and it did the job nicely. You might want to disable the Unyson events extension and see it it will work with your current theme.
> 
> 
Will do. Many thanks for your advice. I will keep you posted.

bb

**Comment by designhouse-git** [comment]
Tom,

How does one know what the updates to and compatability with new WP version are so that one can make a qualified decision ahead of time?

If one updates to new WP and then realizes the error, can one revert to an earlier version of WP?

tx
b


Betty Biesenthal | 613-732-9273
