### ISSUE TITLE
[community discussion] What would you use to sell your digital products?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3112]
This is just a small dilemma I have and would love to hear from you.  

Since about 12 years I used amember to sell Joomla digital downloads but I can honestly say that it is one of the crappiest shops with huge learning curve. Especially the v4 and their "themeing"  is simply horrible. 

So now I am getting ready to publish the theme and would love to hear what would you use to sell it. 

I will not got on TF right away but rather give it a shoot on its own since we already have over 110K  users that we can push the product to. 

@themefuse I see that themefuse is using amember as download member area and downloads but I also see an avant checkout. So are you moving away from amember also or? 

I looked over at EDD and WOO memberships and just kinda have a bad feeling about each , since they are both streamline products and hacks and attacks are simply inevitable. 

The plan is to have a simple checkout and member download area. All sales pages and buttons are done independently from any shops. 

Any input is appreciated.

**Comment by alexluncashu** [comment]
aMember is not the best, but we keep there all affiliates and sales from the beginning. We changed over years different payment processors, such as paypal, fastspring, gumroad and now avangate. We can't migrate affiliates and users every time when we have to change payment processor, so that's why we still keep amember in backend. 

When user press Buy button it redirects to avangate, and avangate sends IPN info back to amember (where we keep our affiliate tracking system)

So, we use amember not because it's the best. But if you start from scratch you may consider other platform, you can use avangate without amember if you want.

Cheers

**Comment by danyj** [comment]
@alexluncashu thnx for the reply ,  I see the appeal of amember ,  tickets, payments, member area downloads, but I am simply mad at them for leaving us out with 100k customers from v3 to v4

**Comment by danyj** [comment]
@alexluncashu 

>  But if you start from scratch you may consider other platform


what would you use at this very moment to have same setup as you do now ?

this is what I need ; 

checkout
member area
download area 
ticket system

**Comment by danyj** [comment]
on Joomla I had to build ticket system on my own  and combine , 

joomla 
aMember
vBulletin ( awful!!!!! )
custom tickets 
custom download

**Comment by alexluncashu** [comment]
Maybe I will try https://easydigitaldownloads.com/, but can't say much about it
