### ISSUE TITLE
copying a post to a new site

### ISSUE THREAD

**Issue by obertscloud** [ThemeFuse/Unyson#3139]
i want to copy a post on another site to see if it works, but not sure how do do that i tried the code in the custom field but it does not save

**Comment by ViorelEremia** [comment]
What do you mean "a post"?
A post created with page builder?

**Comment by obertscloud** [comment]
Yes created with page builder

**Comment by ViorelEremia** [comment]
You can do like that(get the data for page you want to import)
The code below is not tested please test it before going to production:
```
function test_wp_head( $upload_mimes ) {
	print_r( fw_get_db_post_option( get_the_ID(), 'page-builder' ) )
}
add_filter( 'wp_head', 'test_wp_head' );

```
Copy the whole array to new array do that to new site
```
$import_array = array(
	'json' => 'copy json from the page you want to import or you can get it from a file json',
	'builder' => 1
);
update_post_meta( get_the_ID(), 'page-builder', $import_array );
```

**Comment by obertscloud** [comment]
ok thanks, but i don't understand a thing you just said to do?  what is this php?

**Comment by ViorelEremia** [comment]
you are not a developer?
if not there's no way to do that with unyson you need to look for a plugin which works with the export of pages

**Comment by obertscloud** [comment]
No the plugin developer for Wordpress said we must make all support issues here. I am a developer just not in php, I work in other technologies and webdesign.

**Comment by ViorelEremia** [comment]
Ok, and who is ```the plugin developer for Wordpress said```
If you don't know how php is working you can go to phpmyadmin old site and find table ```yourPrefix_postmeta```, here find the field ```page-builder``` with your post_id what you want to export and copy everything from ```meta_value``  further you go to new site and put in the same way.....

**Comment by obertscloud** [comment]
Unyson is , why did you close this? 

https://wordpress.org/support/plugin/unyson
IMPORTANT!!! SUPPORT IS ON GitHub NOT HERE !!!

**Comment by steve-themefuse** [comment]
Hi

Apologies, but you are confusing things a bit, first of all since the Unyson is an open source plugin support is not provided for it, the Github repository is only for maintenance and reporting issues.

Second, the Unyson plugin doesn't have the option to export single pages or posts, and the Unyson administrator was polite enough to even give you a solution, something that he was not supposed to because of the reasons mentioned above. And even so, you did not understand it because you're not a developer. Sorry, but we can't help anymore and  this issue can be closed because it is not related to a technical issue of the plugin.
