### ISSUE TITLE
Litespeed notice

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3168]
We should be able to dismiss this notice
http://prntscr.com/i8wblu

and it should be visible in backup utility only ,  
if I dont use backups than I dont need it.

**Comment by ViorelEremia** [comment]
We don't think to hide it is a good idea. For exemple if user hide it and after two day he wants to create backup I'm sure he will come for support here on github or to theme support, the theme support also will send user here on github. so we need again to ask for ftp credentials etc to check what is wrong because these litespeed errors may appear in different ways.

**Comment by danyj** [comment]
display in backup only is ok
