### ISSUE TITLE
Stripping HTML out of Paragraph element

### ISSUE THREAD

**Issue by reverbunit** [ThemeFuse/Unyson#3170]
1. I placed a PARAGRAPH element into my page. 
2. I add code to the code to the TEXT editor. 
3. I publish the page
4. When I preview the page the HTML is stripped out. 

Any inline code is stripped from the rendered page. 

adding element:
<img width="1405" alt="screen shot 2018-02-03 at 11 50 06 am" src="https://user-images.githubusercontent.com/36110009/35769948-c1e90804-08d8-11e8-8797-c761d2e1c63b.png">

pasting CODE:
<img width="517" alt="screen shot 2018-02-03 at 11 50 17 am" src="https://user-images.githubusercontent.com/36110009/35769950-c6a20d96-08d8-11e8-8386-6660bf7e5284.png">

Rendered page minus code.
![screen shot 2018-02-03 at 11 50 37 am](https://user-images.githubusercontent.com/36110009/35769952-ca4e8dd4-08d8-11e8-80be-7560f1be49ff.png)

**Comment by MaxSakur** [comment]
Hey, just add this peace of code to your functions.php


remove_filter( 'the_content', 'wpautop' ); 
remove_filter( 'the_excerpt', 'wpautop' ); 
remove_filter('comment_text', 'wpautop');

**Comment by ViorelEremia** [comment]
There is no way to do that. If you want to use html in option type editor add a textarea or you can try to use tags <p class="someClass"></p> with classes. The issue occurs because we use some triggers js events like click, resize to refresh editor we tried several methods but no result has been obtained.
