### ISSUE TITLE
Event extension order by date

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#3178]
Hi guys,

I came across [this topic](https://github.com/ThemeFuse/Unyson/issues/711) from 2015 regarding ordering events by date in a custom event archive, is this possible as yet? As it seems a standard functionality required for events.

Thank you

**Comment by ViorelEremia** [comment]
We can't do that because there are too many probabilities of errors. For exemple if you use addable option type how to sort them into multiple query, this is an example of thousands. So when you start a theme or some functionally you need to think where/how you will extract these events what kind of sort, etc so this feature will not be added because it is very complicated to calculate what each programmer will do.
