### ISSUE TITLE
Combine page options and Theme Settings options

### ISSUE THREAD

**Issue by Kraantje85** [ThemeFuse/Unyson#3208]
Is it possible to let people fill some content in the 'Theme Settings' and on page level people can overwrite that value? And if its possible how can i do this? 

I have made the option in the 'Theme Settings' and i made a 'Page option' also but how can i combine them so the Page option will overwrite the theme settings option?

```
<?php 

	$atts = fw_get_db_settings_option();  // If i use this one i get the Theme Settings values
	$atts = fw_get_db_post_option(); //  If i use this one i get the Page options values
	
	echo '<h1>' . $atts['title'] . '</h1>
	<p>' . $atts['content'] . '</p>
?>
```

Thank you for the help. :-)

**Comment by ViorelEremia** [comment]
You can't because of page id you will rewrite for all pages. But let say you want to add a global(theme options and pages) option type select(Choose header) with key db ```header```. So for every options what you want to be global, in page you add one more option so in page options the select will have all your headers ex:headerOne, headerThree etc. and plus one more option let's call it global if user choose this option then you must rewrite it with option from theme options.
```
$pageHeader = fw_get_db_post_option( get_the_ID(), 'header' );
$themeOptionsHeader = fw_get_db_settings_option( 'header' );
$headerId = $pageHeader && 'global' !== $pageHeader ? $pageHeader : $themeOptionsHeader;
```
If you want to add an input in both sides you can check them by values empty or not.
If page input is empty then get it from the theme options and if the theme option input is empty do nothing.
Ex of option from page:
```
array(
	'type'  => 'select',
	'value' => 'global',
	'label' => __('Header', '{domain}'),
	'choices' => array(
		'global'    => __('Global', '{domain}'),
		'headerOne' => __('Header One', '{domain}'),
		'headerOne' => __('Header One', '{domain}'),
	),
),
```
Exemple from theme options:
```
array(
	'type'  => 'select',
	'value' => 'global',
	'label' => __('Header', '{domain}'),
	'choices' => array(
		'headerOne' => __('Header One', '{domain}'),
		'headerOne' => __('Header One', '{domain}'),
	),
),
```
