### ISSUE TITLE
Link content elements

### ISSUE THREAD

**Issue by ricardososa8** [ThemeFuse/Unyson#3216]
Hi guys!

I would like to link content elements. I mean, I would like to publish a page with just one element, for example "Countdown" and when I edit the page, the others that use those elements woud be altered. The idea is not repeat the work for every page and have the possibilite that users cannot edit a page but they can edit just neccesary elements,

Thanks in advance

**Comment by ViorelEremia** [comment]
I can't understand you very well but I'll try to say what I understand.
The only way that can I see is to create a custom a specific page, for example, let's name it "Elements" in this page you add all elements which serve as a standard for all elements of the same type on all pages. When you saving this page you must extract all the data from the pages you have and change their options with standard options from elements page. I want to say what you want to do is very dangerous, you have to be very careful to do all these, because you need to alterate not everything in one shortcode for exemple for button you can't change for all buttons from entire site text button on one page this can be "send message" on another page this can be "Submit form" so some options you need to alterate for exemple color button and some that are specific for one page you can't like: text, items, icon, .. etc.
```
function prefix_change_themes( $post_id ) {
	// here you have a json with all standard elements
	// Perform some actions on this array to have all elements on one level: array( 'button' => array( button shortcode settings ) )
	$standardEelements = json_decode( fw_get_db_post_option( $post_id, 'page-builder/json' ), true );

	// Exclude page elements we don't need it.
	$args = array( 'exclude' => array( 'page "Eelements" id' ) );

	$pages = get_pages( $args );

	foreach ( $pages as $page ) {
		$data = fw_get_db_post_option( $page->ID, 'page-builder' );

		if ( empty( $data['builder_active'] ) || empty( $data['json'] ) ) {
			continue;
		}

		// Now you have all elements for this page
		$data['json'] = json_decode( $data['json'], true );

		foreach ( $data['json'] as &$set ) {
			
			if ( $set['shortcode'] === 'button' ) {
				$set['atts']['color'] = $standardEelements['button']['atts']['color'];
			} elseif ( $set['shortcode'] === 'another shortcode' ) {

			}
		}
		
		update_post_meta( $page->ID, 'page-builder', $data );
	}
}
add_action( 'post_updated', 'prefix_change_themes', 10, 1 );
```

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
