### ISSUE TITLE
Show post date and category on portfolio single projects

### ISSUE THREAD

**Issue by itanhduy** [ThemeFuse/Unyson#3261]
Hi,
I would like to show post date and category on portfolio single projects. How can I get it?
May you tell which file I need to edit and the API for getting post date and category?

![screen shot 2018-03-15 at 1 53 09 am](https://user-images.githubusercontent.com/10527554/37424858-1f66cdce-27f4-11e8-906b-d0c9b31ffa29.png)

![screen shot 2018-03-15 at 1 59 32 am](https://user-images.githubusercontent.com/10527554/37425168-03fee0f2-27f5-11e8-81d1-e43a12ff1adc.png)

Thanks in advance.

**Comment by ViorelEremia** [comment]
First of all, check if your theme rewrites this file ```YourTheme\framework-customizations\extensions\portfolio\views\single.php``` if it exists then you need to create a child theme because it can be rewritten on theme update. How to create a child theme you can see here: https://codex.wordpress.org/Child_Themes. More details how unyson overwrite file through child/parent heme see here: http://manual.unyson.io/en/latest/convention/directory-structure.html

Shortly you must create a child theme and create a file in this path: ```YourChildTheme\framework-customizations\extensions\portfolio\views\single.php``` copy it from the parent theme.
