### ISSUE TITLE
Unyson not playing nice with Varnish-caching

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#3269]
Unyson uses `session_start()` on some places, which apparently causes Varnish-caching to fail for us.

Did someone else get Varnish working with a site running with Unyson? Is there something that can be done about it?

**Comment by ViorelEremia** [comment]
can you try this branch? https://github.com/ThemeFuse/Unyson/tree/sessions

**Comment by warudin** [comment]
I've added the changed file and as far as I can see this works.

**Comment by ViorelEremia** [comment]
@warudin I reverted commits so unyson will continues to use sessions. Now forms messages not work with this branch; I have to think of another mechanism. Try to enable sessions or keep the current file version after next update of unyson.

**Comment by badgerland** [comment]
The link doesn't work anymore, can anyone give me the fix for this? I am getting the following from my hosting company::
"After reviewing this issue for you, it appears there is a conflict with your Unyson plugin that is preventing the server from caching properly. 
I tested this by disabling the Unyson plugin temporarily and running the
command: wp varnish debug from within your domain's directory. With the
Unyson plugin disabled, the server caches the site properly without any issues.
In this case, I would recommend reaching out to the Unyson plugin developers to determine if there is a workaround to allow that plugin to work with the nginx server cache, or alternatively, you may want to look into a different plugin which would be more compatible."

**Comment by warudin** [comment]
@badgerland: as can be seen in the last message of @ViorelEremia, the changes have been reverted because of problems. ViorelEremia would think about another solution, but as the ticket has been closed, I don't think that there will be any follow-ups. 

That being said, the ticket shouldn't remain closed since the changes have been reverted and thus the problem hasn't been solved.
