### ISSUE TITLE
Forms not working unyson plugin #3273

### ISSUE THREAD

**Issue by farajali** [ThemeFuse/Unyson#3276]
when i contacted to godaddy team they had given some setting to update it with script.
and they told that script would start working. setting is given below please find it and update accrodingly.

host: localhost
port: 25
ssl: false
authencation: none

**Comment by ViorelEremia** [comment]
Configure your mail server. Try to send from another service like Gmail an email to your email server(```info@brightonworldschool.org.in```) so you can see that your server doesn't receive anything. If you replace your email with a Gmail email to shortcode settings the shortcode is working so the problem is not from shortcode settings configuration but your server mail.
