### ISSUE TITLE
Theme options switch default value

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson#33]
Hi,

i am developing a theme using unyson framework. i have theme options fields using switch field. 

when i make a fresh installation with no options in database, i do have default values set in theme options file, for example true value for switch option. In wordpress theme options page, i am always getting false values for every switch option. 

how to solve this ? thank you very much.

**Comment by MikeiLL** [comment]
@pudeco Thank you for sharing your code. I actually found a bug in it which is that whereas:

```
'wpml_switcher' => array(
    'label' => __('Language Selector Visibility', 'pudeco'),
    'desc' => __('Toggle language selector of the header on or off ( WPML Required )', 'pudeco'),
    'type' => 'switch',
)
```

returns a php boolean value (1, 0), the above code returns a string. So that in the view, `$atts['wpml_switcher']` would not be able to be used to test for a true value (because the string 'false' is true. Substituting 1 for 'true' and 0 for 'false' instead is working for me.
