### ISSUE TITLE
Unyson Not Working

### ISSUE THREAD

**Issue by healyjames** [ThemeFuse/Unyson#3380]
Hi,

Unyson is not working on my wordpress site. 

When I go to edit a page, there is no page builder and Unyson doesn't appear.

I have tried uninstalling and re installing. I have the latest version too. not sure what to do next...

Any ideas on how to fix?

James.

**Comment by ViorelEremia** [comment]
Have you the latest extensions? #2764 (comment)
Remove any cache from server, browser, server.

**Comment by healyjames** [comment]
I have the latest extension and removed any cache from those sources but it's still not working.

Any other ideas?

**Comment by ViorelEremia** [comment]
do you have the server from cloudflare?

**Comment by ViorelEremia** [comment]
cloudways

**Comment by healyjames** [comment]
As far as I am aware, our servers are from FastHosts and none of the above.

**Comment by ViorelEremia** [comment]
Have you any errors in the browser console?

**Comment by healyjames** [comment]
The only error being thrown up is the following...

Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS.

Not sure if that means anything to you.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by healyjames** [comment]
I have sent across an email.

**Comment by ViorelEremia** [comment]
You don't have installed the extension page builder. I tried to install it and it seems what wordpress doesn't have permissions to write in the unyson folder. Extensions are saved in unyson/framework/extensions/ So here WordPress has no permission to write. At the moment I installed all required extensions with php constant ```define('FS_METHOD', 'direct');``` but you cant use it because of security reasons. Please contact your server administrator. If wordpress has no permissions to write then your unyson extensions will not be able to be updated.

**Comment by healyjames** [comment]
So are you saying that unless we change the permissions, each time we update WordPress we will run into the same problem?

**Comment by ViorelEremia** [comment]
Not wordpress but unyson updater extensions or wordpress plugin updater.

**Comment by healyjames** [comment]
Okay - Thanks for your help Viorel!
