### ISSUE TITLE
[question] How can we use fw.OptionsModal

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#341]
Do you mind showing us a usage example of fw.OptionsModal
https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/04fef3adaedbf5876ccbdd589d7b44157c27482f/includes/option-types/builder/static/js/template-saving.js#L33

I would like to use it in my custom option just like you do in Save Template in builder. 
With a text option type,

I need the option to match the framework so I rather not use

    add_thickbox();

Thank you!

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/8d223a207340d1102400354fd0adbe7e41fd5144/framework/static/js/fw.js#L481-L508

**Comment by moldcraft** [comment]
The workflow is this:

1. You provide options array.
2. When you call `modal.open()` it makes and AJAX request, renders options html on server side and displays it in modal.
3. When the Save button is pressed, an AJAX form submit request is made to extract options values.
4. The `values` (Backbone) attribute is updated and the `change:values` event is fired.

**Comment by danyj** [comment]
True teacher! Thank you!

**Comment by danyj** [comment]
Is there a hook that can prevent the save/close if let say only 2 chars are added ? 

like 

			$(document.body).on('keyup','#fw-edit-options-modal-thzstylename',function (){	
				
				if($(this).val().length < 3){
					// prevent save and add some warning
				}
			});

**Comment by moldcraft** [comment]
> Is there a hook that can prevent the save if let say only 2 chars are added ?

No. We we never used required inputs, or inputs with requirements. Only in `FW_Option_Type::_get_value_from_input()` we check if the value is not valid, then we reset it to default value or some hardcoded correct value.

The idea of the builder is that the user can just add elements/shortcodes without opening any settings modal, and everything should work.

What if he is just trying your theme and by curiosity opened that options modal, then he can't close it because you require him to enter some input he doesn't care, I think he will be frustrated.

**Comment by danyj** [comment]
I got this solved. I did not express myself properly. I just did not want the user to save the new style if a style by that name already exists. I am rtuning some ajax checks while the user is typing, and if the style with name exists , I  hide the save button. If he removes/adds one more letter the save comes back. Closing works just fine.
