### ISSUE TITLE
UNYSON calendar and XML file

### ISSUE THREAD

**Issue by magisterson** [ThemeFuse/Unyson#3414]
Hi there! I am using UNYSON calendar to display events, but got two questions:

1. how to input data from XML file to this calendar? I don't want to use buildin EVENT tab, i Have mu Own events list.

2. How to disable hyperlkinking to every single event?

**Comment by ViorelEremia** [comment]
To import from xml you must have some skills of php and js you must parse xml via php class xml and import it but here is a lot of work to do and good knowledge of programming languages as php js css. if you doubt your knowledge, then hire someone because it's not easy to do that.
About ```How to disable hyperlkinking to every single event?``` you must overwrite the shortcode calendar: http://manual.unyson.io/en/latest/extension/shortcodes/index.html 
Or you can contact your theme developer.
