### ISSUE TITLE
Please DO NOT force Brizy on the dashboard.

### ISSUE THREAD

**Issue by yesandagency** [ThemeFuse/Unyson#3415]
Brizy great and it is your new baby and all, I do get that but, since the last unyson update all my clients are emailing me about CTA comes up on the dashboard and some start installing it. Can you guys please keep it under the extensions like it is and dont create banners/notifications on plugin update please.

**Comment by kellymears** [comment]
I really like Brizy and would also like to second this. Please don't push notifications for things that are not critical or otherwise promotional. At least don't do it in a network configuration outside of the Super Admin role. 

In production it just looks like something is broken -- they are asked to install something, it doesn't install because FS_METHOD isn't DIRECT in that environment anyway, and then I get support tickets.

Brizy is really nice, though. Congrats on the launch.

**Comment by ViorelEremia** [comment]
Redirect and install brizy was deleted. About dashboard notification write here: https://github.com/ThemeFuse/Unyson/issues/3387
