### ISSUE TITLE
Demo content installation errors

### ISSUE THREAD

**Issue by yura-x** [ThemeFuse/Unyson#3459]
Hello! 
For the last week many of our customers of various themes based on Unyson has following errors during demo content installation:
```
The execution failed. Please check error.log
```
```
Install Demo Content - Error 28: Curl timeout()
```
```
cURL error 28: Connection timed out after 10000 milliseconds
```
```
URL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```
I made some research in closed issues and found that most of these issues appears on old PHP version, low PHP.INI settings or outdated PHP extensions.

But earlier we had 1 or 2 these issues per month and for the last week it was more than 25 times.

Does anybody have same problems? 
Maybe these problems appears after last Unyson and it's extensions updates?

**Comment by ViorelEremia** [comment]
The only thing I thought maybe this could happen it's because of the request of the client-server to an unsecured protocol(http) now our server with extensions caches has https; In the next update of unyson updater will call https but you can try to test before it; change this line: https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/hooks.php#L147
which is unlikely because the error of the message clearly shows what is going on.
Also you can test is our server guilty by adding this code in functions.php: 
```
add_action( 'wp_head', function () {
	if ( ! is_admin() ) {
	    return;
    }

	$remote = wp_remote_get( 'https://api.github.com/' );
	fw_print( $remote['body'] );
	$http     = new WP_Http();
	$response = $http->get( 'https://api.github.com/' );
	fw_print( $response['body'] );
} );

```
