### ISSUE TITLE
Unyson Plugin is making the images on my pages "disappear"

### ISSUE THREAD

**Issue by DiannaLara** [ThemeFuse/Unyson#3463]
I have next to no understand of coding or website development, etc., so bear with me...

I have a website that has been working just fine until yesterday. On my Home Page I noticed that the images in my "Current Projects"  and "Latest Post" sections were loading initially then a few seconds later  were "disappearing" as thumbnails with the image description. Someone suggested deactivating all plugins to find the culprit. I did. It's Unyson. With the plugin deactivate my images are unaffected, but almost all of the other elements on the pages disappear like the slider, the calendar, buttons, etc.

What can I do? And please explain it to my like I'm 5 years-old. :)

(P.S. I checked to make sure I have the latest version of Wordpress and that all the Unyson extensions are up-to-date)

**Comment by ViorelEremia** [comment]
Hi, Dianna, I'm 7 years old and I already have some knowledge of some programming languages :) and we are now in kindergarten and we think it is a theme issue because Unyson is a plugin which facilitates the creation of themes so developers of themes use it to create themes that means some issues comes from themes. But I can help you if you send me some temporary credentials (admin, ftp): ```viorel@themefuse.com``` and please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
