### ISSUE TITLE
New extensions updates should show what extension

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3474]
Currently New extensions updates available notification is not showing what extension needs an update. Because of issues like this https://github.com/ThemeFuse/Unyson/issues/3472#issuecomment-400068070

we should advise what extension requires the update so that we can advise the users to wait if necessary. 
One user testing https://github.com/ThemeFuse/Unyson/issues/3422#issuecomment-397622932 is not a measure to release such a complicated update. 

And that update was not even added to Extension approval as it should have been, 
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues?q=is%3Aissue+is%3Aclosed

Last one that was added for backups was 2.0.27.

Please lets keep this as it was.

**Comment by ViorelEremia** [comment]
I do not agree with you, not in this case. The [issue](https://github.com/ThemeFuse/Unyson/issues/3422) it's a major issue than yours because the user must install wordpress again and what's worse is that the user can lose the content and now imagine a site with 150 pages created with page builder you cannot restore them anymore and this has happened to us but saved us the server backup. The final user doesn't know how everything is working and then he sees that the wordpress must installed again then they remove everything on the server but on the server is also and the backup archives.
About testing, there was not only one we also tested you know we have also premium themes in sale and other products, custom works etc.
So I think we're doing right in such cases, and I think that will happen again and again in the future because we can't follow every update of the wordpress plugins like was for woocommerce that generates the issue.

**Comment by danyj** [comment]
I am not sure how any of the issues mentioned have anything to do with the notice. I am asking to tell us admins what extension requires update so that we can test accordingly in a case when you issue an update without previously advising us. I am not against quick patches but none of us that had issue since that update knew that a major change was in and seeing "New extensions updates available." does not tell us anything else.  

I also never said my issue is bigger issue or vice versa but their issue fix broke other users demo installs which puts us all in a same boat.  All I am asking for is a clarification. 

Note that I am watching the  Unyson-Extensions-Approval git and we did not see a notice for backups 2.0.28 but the update was released. Yes you did had to do quick patch but that patch messed others up. 

This notice should simply list what extension needs an update. Seeing unproved extension in there would make me do an immediate test. 

![screenshot_22](https://user-images.githubusercontent.com/2340172/42029395-b53cb7cc-7acf-11e8-800b-03e73d10fb20.jpg)


This is also how we would know that there was quick patch issued if there was no previous approval test . That would makes us test more and report bugs faster.

**Comment by danyj** [comment]
So all I am asking for is this right under the update extension notice. 

```
"New extensions updates available." 

Backup & Demo Content
Mega Menu
SEO

```

**Comment by ViorelEremia** [comment]
I do not know why this has not been added by default but you can do that for your theme add in ```theme/framework-customizations/extensions/update``` file config.php with code: 
```
<?php if (!defined('FW')) die('Forbidden');

$cfg = array();

/**
 * Do not show details about each extension update, but show it as one update
 * (simplify users life)
 */
$cfg['extensions_as_one_update'] = true;

```
Result
![wordpress updates single wordpress](https://user-images.githubusercontent.com/28967378/42030284-f3a0f8f6-7ada-11e8-82dd-098f971475c4.png)

**Comment by danyj** [comment]
There you go. I never knew about it. Thnx will add

**Comment by danyj** [comment]
ah no , we need to duplicate the folders and add files for it to be turned on ?
any faster way without adding files and folders?

**Comment by danyj** [comment]
hook , theme manifest , anything else ?

**Comment by ViorelEremia** [comment]
Theres no hook for it; why can't add a file config.php in yoour theme? I don't understnad "duplicate the folders"?

**Comment by danyj** [comment]
I can, is just more files and folders for a simple true statement , was hoping for something faster

**Comment by ViorelEremia** [comment]
use filter:
```add_action( 'fw_extensions_as_one_update', '__return_false' );```

**Comment by danyj** [comment]
bless you!

**Comment by ivandotv** [comment]
I'm on `12.7.18`And this new `hook` doesn't  exists.
