### ISSUE TITLE
How can I use font-awesome???

### ISSUE THREAD

**Issue by shaonsina** [ThemeFuse/Unyson#3497]
I would like to use **font-awesome** in the front-end. Which CSS file used back-end (located: `framework/static/libs/font-awesome/css/font-awesome.min.css`).
Actually, I don't want to call another CSS file for the front-end.

**Comment by ViorelEremia** [comment]
To use it you must load it in your theme/extension/etc you can't use the files that load it to frontend declared in unyson the best way I see it:
```
function theme_name_scripts() {
	
	if ( ! function_exists( 'fw' ) ) {
		return;
	}
	
	wp_enqueue_style(
		'font-awesome',
		fw_get_framework_directory_uri( '/static/libs/font-awesome/css/font-awesome.min.css' ),
		array(),
		fw()->manifest->get_version()
	);
}
add_action( 'wp_enqueue_scripts', 'theme_name_scripts' );
```
the most important part it is do not change the handle of the script I mean ```font-awesome``` because if you use for example extension megamenu which also loads this file and you rename the handle in your theme then this file will be loaded twice.

**Comment by shaonsina** [comment]
Thanks. Now it's working.
