### ISSUE TITLE
date picker date format

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#386]
Hi
 i have tried to date format like Y/m/d.  default is d-m-Y

i have changed 'min-date' => date('Y/m/d'), also  but nothing happened.
is it possible to change date format in date picker ??

Thank you

**Comment by valeriuzdrobau** [comment]
Now is not possible because we have saved in the database instead of timestamp string and if we change risks upsetting from customers already using this option in the way it works now. We will analyze and to one of the next versions will implement this capability. We apologize, but at the moment the best solution is to create your an option in framework-type customization.

**Comment by xpeeder** [comment]
@valeriuzdrobau  i will use now normal option with text field. hope if you update in next version i will change this again with date-picker :)

Thanks

**Comment by martin-bede** [comment]
Hi, if you want to change the date format I'm doing it like this:

```
$date = $atts['date'];
$timestamp = strtotime($date);
$formatted_date = date('l jS F Y', $timestamp);```

**Comment by xpeeder** [comment]
@martin-bede  Thanks mate its work :+1:  ☕

**Comment by martin-bede** [comment]
No worries, I'm sure you know but put what ever combo you want on the last line to format it differently.
