### ISSUE TITLE
Style not available under appearance menu

### ISSUE THREAD

**Issue by softcircles** [ThemeFuse/Unyson#392]
Hi there,

I just installed a fresh wordpress version and using default twenty fifteen theme. no customization made, not even installed any other plugin but only unyson. but strangely I am not able to find "style" under appearance menu. is there anything missing ? or is it my mistake somehow ? please help me. thanks.

regards,
Kax

**Comment by moldcraft** [comment]
The Styling and MegaMenu extensions are visible only when added to

```php
// file: {theme}/framework-customizations/theme/manifest.php

$manifest['supported_extensions'] = array(
    'styling' => array(),
);
```

https://github.com/ThemeFuse/Scratch-Theme/blob/f7c08ab349635ef40dd8b1c88391f4d5bf22b4c4/scratch-parent/framework-customizations/theme/manifest.php#L12

because those extensions has no sense if the theme is not configured to display them correctly.
