### ISSUE TITLE
Unyson Multisite

### ISSUE THREAD

**Issue by oerben** [ThemeFuse/Unyson#393]
First of all, i have to say that i really love this framework. It saves me so much time developing themes.

I have one question regarding to use unyson as plugin on a multisite. 

Let me discribe the circumstances. I build a theme based on the Unyson Framework. A customer want to install this theme on a multisite and he wants to install the theme on a child-site other than site 1. The theme requires the customer to install the plugin via TGM plugin activation*. The customer installs and activates the framework (only for this child-site). 

Now the user can´t install or activate any extension, because this can only be done in the network administrator menu. But Unyson is not visible in the network administrator menu if the framework is not activated for site 1.

Do I have to force my customers to activate the framework for site 1 so they can install and activate extensions, or is there any other way to install extension from a child site?

Addition:
*When the user is is running a multisite the TGM plugin activation is not working very well when the plugin is used in a theme and the theme is not associated with site 1. That is why I wanted to integrate the framework in the theme, so the user does not have to install any plugin.   But as you mentioned in other comments this is not good when you want to sell themes. So there is no "easy" way for the customer to automatically install the Unyson Plugin when the customer is running a multisite.

**Comment by moldcraft** [comment]
Fast answer: The logic that decides if current user can activate or install extensions is in [these methods](https://github.com/ThemeFuse/Unyson/blob/9dfb7c8091e38eaba986d9591b08c84ffc1d3df3/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L65-L118).

*I will come back to this issue later, sorry.*

**Comment by moldcraft** [comment]
@oerben Sorry for late reply.

I have not so much practice with multisite, but I made some test and figured out how it works and made some fixes in framework.

When I tested, I learned/noticed that only network administrator is allowed to install themes and plugins, other sub-administrators can only to switch themes. So I made [this method](https://github.com/ThemeFuse/Unyson/blob/9dfb7c8091e38eaba986d9591b08c84ffc1d3df3/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L99-L118) that returns true only when the user is network administrator, and [this method](https://github.com/ThemeFuse/Unyson/blob/9dfb7c8091e38eaba986d9591b08c84ffc1d3df3/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L72-L91) that returns true if the user is any administrator (network a simple (sub)site).

Did I made something wrong? If I did, how should I fix it?

**Comment by glerner** [comment]
With WordPress Version 4.2.1 | Unyson 2.2.8 I installed Unyson as network administrator on the main site, and enabled the entire suite of extensions. Then in admin for a subsite, I enabled the plugin. On /subsite/wp-admin/admin.php?page=fw-extensions I get only "Unyson Extensions" and in the footer the Unyson version.

From the main site, I installed extensions, and they show as installed.

Are you assuming the location of a file instead of requesting the site location from WordPress? 

Assuming the name of tables? For site 4, MYPREFIX_4_fw_termmeta is empty; fields meta_id, fw_term_id, meta_key, meta_value. (MYPREFIX_fw_termmeta is also empty.)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/709#issuecomment-120767539

**Comment by moldcraft** [comment]
> The theme requires the customer to install the plugin via TGM plugin activation*. The customer installs and activates the framework (only for this child-site).

As far as I know, you can't install plugins or themes on child sites. Only network administrator can install them. Can you make a video demonstration how you install plugins from child-site?

> But Unyson is not visible in the network administrator menu if the framework is not activated for site 1.

Can you test that now? I should not happen.

> is there any other way to install extension from a child site?

It is not right to install/remove extensions from child site, because it will affect all sites on that installation (because the files are shared, there is no separate `extensions/` directory for each child-site). So I think it's right that only network administrator can do that.

> When the user is is running a multisite the TGM plugin activation is not working very well when the plugin is used in a theme and the theme is not associated with site 1.

Please report that problem here https://github.com/TGMPA/TGM-Plugin-Activation

> That is why I wanted to integrate the framework in the theme, so the user does not have to install any plugin.

We do not recommended that, because:

* Your theme will not be accepted on ThemeForest, because it violates [Plugin Territory](https://make.wordpress.org/themes/handbook/guidelines/plugin-territory/)
* You will have to provide framework updates by yourself, by creating theme update on every Unyson update.

    * When the theme is update, everything in parent theme is replaced, so all installed extensions will be deleted and after every theme update the client will have to install them again.

> Are you assuming the location of a file instead of requesting the site location from WordPress?

I don't think I understand this question (try to ask again in other words or more detailed).

We don't have any custom detection mechanisms that would make the extensions work differently or loaded from other locations on multisite. They are installed and loaded from the same location as on simple site `wp-content/plugins/unyson/framework/extensions`.

> Assuming the name of tables? For site 4, MYPREFIX_4_fw_termmeta is empty; fields meta_id, fw_term_id, meta_key, meta_value. (MYPREFIX_fw_termmeta is also empty.)

We use default WordPress functions to work with the database, and those functions are taking care to work fine on multisite and simple site. We don't have any hardcoded table or column names in sql.
