### ISSUE TITLE
Warning: Recursive shortcodes load in /wp-content/plugins/unyson/framework/extensions/shortcodes/class-fw-extension-shortcodes.php 

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#396]
Hi Guys,
When I enabled the wp_debug , I am getting this warning on my WP page editor. Anyway to resolve this issue?

**Comment by moldcraft** [comment]
This happens when inside some shortcode is called [one of these methods](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/89597be5467cb7747a1983a5b7aff797a08c5c0a/class-fw-extension-shortcodes.php#L8-L29), while the loading process is in progress.

Can you do a search to check which shortcode is calling one of those methods? Is that shortcode located in framework or in your theme?

Thanks

**Comment by linjo** [comment]
Thanks guys, I got it fixed :)
