### ISSUE TITLE
Error in "Portfolio" extension

### ISSUE THREAD

**Issue by Anydog** [ThemeFuse/Unyson#414]
Hi,
first of all - great work ! However, when I install "scratch-parent" theme and activate Unyson plugin (all latest versions, on fresh WP install), got this error

Notice: Undefined variable: other_existing_paths in [my local server path]\wp-content\themes\scratch-parent\framework-customizations\extensions\portfolio\static.php on line 9

Warning: include(): Filename cannot be empty in [my local server path]\wp-content\themes\scratch-parent\framework-customizations\extensions\portfolio\static.php on line 9

Warning: include(): Failed opening '' for inclusion (include_path='.;C:\xampp\php\PEAR') in [my local server path]\wp-content\themes\scratch-parent\framework-customizations\extensions\portfolio\static.php on line 9

I prefer not to dig into your code there, I thought you must have better idea ... :)
Any ideas ?

**Comment by llemurya** [comment]
@Anydog please install the latest version of the scratch-theme , because you use an old version, as a proof please see in the source code, in latest version at line 9 is  this [code line](https://github.com/ThemeFuse/Scratch-Theme/blob/4db4e1b2e9860f7ec9dbaa2ab4106f7bbd047334/scratch-parent/framework-customizations/extensions/portfolio/static.php), in the old version at line 9 is this [code line](https://github.com/ThemeFuse/Scratch-Theme/blob/f54cf0c2ed2a917f79414c67abcab0b76e5a4058/scratch-parent/framework-customizations/extensions/portfolio/static.php) that trigger your error. Please download and install the latest version of the scratch-theme and give us a feedback if it works.

**Comment by Anydog** [comment]
Yes, it works ... thanks

**Comment by llemurya** [comment]
@Anydog thanks for feedback!
