### ISSUE TITLE
Fatal error occured when creating new navigation menu

### ISSUE THREAD

**Issue by zaneyu** [ThemeFuse/Unyson#419]
Unyson version: the latest

Error Information:

Fatal error: Cannot redeclare class fw_option_type_multi_select in .../wp-content/plugins/unyson/framework/includes/option-types/multi-select/class-fw-option-type-multi-select.php on line 11

**Comment by moldcraft** [comment]
I opened this page `/wp-admin/nav-menus.php?action=edit&menu=0` and created a new menu, everything works fine.

Also I added [here](https://github.com/ThemeFuse/Unyson/blob/02ccb848072e7d7ac80f3c721cbdf77fa568448e/framework/includes/hooks.php#L19)

```php
require dirname(__FILE__) . '/option-types/multi-select/class-fw-option-type-multi-select.php';
require dirname(__FILE__) . '/option-types/multi-select/class-fw-option-type-multi-select.php';
```

so the file is included multiple times, but I can't get that fatal error. I shouldn't because here is [this `if`](https://github.com/ThemeFuse/Unyson/blob/02ccb848072e7d7ac80f3c721cbdf77fa568448e/framework/includes/option-types/multi-select/class-fw-option-type-multi-select.php#L5)

**Comment by zaneyu** [comment]
@moldcraft Thank you for checking the problem.
I just re-activated the plugin and the issue didn't reproduce either.
