### ISSUE TITLE
Error when updating today

### ISSUE THREAD

**Issue by maod321** [ThemeFuse/Unyson#426]
Updated Unyson plugin to day and ok until updated extensions then Parse error: syntax error, unexpected '[' in /home15/ommanage/public_html/wp-content/plugins/unyson/framework/extensions/events/extensions/events-tags/class-fw-extension-events-tags.php on line 394.

**Comment by moldcraft** [comment]
[There](https://github.com/ThemeFuse/Unyson-Events-Extension/blob/8c97e4ab96e8e4c5851c91c5af5566171c4bc7ca/extensions/events-tags/class-fw-extension-events-tags.php#L394) is used a [php 5.4 feature](http://stackoverflow.com/a/15277890/1794248)

```php
$value = some_function_that_returns_an_array()['array_key'];
```

which violates our (and WordPress) [no php 5.3+ features convention](http://manual.unyson.io/en/latest/convention/general.html#content).

It will be fixed in the next Events version. Until then, you can fix it manually:

Open `unyson/framework/extensions/events/extensions/events-tags/class-fw-extension-events-tags.php` line 394, and replace:

```php
$language = substr( wpml_get_language_information( $post_id )['locale'], 0, 2 );
```

with

```php
$language_information = wpml_get_language_information( $post_id );
$language = substr( $language_information['locale'], 0, 2 );
unset($language_information);
```

Thank you for the report.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Events-Extension/commit/5877990f7f44d3015d8e9542aef1ac8e0f0ab602?diff=unified#diff-d79dced1ba15ade03f0e75e33d301091R365

**Comment by thednp** [comment]
I also want to point out an issue on update:
* when updating via Google Chrome, if you focus out the window while the scripts are processing the update, when coming back after a little while the page is blank with message "Forbidden"
* I had to delete/rename Unyson powered theme and reinstall/rename to fix the issue.

You must WRITE A CLEAR NOTE: don't close or leave the window while update is processing, because (see details above, Google Chrome kills running scripts on window focus out)

**Comment by GheorgheP** [comment]
Hi @thednp,

I just tried out this and don't get such problem. Could you provide a step by step scenario? Also, try one more time by deactivating all extensions of you browser.

**Comment by thednp** [comment]
OK, will do that with the next extensions and plugin update. But I am very sure Google Chrome is doing that (among many others), mostly for performance reasons.

**Comment by GheorgheP** [comment]
Hi,

You can go in the `manifest.php` of each extension and set it to a lower version and try one more time

**Comment by Nic787** [comment]
I got this error too last week when updating. Thank you to write how to fixe that.

**Comment by GheorgheP** [comment]
@Nic787, same scenario how @thednp described?

**Comment by Nic787** [comment]
I had the same error, but now it work with the last update.

**Comment by GheorgheP** [comment]
Hi,

Did anyone else get this problem? Because I'm trying to get the problem, but all seems to work fine.

**Comment by Nic787** [comment]
Everything work fine.

**Comment by GheorgheP** [comment]
Does someone still get this problem or we can close the issue?

**Comment by thednp** [comment]
I believe you can close it for now. If I get my error again, will open a new issue with detailed replicate guide.

**Comment by maod321** [comment]
You can close now thanks for your help
