### ISSUE TITLE
Error when update images in slider

### ISSUE THREAD

**Issue by ziuzea87** [ThemeFuse/Unyson#449]
This is what I get when updating images on the slider.

Fatal error: Call to a member function get_multimedia_types() on a non-object in /hermes/bosoraweb118/b432/ipw.creatingchiccom/public_html/wp-content/plugins/unyson/framework/extensions/media/extensions/slider/class-fw-extension-slider.php on line 294

**Comment by llemurya** [comment]
@ziuzea87 please write details about your Unyson version and Slider version from manifest, or make update at the Unyson and Slider, create a new slider and test if error persist.Thanks for the feedback. I am waiting for your response.

**Comment by ziuzea87** [comment]
I'm using latest Unyson 2.2.7 and latest version of your Exposure theme. Can provide the login and ftp details for you to see the issue. I also get an error with slider when access website from mobile device.

**Comment by llemurya** [comment]
@ziuzea87 this bug is not from Unyson , is from a plugin called [Simple Wp Sitemap](https://wordpress.org/plugins/simple-wp-sitemap/), I opened and [issue](https://wordpress.org/support/topic/bug-in-postphp-page?replies=1), hope they will fix it, at the moment I uninstalled the plugin from the client server. And I close this issue because is not an Unyson problem , but a third party plugin problem.

**Comment by pe6o** [comment]
Whoa, why is `$post` changed and `wp_reset_postdata()` is not resetting it? 

I implemented the solution and now it works. Can't understand why the global `$post` stayed changed..
