### ISSUE TITLE
Typography Option  - how to select multiple styles for Google web fonts?

### ISSUE THREAD

**Issue by dameer** [ThemeFuse/Unyson#458]
Maybe I'm missing the point but it looks like there's no way to select multiple styles for a Google font. It's kinda silly to have a drop-down with several font styles/variations and not be able to grab all at once!

Is there anything that can be done in regards to it?

For example, my theme uses several variants of "Lato" (from 300 to 700 + italic) and all I can do is to select only one style while all other are "emulated" by Browser. It doesn't look right at all.

Another problem is the font family subset. Why is it ignored? Many fonts include it!

Unyson is awesome but typography option can't be worse :)

**Comment by valeriuzdrobau** [comment]
Typography option is designed to set the color, font size and style of a particular CSS selector, based on a type typography options, the theme developer needs to generate some css , [here ](https://github.com/ThemeFuse/Unyson/issues/433) you have an example of using this type of option. I know this type of option requires many improvements, but it came to what is now a compromise.
For performance it was decided not to load all the fonts to preview this reason they take a picture and because of this they are but are harcoded somewhere, but were created [filters](https://github.com/ThemeFuse/Unyson/issues/212) for developers to insert the fonts they need .

If you do not meet as he is now working, as long as we do not did another to solve the above problems, we recommend you create your typography option in framework-customizations folder.

**Comment by dameer** [comment]
Thanks! Luckily Unyson is flexible enough so I ended up creating new option type which works just fine.
Another problem regarding default Typography option is the fact that we can't update "fw-google-fonts.json.php" because 
a) it doesn't share the same data structure (I guess it should follow GFonts API response)
b) it can't be overridden in framework customization
Hopefully there will be some improvements soon!

Thanks for a great job anyway!

**Comment by valeriuzdrobau** [comment]
We recommend using [`typography-v2`](http://manual.unyson.io/en/latest/options/built-in-option-types.html#typography-v2) option type.
