### ISSUE TITLE
Fusion core plugin  from avada kills Unyson slider

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#464]
Looks like fusion slider is taking over Unyson slider , 

fusion on
http://prntscr.com/6u0xxg

fusion off
http://prntscr.com/6u0y5l

**Comment by llemurya** [comment]
@danyj the problem is not in slider , the fusion core plugin rewrite all shortcodes that have the same name, for example if you have an button shortcode and in the fusion core plugin exists this shortcode with name button it will be rendered on `do_shortcode`.This is not an Unyson or Slider bug, this is a collision name problem, if you want to work with 2 builders , rename your shortcodes in order to have different names, we won't do this , because on the next update all data from users will crash.If you agree with our position please close the issue.

**Comment by danyj** [comment]
never said is a bug , noticed that fusion takes over , just wanted to give you heads up on it.  
crash fusion if is on :)
