### ISSUE TITLE
Select , short-select empty value bug

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#474]
if you leave any of the choices empty , the select will always default to it , example choices 

	'color'  => array(
		'label'   => __( 'Button Color', 'fw' ),
		'desc'    => __( 'Choose a color for your button', 'fw' ),
		'value' => '',
		'type'  => 'short-select',
		'choices' => array(
			''      => __('Default', 'fw'),
			'dark' => __( 'Dark', 'fw' ),
			'blue'  => __( 'Blue', 'fw' ),
			'green' => __( 'Green', 'fw' ),
			'red'   => __( 'Red', 'fw' ),
			'yellow'   => __( 'Yellow', 'fw' ),
			'gray'   => __( 'Gray', 'fw' ),
			'color'   => __( 'Primary theme color', 'fw' ),

		)
	),

**Comment by llemurya** [comment]
@danyj It's a normal behavior of option type, because you set the value as empty string and the value of the choice is the same empty string, it check if is equal it set selected to this option. If you will set the value for example to the dark as default, it will works correct.
```php
'color'  => array(
    'label'   => __( 'Button Color', 'fw' ),
    'desc'    => __( 'Choose a color for your button', 'fw' ),
    'value' => 'dark',//set to dark will verify if value is equal with choices key , if is equal it will be set as selected
    'type'  => 'short-select',
    'choices' => array(
        ''      => __('Default', 'fw'),
        'dark' => __( 'Dark', 'fw' ),
        'blue'  => __( 'Blue', 'fw' ),
        'green' => __( 'Green', 'fw' ),
        'red'   => __( 'Red', 'fw' ),
        'yellow'   => __( 'Yellow', 'fw' ),
        'gray'   => __( 'Gray', 'fw' ),
        'color'   => __( 'Primary theme color', 'fw' ),

    )
),
```
Now your value is empty and the one of the choices value is the same empty that is why it is selected. Please verify and close the issue.

**Comment by danyj** [comment]
no ,  use it and select dark , save , reload , it will default to the empty one

**Comment by danyj** [comment]
and I dont want dark to be default , default should be empty , the first one , 
once user chooses an option it should load choosen option , not reset to the empty one

**Comment by llemurya** [comment]
@danyj I think you have a collision name of the ids, please rename your id from `color` to another name, because I tested , and for me it works , as the proof , please see this [video](https://www.youtube.com/watch?v=mc6FD8E1rG8&feature=youtu.be).If the problem is in collision please close the issue.

**Comment by danyj** [comment]
you could be right , I now move the option somewhere else as is and it works like in your video. thnx for digging and taking time to look at it. closing.

**Comment by danyj** [comment]
sorry for the toruble
