### ISSUE TITLE
Owl slider js bug 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#475]
Owl slider has js bug 

    Uncaught TypeError: Cannot read property '3' of null

no matter how many slides you have 1 or more , and the slides indicate that you should use video links

http://prntscr.com/6w0ypj

**Comment by llemurya** [comment]
@danyj error was because you added an `image src` but the javascript wanted an `vimeo` or `youtube` url, the `owl-carousel` extension is a demo preview how you can make a video slider whats why this should use video links, if you want `owl-carousel` to work with `image` or from `json `, see the [live examples](http://owlcarousel.owlgraphic.com/demos/demos.html) and integrate them in your theme.Thanks a lot for the feedback.

**Comment by danyj** [comment]
@llemurya , no that was just screen , I tested with youtube and mp4 first , same bug was there, last I just experimented with image to make sure it is  abug

**Comment by llemurya** [comment]
@danyj Yes I know that it is a bug, I fixed it, I just described how I reproduced it.

**Comment by danyj** [comment]
should have said it was a bug :) ,  we got it squashed either way, thnx!

**Comment by llemurya** [comment]
@danyj I must test with `youtube` and `mp4` as you made ,to say it was a bug :+1:

**Comment by llemurya** [comment]
@danyj I tested, It will ignore the local videos uploaded to` wordpress install` , it will work only with `youtube` and `vimeo` urls, because the `owl-carousel` fails with an `javascript error` if you give another sources.
