### ISSUE TITLE
FW_Flash_Messages styling/structure

### ISSUE THREAD

**Issue by martin-bede** [ThemeFuse/Unyson#486]
Hi,

I'm wanting to customise how popups are displayed by altering the markup the messages are displayed in. Mainly the contact forms success and error popups.

I know I could edit this: https://github.com/ThemeFuse/Unyson/blob/a2adef26229f5ad1ad015b0b74f657aa59f21235/framework/static/js/fw-form-helpers.js#L57-L76

However I'd then have to do the same for the `onErrors` callback and anywhere else I want to change the output.

Is there a better way to do what I want to do?

Thanks

**Comment by moldcraft** [comment]
Hello,

> However I'd then have to do the same for the `onErrors` callback and **anywhere else**

Can you tell me please where else?

> Is there a better way to do what I want to do?

I don't know any other way.

But it seems simple:

* Create you own copy of [this function](https://github.com/ThemeFuse/Unyson/blob/a2adef26229f5ad1ad015b0b74f657aa59f21235/framework/static/js/fw-form-helpers.js#L194-L218)
* Overwrite `onErrors` and `onSuccess` and use it [instead of this](https://github.com/ThemeFuse/Unyson/blob/a2adef26229f5ad1ad015b0b74f657aa59f21235/framework/static/js/fw-form-helpers.js#L63)

**Comment by martin-bede** [comment]
Thanks, I copied `fwForm.frontend.renderFlashMessages` which allows me to modify the output, that'll work just fine :+1:
