### ISSUE TITLE
No link in textblock

### ISSUE THREAD

**Issue by anoukkolkman** [ThemeFuse/Unyson#509]
It isn't possible to add a text link in the WYSIWYG editor when you're working in a text block. Is there something I can do to turn it on? I've attached a screenshot so you can see what I'm talking about (:

Thanks in advance

![schermafbeelding 2015-05-01 om 10 21 30](https://cloud.githubusercontent.com/assets/7745011/7428186/f4d0a604-efeb-11e4-8e03-bca50ba2ea69.png)

**Comment by llemurya** [comment]
@anoukkolkman you must copy `text-block` shortcode from `unyson/framework/extensions/shortcodes/shortcodes/text-block` to `{your-theme}/framework-customizations/extensions/shortcodes/shortcodes/text-block` after copy , you must edit `options.php` file
```php
$options = array(
	'text' => array(
		'type'   => 'wp-editor',
		'reinit' => true,
		'label'  => __( 'Content', 'fw' ),
		'desc'   => __( 'Enter some content for this texblock', 'fw' )
	)
);
```
If you didn't copy and just edit the `text-block` from unyson, it will works , but on the next update all your custom changes from the unyson will overwrite by update that's why you must copy `text-block` shortcode in your theme `framework-customizations`.If the answer helps you,please close the issue.

**Comment by anoukkolkman** [comment]
Thanks for your answer! 
I hadn’t changed anything, because I didn’t know which part to change. I’ll check it later this week to see if it wil work. 

Thanks again!

**Comment by moldcraft** [comment]
This happens when the `teeny` parameter is `true`.
Try

```php
array(
	'type' => 'wp-editor',
	'reinit' => true,
	'teeny' => false,
)
```
