### ISSUE TITLE
Please help me brainstorm on this one

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#536]
OK , in joomla we have this as a natural choice and the pages model is easy to understand so I am trying to understand this in wp and see if something like it exists. 

in j ,  a page cannot exist without specific ID and that ID is assigned trough the menu. 
So in order for a page  to be visible and accessible you go to you menu , select page type , save and ID gets assigned. ,  

this ID helps us assign specific modules ( in wp this would be a widget like search or RSS, NOT widget poz ) on specific pages. 
http://prntscr.com/73m4dk and each time you make new page , you can see that page in module page assignment option. 

now you sidebar extension does this differently , it assigns a widget position to specific page rather than the widget itself. 

what I am after and need to understand is , is there a specific way to pull ALL existing WP pages in to a single select and do my specific assignment via some  ID or slug?    

in your sidebar you separated this in to groups and specific pages ,  but I would like to have this in a single list like the j  image shown above. 

any help is appreciated!

**Comment by danyj** [comment]
I think I am after this http://prntscr.com/73m99v in a single select

**Comment by moldcraft** [comment]
> in j , a page cannot exist without specific ID

In wp the id is assigned automatically on post creation. (or maybe you are talking about some other "ID")

>  pull ALL existing WP pages in to a single select

I don't think it's a good idea to have all posts in a select. Some (old) sites may have so many posts and the select will be very big (db query will be slow, the options array will be big). That's why we made the multi-select option-type with auto-complete. 
But if only Pages, not all posts, I think those can be not so many and using a select will be ok.

You can use [this function](https://codex.wordpress.org/Template_Tags/get_posts) (and specify post_type page).

**Comment by danyj** [comment]
thnx. yes I noticed that in wp id is auto thus the access is auto granted via ID again , same thing just in j menu controls it. 

I see what you are saying about the pages list  . Will rethink this , 

what I am trying to do is somehow give widgets an option to be assigned to pages , not widget positions. 
In my mind position is just that, a position and it should be available always. it should show itself only if it is populated with a widget. so assignment of a position is kinda irrelevant. 
 Display Widgets  nailed the idea of it http://prntscr.com/73mncj but I dont want another plugin to do a simple logic.

**Comment by danyj** [comment]
@moldcraft  what do you think , could we have something like that in unyson, il gladly pay for the development time. this way I can concentrate on other things and we can have an extended addon for unyson which I am sure others  would like to have

**Comment by llemurya** [comment]
@danyj assigment of a position is relevant ,because If the widget don't have a position where it will be render in the frontend? In WordPress when you create a sidebar area it means you create a widget position, after that you add an widget in this sidebar area. Now if you want an option type, by default in the option is mandatory to specify in what sidebar area it will be render, but the second problem is how to reproduce the add new widget flow with  widget [forms](http://static.md/3e408c39b8ac292d0ce7901ec9116401.png) in the page side.Please describe more concret how you see this feature.

**Comment by danyj** [comment]
yes , your sidebar extension is clear to me and I understand that it makes positions, but it should  do  just that , make the position , not assign it specifically. example 

make sidebar  left and right , done , those should be there and I can use them in my theme

but my page assignment check should be on the widget itself   because I use this to show or hide the sidebar position which I think is completely normal WP process


    if ( is_active_sidebar( 'left' ) ) {



jetpack has Widget Visibility

than you have  list of bunch more plugins that do that 
http://www.wpstarted.com/wordpress-select-widgets-to-show/

but in unyson we do it the other way around, we control the position assignment and I did not see any other plugin do this. Thus I said is irrelevant. Noting against the work here , is just the looks like we mixed up the logic.

**Comment by danyj** [comment]
This should have been an option type that we can use in theme admin to set the layout on all or specific pages 
http://prntscr.com/73y29s
instead of the carp that other themes do like this 
http://prntscr.com/73y35v

this should be in widgets to let us create positions 

http://prntscr.com/73y2fs


this is where page assignment for widgets should be 
http://prntscr.com/73y2qe

**Comment by danyj** [comment]
Il close this issue and open a suggestion to see what other devs think about ihis.
