### ISSUE TITLE
Pagebuilder: Visual Page Builder not active, show content (mostly its shortcodes) in default editor

### ISSUE THREAD

**Issue by ahutatatong** [ThemeFuse/Unyson#553]
Hi there, 

sometimes the Visual Page Builder is not active, but it should be, as it's content is displayed. This happens from time to time. Not often, but actually once is enough to break an existing site (it's still correctly rendered, but changes can't be made, as the switch to the visual editor destroys everything (it's just copied to a textbox. 

Is there a way to tell the Visualb Page Builder to interpret the content corretly or in other words, set the post to a "Visual Page Builder Post". 

great framework! love it!

**Comment by moldcraft** [comment]
A few days back we fixed a bug with post Preview: When the Preview was clicked, that deleted the post meta options and the builder was broken/disabled.

Now the Preview and Revisions works fine.
**Important!** The revisions that were created before the bug was fixed, are "broken" and doing a restore from them will break the builder.

Please make sure you have the latest version of Unyson and extensions (check the WordPress Updates page).
If this problem will happen again, please let us know. (I will leave this issue open for about a month).

**Comment by chloeDT** [comment]
I have the same issues. When I import my database in my wordpress, it broke my page builder and only show shortcodes. What to do?

**Comment by moldcraft** [comment]
Can you give us the steps to reproduce that?

**Comment by chloeDT** [comment]
Well I forget to say that I changed the path of my pictures in textedit. 
I export my database and change the path of my pictures manually (I deleted my local path for another path) and after I import the database in Wordpress. And it shows shortcodes in my pagebuilder.
(Sorry I'm not really good in english)

**Comment by valeriuzdrobau** [comment]
@chloeDT Hi, sorry for the delay, how exactly are you doing import of the database?

**Comment by valeriuzdrobau** [comment]
Due to inactivity I close this issue. Feel free to reopen it at any time.

**Comment by TCQTheConseQuor** [comment]
Hello @valeriuzdrobau , we have almost the same problem.

We moved our wp site from a host to another, we copied the db, the files manually, we replaced the url-s in the db with string replace, and now at some page the visual page builder does not works, just shows shortcodes in the normal editor field.
If we change to visual page builder, it show only one text field, within the whole page's code. See :
http://prntscr.com/arj8ev and http://prntscr.com/arj8nr
Any suggestion?
