### ISSUE TITLE
[suggestion] Detect options change and advise admin to save.

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#577]
We have plenty of options that are ajax, js based ( almost all )  so the user might forget going from tab to tab that the option has been changed and might get frustrated that the setting does not work. 
Can we detect any changes and flash msg to admin that the options need to be saved. 
redux has something like this. http://prntscr.com/77n7dy

**Comment by moldcraft** [comment]
I made this

![s](https://static.md/cbcf83f74dd4aaa313498a6318123944.png)

Please test it.

P.S. Note that [there is a timeout](https://github.com/ThemeFuse/Unyson/commit/3500e2caf636dfc4b2d989fb9838ccab690cc8f7?diff=unified#diff-6ae529d62c26486ad784f55b6940d513R339). If you will change an input and leave the page within 2 seconds, there will be no warning.

**Comment by danyj** [comment]
thnx for looking at this but this should be msg reminder that options are changed , not an alert when leaving options.  
example , I edit option ,   continue working , msg shows that I should save changes , 
your alert should be in place on  attempt to lave the page , but we should also advise admin of a change before he/she attempts to leave.

**Comment by danyj** [comment]
continued from above :  I save , and msg disappears,

**Comment by moldcraft** [comment]
We don't have `position:fixed` elements to place such messages. If I place the messages on top of the form or at the bottom, the user may not see it when he/she is in middle with the scroll.

So I am thinking to not make the reminder msg.

**Comment by danyj** [comment]
ok , how about giving us a hook in the warnOnUnsavedChanges   that we can than use to display msg like 

	$(document).on('settingschanged', function (){ 
	   $('.warchange').show().delay(3000).hide();
	});

**Comment by danyj** [comment]
@moldcraft  updated previous

**Comment by moldcraft** [comment]
Currently there is no change listener. This is how that script works:

* Remember initial form values (after page load finished)
* On pageLeave, compare current form values with initial. If they differ, show alert.

Ok, I will make an event when settings has been changed.

**Comment by danyj** [comment]
I just went trough  it an noticed that , thnx

**Comment by moldcraft** [comment]
```javascript
jQuery(document.body).on('fw:form-delayed-change', 'form', function(event, data){
    console.log(data.hasChanges);
});
```

**Comment by danyj** [comment]
perfect! thank you!

**Comment by duongancol** [comment]
hi @moldcraft : how about confirm alert when shortcode change without save in page builder ?

**Comment by danyj** [comment]
I forgot how much we actually click around while we develop, can we please have on/off switch for developers, or development mode or something.

**Comment by danyj** [comment]
the alert is why I am asking for dev mode, while building option types I must refresh several times and  alert becomes anoying

**Comment by moldcraft** [comment]
I am stuck with a problem. Here is how you can test it:

1. Open Theme Settings page
2. Make sure you have a `wp-editor` option there (better use scratch theme, it has demo options)
3. Run this script in browser console

    ```javascript
    JSON.stringify(jQuery('form[method="post"]').find(':input').serializeArray()).split('<p>').length
    ```

4. Press the Submit button (you must have ajax submit enabled, it is enabled by default)
5. Run again in browser console the script from the step 3.

    You should get a smaller number.

6. Run this script in browser console

    ```javascript
    jQuery(window).on('beforeunload', function(){ return 'Test'; });
    ```

7. Try to leave the page. A warning will appear, click on 'Stay on this page'
8. Run again in browser console the script from the step 3.

    You should get a bigger (initial) number.

----

Instead of number, you can inspect the input values by running this script in the browser console

```javascript
JSON.stringify(jQuery('form[method="post"]').find(':input').serializeArray()).split(',{').join(',\n{')
```

That difference in numbers represents this

![s](http://static.md/4a663de816d5b1a001e33693479df8a6.png)

----

This is the actual problem:

1. Open Theme Settings page
2. The script remembers the form initial values. The `wp-editor` value is with `<p>...</p>`.
3. Don't change anything and press Save
4. After form submit, the script remembers current form value as initial value to prevent alert on page leave, because it compares initalValue with currentValue, if they are different, that means the user made some unsaved changes. Because of the "bug" explained above, the script will remember `wp-editor` value without `<p>...</p>`.
5. The user tries to leave the page, on 'beforeunload' the `wp-editor` value is "magically" again with `<p>...</p>`, the script compares initial value (without `<p>`) with current, they differ, and a warning is displayed.

Again more simplified:
1. Open Theme Settings
2. Press the Save button
3. Try to leave the page, a warning will appear that you have unsaved changes. (your reaction: wtf?!)

----

*P.S. This little script is such a pain, I better spend that time on more important tasks.*

**Comment by danyj** [comment]
I noticed that to, it fires uncontrollably, sometimes  , it also happens on  typography option even if you dont change anything but just click , since the population of selects happened. 
Id say drop the alert for now and leave the event listener. Devs cold still use it until we refine it.

**Comment by moldcraft** [comment]
> Id say drop the alert for now

Thank you. [Done](https://github.com/ThemeFuse/Unyson/commit/55f74485eee014b5ceb1529b3e9747324daf0465)

I [renamed the change event](https://github.com/ThemeFuse/Unyson/blob/55f74485eee014b5ceb1529b3e9747324daf0465/framework/views/backend-settings-form.php#L148) and removed the `hasChanges` data parameter, it has the same issues as described above *(some times it was `true` even if the user changed nothing or set the value back to initial)*.

**Comment by danyj** [comment]
works for me. if i find better solution il post a suggestion
