### ISSUE TITLE
URL Issue when import demo

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#638]
Hi all,

When the site is importing the demo content, it occur below error and then can not change the site URL to the current site, so I can not access the site :

Fatal error: Call to a member function quote() on a non-object in /home/content/p3pnexwpnas09_data01/72/2651472/html/wp-content/plugins/unyson/framework/extensions/backup/includes/lib/srdb.class.php on line 608

Thanks

**Comment by duongancol** [comment]
please check this: https://github.com/ThemeFuse/Unyson/issues/545

**Comment by maiakhoa** [comment]
Hi @duongancol 

Do we have another solution instead of adding a piece of code to the site of clients?

Thanks for quick answer.

**Comment by duongancol** [comment]
i'm not sure but I think @valeriuzdrobau can answer you more detail about this issue.

**Comment by maiakhoa** [comment]
ok thank @duongancol

**Comment by valeriuzdrobau** [comment]
This error appear because the method[ quote()](http://php.net/manual/ro/pdo.quote.php) requires PECL and you do not have it enabled.  Activate extension and try again.
This error comes from a popular class hosted on [github](https://github.com/interconnectit/Search-Replace-DB) for this reason I don't wanted to make changes in it. I'm going to make changes in it and in the next version this problem should disappear.

**Comment by maiakhoa** [comment]
Hi @valeriuzdrobau 

Thanks, hope that it come out soon.

**Comment by valeriuzdrobau** [comment]
Try to update your backup extension up to version 1.0.4 and you tell me if the problem persists.

**Comment by maiakhoa** [comment]
I saw that the commit to fix this issue is not included in 1.0.4

**Comment by maiakhoa** [comment]
Hi @valeriuzdrobau,

Please release new version that included the code to fix this issue soon.

Thanks

**Comment by valeriuzdrobau** [comment]
Fix is present in 1.0.4 release. Please check. Good day!
