### ISSUE TITLE
When using ajaxForms I'm unable to get the submit button from onSuccess

### ISSUE THREAD

**Issue by martin-bede** [ThemeFuse/Unyson#649]
I'm using the forms with `ajaxForms`. Within `onSuccess`, the success message is appended to the form by doing `$(elements.$form).append(html);`.
`$submitButton` is also contained within `elements` but I don't seem to be able to get the actual DOM element like I can with `$form`.

This is the returned data when logging out `$(elements.$form)` and `$(elements.$submitButton)`

![image](https://cloud.githubusercontent.com/assets/4599099/8021332/1b1cd17a-0c93-11e5-9acc-45fbf2d352c8.png)

**Comment by moldcraft** [comment]
I will test it later.

At the moment try to find the button manually

```javascript
elements.$form.find('[type="submit"]')
```

----

Also try to to change [this line](https://github.com/ThemeFuse/Unyson/blob/a2adef26229f5ad1ad015b0b74f657aa59f21235/framework/static/js/fw-form-helpers.js#L98) to

```javascript
var $submitButton = $form.find('[type="submit"]:focus')
```

also try to replace everywhere `input[type="submit"]` with `[type="submit"]`, because in a form ca be `<button type="submit">...</button>`.

**Comment by moldcraft** [comment]
I found [a better way to select the submit button](https://api.jquery.com/submit-selector/) and made [the fix](https://github.com/ThemeFuse/Unyson/commit/e2c9c5458deea5b6121084f7c626616178782138).

Please see if it helps.

**Comment by martin-bede** [comment]
Perfect :+1: 
Cheers!
