### ISSUE TITLE
"Lesson" Module

### ISSUE THREAD

**Issue by ariehwagner** [ThemeFuse/Unyson#720]
1) LESSONS 
I set up a test lesson. 
I set Quiz Passmark Points: 0 (see 2nd screenshot) 
If I answer 3 questions correctly (see 3rd screenshot) - if should say 30 point NOT 30%.

2) LESSONS 
Is there an option to email the result? 
If someone takes the test and wants to know if he passed - I think a great option is if he can submit the Lesson/Quiz by email.

3) LESSON 
only if he passed the quiz he can continue to the next "level". 
is this possible?
![screen shot 2015-07-09 at 16 39 11](https://cloud.githubusercontent.com/assets/13293939/8635736/65e00894-282c-11e5-996a-0b3d821dc0eb.png)
![screen shot 2015-07-09 at 16 45 41](https://cloud.githubusercontent.com/assets/13293939/8635738/65fe1fb4-282c-11e5-99ae-0935be2529ad.png)
![screen shot 2015-07-09 at 16 45 59](https://cloud.githubusercontent.com/assets/13293939/8635737/65fe05c4-282c-11e5-9700-ff8b59414419.png)
![screen shot 2015-07-09 at 16 47 25](https://cloud.githubusercontent.com/assets/13293939/8635740/660434da-282c-11e5-9813-3295ef6b65fe.png)
![screen shot 2015-07-09 at 16 49 17](https://cloud.githubusercontent.com/assets/13293939/8635739/6601c40c-282c-11e5-9a94-13ab54f1378b.png)
![screen shot 2015-07-09 at 16 51 43](https://cloud.githubusercontent.com/assets/13293939/8635741/66104586-282c-11e5-87e5-24d6dd54f8d9.png)

**Comment by GheorgheP** [comment]
Hi,

1. The system is calculating by points, not by percentage.

2. See the [fw_ext_learning_quiz_form_process](http://raw-test.readthedocs.org/en/latest/extension/learning/quiz.html#actions) action.

3. This feature was planned in case will be released the second version of Learning with ability for users to get subscribed on courses. Now this is not done as the users users are not required to log in in order to pass the course. But you can do this simply using cookies and the Learning [Helpers](http://raw-test.readthedocs.org/en/latest/extension/learning/index.html#helpers). In particular you'll need this:
 - [fw_ext_learning_quiz_form_process](http://raw-test.readthedocs.org/en/latest/extension/learning/quiz.html#actions) action - everytime a quiz is submited, save in the client cookies if he passed the quiz or not.
 - ``fw_ext('learning')->is_lesson()`` - to check is the current page is a lesson page, *use only in if did action [wp](https://codex.wordpress.org/Plugin_API/Action_Reference/wp)*.
 - ``fw_ext_learning_get_previous_lesson()`` - to get the previous lesson and check if the user did pass the quiz. And from there you can add a flash message and redirect the user to the previous lesson in order to pass it.

Optionally you can also use the ``fw_ext_learning_get_next_lesson()``, in case the user did pass lesson quiz, to redirect him to the next lesson, or provide link.

**Comment by ariehwagner** [comment]
Thank you. I appreciate you taking the time and helping me.

Re: 1.
I understand its using a point system - but by default it adds a %sign (this is confusing. maybe you can change this?).

Re: second version
Do you have an idea when you will release the 2nd version of Learning?
I like it very much.

Thank you again for your fantastic work.

Arieh Wagner 
DIRECTOR
Starguest Ltd
0208 458 7708
Www.StarGuest.com



On 20 Jul 2015, at 11:12, Gheorghe <notifications@github.com> wrote:

Hi,

The system is calculating by points, not by percentage.

See the fw_ext_learning_quiz_form_process action.

This feature was planned in case will be released the second version of Learning with ability for users to get subscribed on courses. Now this is not done as the users users are not required to log in in order to pass the course. But you can do this simply using cookies and the Learning Helpers. In particular you'll need this:

fw_ext_learning_quiz_form_process action - everytime a quiz is submited, save in the client cookies if he passed the quiz or not.
fw_ext('learning')->is_lesson() - to check is the current page is a lesson page, use only in if did action wp.
fw_ext_learning_get_previous_lesson() - to get the previous lesson and check if the user did pass the quiz. And from there you can add a flash message and redirect the user to the previous lesson in order to pass it.
Optionally you can also use the fw_ext_learning_get_next_lesson(), in case the user did pass lesson quiz, to redirect him to the next lesson, or provide link.

—
Reply to this email directly or view it on GitHub.


This email has been scanned by Netintelligence
http://www.netintelligence.com/email

**Comment by GheorgheP** [comment]
About the second version, I cannot tell anything.

**Comment by ariehwagner** [comment]
Hi GheorgeP,

You wrote: 
The system is calculating by points, not by percentage.

But see above the screen shot - the module is using the "%"- sign.
I suggest you replace it with the word: "points"

have a great day
