### ISSUE TITLE
Add "Reset" button in `popup` option type

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#726]
![](http://static.md/0d69e9c71a99281cf64373ad44baf877.png)

**Comment by duongancol** [comment]
:+1:

**Comment by duongancol** [comment]
Would you give me the code that use to create option in your screenshot?

**Comment by moldcraft** [comment]
Sorry, no. It's a custom theme option type that will be included in ThemeFuse's next theme.

**Comment by danyj** [comment]
@moldcraft   this reset is failing  on and off,  many times it is not resetting the values in popup , 
and to be honest I dont even understand what is it trying to reset them to  since it is definitely not setting the options back to the actual  option values set inside the php files. 

a particular nonworking issue is if you have popup option type in popup option type  ,

so 2 sets of popus ,  the second one is not able to reset itself 
I set you the video to see what I mean

**Comment by moldcraft** [comment]
> I dont even understand what is it trying to reset them to since it is definitely not setting the options back to the actual **option values set inside the php files**.

On reset, values are extracted from modal options default values https://github.com/ThemeFuse/Unyson/blob/v2.5.5/framework/static/js/fw.js#L1067-L1071 There is no connection with php files

**Comment by danyj** [comment]
@moldcraft  , aren't  the default values the actual values set in the php file ?

**Comment by moldcraft** [comment]
php files options array -> enqueue in js -> **modal js options** -> Reset -> get default values from **modal js options** (no php files)

If you are doing some manipulations with modal options then you change default values used on reset.
