### ISSUE TITLE
maximum execution timeout when Import demo content

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#729]
Hi!
My client site get this error when importing demo content.
```
Fatal error: Maximum execution time of 30 seconds exceeded in /home1/micheln5/public_html/wp-content/plugins/unyson/framework/extensions/backup/includes/helpers/class-fw-backup-helper-file-system.php on line 132
```
It still happen when increased maximum timeout of hosting. So please give me the solution! I can give you FTP information if you need.

**Comment by llemurya** [comment]
@duongancol please send the ftp info at  dev-team@unyson.io.

**Comment by duongancol** [comment]
I did, please check it!

**Comment by valeriuzdrobau** [comment]
Hello, I have made import of the demo content. Backup extension on every time when performs importation of the content, make a backup, and includes in it all files of the site. The problem is that, at your client in root of the  WordPress install there are many other files, thus, backup extension exceeds script execution time when it tries to add all files in a zip archive. To be imported to content without making a backup, I commented [this line](https://github.com/ThemeFuse/Unyson-Backup-Extension/blob/master/includes/processes/class-fw-backup-process-auto-install.php#L30). But the best solution is to inform users to not keep other files in the folder where WordPress is installed.

**Comment by duongancol** [comment]
Thank you so much for your time! I'll recommend my client like that.

**Comment by duongancol** [comment]
Other issue of my another theme in client site related to ` sufficient permissions`. 
After importing demo content, I couldn't login to wp-admin. It showed that: http://prntscr.com/7t8dys
I changed permission of wp-content to 755 and added tmp folder manually. But It still didn't work. 
Please give me an solution!

**Comment by valeriuzdrobau** [comment]
Hi, look [here](https://github.com/ThemeFuse/Unyson-Backup-Extension/issues/13).

**Comment by duongancol** [comment]
It works well. Thank @valeriuzdrobau !

**Comment by duongancol** [comment]
Hi @valeriuzdrobau there're a lot of my client get problem with Demo install because of max execution timeout of hosting(30 seconds). I think the backup is helpful but can you add an option to disable it in Content install page. I mean it's not necessary in a site that is fresh install. So when disable backup step. I'll go down timeout loading.

**Comment by valeriuzdrobau** [comment]
Hello, update the backup extension to [1.0.8 version](https://github.com/ThemeFuse/Unyson-Backup-Extension/releases/tag/v1.0.8), should work now. You often encounter this problem because you haven't tried to set this time from your theme. On most servers this is allowed. Now I have added this code in extension.
If you want to create a option to disable the creation of backup copies on install demo content, you can use `fw_ext_backup_do_backup_on_demo_content_install ` filter.
