### ISSUE TITLE
Problem saving slider

### ISSUE THREAD

**Issue by nenadmk** [ThemeFuse/Unyson#741]
I' am having a problem saving sliders. This is the message I get:

Fatal error: Call to a member function get_multimedia_types() on a non-object in D:\Dropbox\www\dunda\wp-content\themes\dunda\framework\extensions\media\extensions\slider\class-fw-extension-slider.php on line 270
[See full image](https://dl.dropboxusercontent.com/u/15585770/error.JPG)

I've tried several times and it happens regardless the type of slider, the population method (automatic or manual)

**Comment by llemurya** [comment]
@nenadmk you have an old version of the slider, because in the last version at line 270 is declared a function , [current version v1.1.10](https://github.com/ThemeFuse/Unyson-Sliders-Extension/blob/master/class-fw-extension-slider.php#L270),but in [v1.1.2](https://github.com/ThemeFuse/Unyson-Sliders-Extension/blob/v1.1.2/class-fw-extension-slider.php#L270) at line 270 is called `get_multimedia_types()` function.Please update the slider extension , see if everything works well and close the issue.

**Comment by nenadmk** [comment]
Yes it looks like that was the case. Update of the extension fixed the problem. Thanks.
