### ISSUE TITLE
Change Mega Menu markup

### ISSUE THREAD

**Issue by janlonden** [ThemeFuse/Unyson#771]
How would I go about changing the mega menu markup?

I tried moldcraft's solution (https://github.com/ThemeFuse/Unyson/issues/79#issuecomment-74970280) to no avail. It might be incompatible with the current version of mega menu?

**Comment by moldcraft** [comment]
[That](https://github.com/ThemeFuse/Unyson/issues/79#issuecomment-74970280) `fw_print('Hello');` is not executed?

Can you tell us what exactly to you want to change?

P.S. [Here](http://manual.unyson.io/en/latest/extension/megamenu/index.html#changing-item-icon-markup) is how to change link markup

**Comment by janlonden** [comment]
That's correct, fw_print('Hello'); is not executed.

We'd like to add a specific class to every column depending upon how many columns the row with the most columns has.

Let's say we have a maximum of 4 columns. Then all the columns would get a "fw-col-sm-3" class.

**Comment by moldcraft** [comment]
[It's executed](https://static.md/9cc7d9b25acf02e4319b1eac00e5eece.png) when the menu has [second level](https://static.md/1d4d824b84d91c95f72c6b11eef11611.png).

> Let's say we have a maximum of 4 columns. Then all the columns would get a "fw-col-sm-3" class.

I can't tell a solution because I am not familiar menu walker.

Please learn about [menu walker](https://codex.wordpress.org/Class_Reference/Walker) and inspect [mega-menu walker](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/includes/class-fw-ext-mega-menu-walker.php).

**Comment by janlonden** [comment]
Well, the menu has 3 levels, but it still won't execute.

I'll take care of the menu walker, if I could just get the extended class and add_filter to work.

I did the steps exactly as you described in your [comment](https://github.com/ThemeFuse/Unyson/issues/79#issuecomment-74970280). Any idea what the problem could be?

**Comment by moldcraft** [comment]
I did the same (created those 2 files). I don't know, add some `fw_print('Debug');` to detect where the execution stops.
