### ISSUE TITLE
Switching editors should not change page builder contents

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#783]
I might be on your bug that is making content disappear which just happened here  #782 

Setup page builder elements , hit preview you will see them 
Save the page, 
Hit  default editor button , hit preview and everything is gone,

This should not happened at all ,  switching between editors should not change the page content 
and now browsing trough all existing top page builders like the ones from avada , enfold and  VC, 
they have same setup but they add their short-codes directly in to editor so switching between them makes no difference, the content stays. 

This is what our page builder does  
http://screencast.com/t/dTXbtdHfU

These are avada and enfold 

http://screencast.com/t/8HwwD6Bn

**Comment by duongancol** [comment]
:+1:

**Comment by Alex-Ascet** [comment]
+1

**Comment by thednp** [comment]
+1

**Comment by maiakhoa** [comment]
+1

**Comment by moldcraft** [comment]
We can't do that because WordPress will change/break/corrupt shortcode attribute values that contains encoded json (like table or form shortcode, that stores big complicated json data in attributes).

[Here](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/f2d1dbf534192bf4534fa73f3f7c9917d5f5ea8a/class-fw-extension-page-builder.php#L200-L227) we remove revisions that contains duplicate/corrupt content.

To prove that, here is how you can test:

* After [this line](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/70e5842692e3fb4eadcc81143e328a0d9468c996/includes/fw-option-type-page-builder/static/js/editor_integration.js#L30) add `return;` (this will disable default builder clear)
* Edit a page *(Ctr+R to make sure the js is not loaded from browser cache)*, add **Table** or **Form** shortcode (better both)
* Save the page
* View it on frontend to make sure it works

&nbsp;

* Open phpMyAdmin `wp_posts` table
* Search that page by id (`/wp-admin/post.php?post={ID}`)
* Copy `post_content` and paste it in the left textarea on http://text-compare.com/

&nbsp;

* Switch to **Default editor**
* Save the page
* View it on frontend (it will not work)

&nbsp;

* Copy the shortcodes from default editor and paste in the right textarea on http://text-compare.com/
* Press the **Compare** button on http://text-compare.com/

----

Also there is no way to convert `[shortcode notation="..."]` to `[{builder:'elements', ...}]` because it works only in one direction:

```
(backbonejs builder elements json) ---> (wordpress shortcode notation)
```

I think users will start to request that, saying that they spent a lot of time building their pages with shortcodes and now they want to switch to page-builder (and all shortcodes should be displayed as builder elements)

----

The idea is that with page-builder you create fancy pages. With default editor, simple content (blog).

With other builders (that do not clear the default editor), in practice, are you using both visual builder and default editor while creating the content (switching frequently between them), or this request/issue is just a notice that from the technical point of view, how our builder works, doesn't look good?

**Comment by danyj** [comment]
It was from technical point of view since we can see the actual shortcode, but now that you say this 
> The idea is that with page-builder you create fancy pages. With default editor, simple content (blog).

kinda makes sense
