### ISSUE TITLE
[we are waiting for your opinions and suggestions] Suggest users to make backups before updates.

### ISSUE THREAD

**Issue by valeriuzdrobau** [ThemeFuse/Unyson#785]
Often after updates of the theme or of the plugins, occur problems and users are outraged and would like to return to what they had before the update, because of this we believe that we must put some notices in dashboard to suggest users to install and configure backup extension so that it automatically do a backup at some time (the interval one to be chosen by the user).
    And before each update, the themes or plugins, if not created to be a backup in the last 24 hours (this time it will be possible to change through a filter) to suggest a user to make a backup as then return to make the desired updates. However for developers working on local projects that construct themes or plugins or for developers who do not want these backups or use another backup plugins will be possible to stop these notifications.

**Comment by danyj** [comment]
This is not a bad idea but it must be optional. A little push from a notification is how I see this , 
like Woo does  http://prntscr.com/81v1ab,  but in no way should this be done automatically on install. 

So on unyson install show a notification with opt out button,  that will urge users to turn on auto backups.

**Comment by alexluncashu** [comment]
If we'll add a simple notice to backup the website before update users will ignore it. They want to get everything done quickly and don't pay attention to notices or lose time to read those. This may generate problems, as when you update, you may lose everything and no one can help you to restore your work, and because of it client become frustrated. We can add a notice, and also force the client to backup and after it, we check that the backup if finished, we allow the update. In this case we will teach the clients to always take backups before update and solve a big issue with not losing the work done. If you're a developer and have another backup plugin, you can add a config file from where this notice can be deactivated but that need to be done on your own risks.

**Comment by Creative-Dreams** [comment]
I am totally agree with Alexandru, user could simply ignore the notification. I will rather be for adding an option (to be used before updating something) so the user could chose from:

a) automatic backup - this will make a backup before something is updated (without the user to know).
b) regular backup - user should go by itself and click the backup button and after the process is done, he will go and update what he needs - but this is a more time consuming process :)

**Comment by andreiglingeanu** [comment]
Maybe, it will be smarter just to give developers tools to do this, in a very simple manner for them? In this case you leave responsibility to them, and this should be specified in docs. At the end of the day, Unyson position itself as a framework for developers, not as a end-user ready product. Again, this should be specified in manuals with bold text.

**Comment by alexluncashu** [comment]
They don't read docs. I can say "is user fault", but, if they lose content, user had a problem, and I to. Because you can't guarantee 100% that new update won't break something. In this case, you secure yourself, that if something goes wrong, you have a backup.

**Comment by Creative-Dreams** [comment]
Yep, that's why I was telling that it would be cool to have those options.
If you chose the "automatic backup" - the user and you (the developer) could forget about the problems.
If you chose the "regular backup" - this will also not guarantee that the user will use this feature or maybe will forget to use it before updating something.

So in my opinion "automatic backup before updating something" will be the best solution.
What do you think?

**Comment by valeriuzdrobau** [comment]
I would prefer "regular backup", they must get used to the idea that need to be responsible and make a reserve copy, will be an alert so that he will not forget to backup. If the process will be automatically, her one forget that it creates a backup and  will not know how to use it in those rare cases when this copy will be required to restore the site. Some of them will be unhappy as the update takes too long, but actually the time will be consumed for creating a reserve copy.

**Comment by danyj** [comment]
We cant force a backup on users and we cant rely on the backup either.  So all of this must be optional not forced. Sure flash it in front of user to do it or add checked check box with big red letters next to update Unyson button. http://prntscr.com/81wx2g

We have so many background processes in unyson that we cant catch the actual issues like loosing content or builder combining everything in one box, adding another one can cause issues. 

Look at this , https://github.com/ThemeFuse/Unyson/issues/492 a bug since April that is still not fixed and backup is actual demo install so far I see this. So we might end up loosing more things with auto backup. 

I am for backup but only optional, not forced and not running in backend without user knowing about it.

**Comment by duongancol** [comment]
I agree with backup is an optional.
