### ISSUE TITLE
How to disable all shortcodes in content tab ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#805]
Hello @moldcraft 

I want to disable all shortcodes from content tab. And move contact form shortcode to new custom shortcodes tab.

I am using this function to disable the shortcodes but some are hide and others are not.
function disable_default_shortcodes($to_disable)
{
    $to_disable[] = 'call-to-action';
    $to_disable[] = 'divider';
    $to_disable[] = 'icon';
    $to_disable[] = 'map';
    $to_disable[] = 'notification';
    $to_disable[] = 'special-heading';
    $to_disable[] = 'table';
    $to_disable[] = 'textblock';
    $to_disable[] = 'widge-tarea';
    $to_disable[] = 'media-image';
    $to_disable[] = 'media-video';
    return $to_disable;
}
add_filter('fw_ext_shortcodes_disable_shortcodes', 'disable_default_shortcodes');

These shortcodes are not disabled using this hook.

And also i want to know how to move the contact form shortode to other tab.

Thanks

**Comment by wpthemes786** [comment]
Hello @moldcraft 
I am waiting for your reply

**Comment by moldcraft** [comment]
Hello @wpthemes786 

I don't know the answer for this. We didn't made the possibility to move shortcodes between tabs.

So at the moment, the answer is: You can't.

P.S. Instead of `$to_disable[] = 'media-video';` try `$to_disable[] = 'media_video';` (with underscore. I haven't tested this, so not sure if this will help)

I will take a look at this issue later. Right now I am busy with [this issue]()

**Comment by wpthemes786** [comment]
@moldcraft  Ok Thanks

**Comment by PavelEfimenko** [comment]
Hello guys @moldcraft @wpthemes786 
Im tested this issues and really problem in the dash, if use underscore shortcodes disable.
