### ISSUE TITLE
Two Update buttons

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#810]
Is this Update button normal?

![image](https://cloud.githubusercontent.com/assets/1108563/9380204/59f6534c-4737-11e5-9c65-a26764050387.png)

**Comment by moldcraft** [comment]
Yes. It's convenient when the builder becoms big and you don't have to scroll up for the post save button. Also this button will recover page scroll after refresh.

**Comment by danyj** [comment]
true , what is the point of the second update button ?

**Comment by moldcraft** [comment]
I can't reproduce that button position https://vid.me/cbgh

----

The advantages of the second Update button:

* When you built a big page with builder elements, you don't have to scroll up to press Update (because the builder header is fixed and follows you while you scroll)
* After you pressed the Update button and the page was refreshed, you don't have to scroll back down, the page scroll will be restored at the position where you pressed that second Update button

**Comment by danyj** [comment]
@moldcraft   thnx for the info , than we ned preview button also there since we still have to scroll up to preview the page
