### ISSUE TITLE
Shared Options for shortcodes

### ISSUE THREAD

**Issue by c0sm1n87** [ThemeFuse/Unyson#841]
Hello,

I tried searching the issues but I couldn't find what I'm looking for. I am trying to create some options that will be shared across shortcodes. For example I create margins-top,bottom / padding-top,bottom which I don't want to copy paste in X Number of options.php but maybe include it somehow like I can do with the page options  ( fw()->theme->get_options( 'something' ); )
Point me in the right direction :)

**Comment by moldcraft** [comment]
Hi,

If there are few simple options, create a function that returns that array with options, and use it where you need them (instead of copy/paste the actual options). So you will have a central place to edit them (like with `fw()->theme->get_options( 'something' );`).

If there are a bit advanced and need custom positioning, [create an option type](http://manual.unyson.io/en/latest/options/create-option-type.html#content).
