### ISSUE TITLE
Unyson Shortcodes Probelm ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#857]
Hello @moldcraft @llemurya 

I have a map shortcode which is unyson builtin shortcode. and i have a metabox in page which is as a textarea metabox. when i copy the shortcode from editor as a text mode and copy it into textarea metabox the shortcode is not render. And then i put the same shortcode in wp editor the shortcode is rendered.

Any help would be much appreciated.

Many Regards.

**Comment by moldcraft** [comment]
> the shortcode from editor as a text

Can you give us that text so we can test it?

**Comment by wpthemes786** [comment]
[google_map fw_shortcode_id="1"]

This is the Map Shortcode. Just put this code in metabox textarea.

Thanks

**Comment by moldcraft** [comment]
> [google_map fw_shortcode_id="1"]

This is not a page-builder shortcode, it's a [editor-shortcodes](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/tree/master/extensions/editor-shortcodes) shortcode. It has a tricky save mechanism, it doesn't store shortcode data in attributes, but it stores the data in post meta and in `fw_shortcode_id="1"` it stores the id of that data. I am not sure why it was created like that (because I didn't made that extension) but most likely it was because of [this problem](https://github.com/ThemeFuse/Unyson/issues/783#issuecomment-137479345).

So, you can't use [editor-shortcodes](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/tree/master/extensions/editor-shortcodes) shortcodes standalone.
