### ISSUE TITLE
Few questions about icon option?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#871]
@moldcraft  I know you mentioned that icon option is going to change or you are considering new one ,  now the icon shortcode has no sizes or color option and I am about to do it. Questions are 

do unyson icons have size utility like  small, medium , large ? 
Is your "new" icon option going to implement sizes or anything else that I need to know?

**Comment by moldcraft** [comment]
> now the icon shortcode has no sizes or color option

We will not add new options in default shortcodes, because some themes maybe are using default options and customized only the view. If we add a new option, the view will not use it and the client will be confused that that option has no effect in frontend.

----

size **utility**?

----

> Is your "new" icon option going to implement sizes or anything else that I need to know?

No, there will be no options related to size, only icon.

**Comment by danyj** [comment]
yes , like   fa ,  fa-2x  fa-3x
https://fortawesome.github.io/Font-Awesome/examples/

**Comment by moldcraft** [comment]
Some font-icons has such utilities, others not (like unycon)

I don't know, when I will start `icon-v2` I will consider this and maybe there will be custom options depending on font-icon. But color sure will not be there.

*P.S. I don't know when I will start working on `icon-v2`. For e.g. now there are some critical bugs in Backup extension, I need to study it and figure out how to fix them (I don't know how much time it will take)*

**Comment by danyj** [comment]
ok than I do my own thing on this one. thnx for the info . I just did not want to do double job in case you were on it.
