### ISSUE TITLE
Array setup help needed

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#899]
I am having huge issue with setting up an array and need some hints if possible 

I am working on icon-box shortcode ,  it should have 5 styles 
for each style I need to set  7  icon options  2 of them multi-picker ,  
5 icon shape background options 3 of them multipicker 

just by looking at this you understand that this is a huge array , about 400 lines for each style and I did not even include options for read more button , 

I cant make an option type out of this since again it is huge , multi-picker logic does not gives me to many options so I am stuck by including   5x 400 lines. It is crazy. 

This is kinda like VC   icon-box  http://prntscr.com/8mbtbu

Do you have any suggestion on how to accomplish this ?

I wish we could do an array change with multi-picker like  global array template and than per select defaults for each template option instead of writing up this whole thing over and over. 

Not only that is crazy to do it but the markup for multi becomes huge , now imagine just adding 3 icon boxes in builder , it is beginning to stutter already. 

Any suggestion is greatly appreciated

**Comment by danyj** [comment]
I am trying to do this, but will likely run in to trouble when defaults are changed 


'style1' => array(
	'text' => __('Style 1', 'creatus'),
	'attr' => array(
		'data-iconsize' => '72',
		'data-iconposition' => 'leftheading',
		'data-shapeactive' => 'active',
		'data-shapesize' => '120',
		'data-bgtype' => 'solid',
		'data-hovereffect' => 'active',
		'data-effect' => 'spin'
	),

	(function($, fwe) {
	
	
		fwe.on('fw:options:init', function(data) {
			
			$('#fw-edit-options-modal-style-picked').on('change',function(){
				
				
				
				var $option 		= $(this).find(':selected');
				if($option.hasClass('styleset')) return;
				
				var $iconsize 		= $($option).attr('data-iconsize');
				var $iconposition 	= $($option).attr('data-iconposition');
				var $shapeactive 	= $($option).attr('data-shapeactive');
				var $shapesize 		= $($option).attr('data-shapesize');
				var $bgtype 		= $($option).attr('data-bgtype');
				var $hovereffect 	= $($option).attr('data-hovereffect');
				var $effect 		= $($option).attr('data-effect');
				
				//fw-edit-options-modal-icon_shape-picked console.log($iconsize);
				
				$('#fw-edit-options-modal-size').val($iconsize).trigger('change');
				$('#fw-edit-options-modal-icon_position').val($iconposition).trigger('change');
				$('#fw-edit-options-modal-icon_shape-picked').find('input').val($shapeactive).trigger('click');
				
				setTimeout(function() {
					$('#fw-edit-options-modal-icon_shape-active-size').val($shapesize).trigger('change');
					$('#fw-edit-options-modal-icon_shape-active-bg_type-picked').val($bgtype).trigger('change');
					$('#fw-edit-options-modal-icon_shape-active-hover_effect-picked').find('input').val($hovereffect).trigger('click');
					$('#fw-edit-options-modal-icon_shape-active-hover_effect-active-effect-picked').val($effect).trigger('change');
					
					
				},500);
	
				setTimeout(function() {
					$option.addClass('styleset');
				},1000);
			});
	
					 
		});
	
	})(jQuery, fwEvents);


any suggestion is welcome.

**Comment by moldcraft** [comment]
Want to notice a "bug" in your js

```js
fwe.on('fw:options:init', function(data) {
    $('#fw-edit-options-modal-style-picked').on(...);
```

should be

```js
fwe.on('fw:options:init', function(data) {
    data.$elements.find('#fw-edit-options-modal-style-picked:not(.initialized)').on(...).addClass('initialized');
```

----

We will try to answer later. Right now we have the same problem, theme shortcodes contains so many options that when you add a lot of shortcodes in builder, on post save we get mysql error because the post meta `UPDATE` query is too big

```
WordPress database error: [Got a packet bigger than 'max_allowed_packet' bytes]
UPDATE `wp_postmeta`
```

----

> I wish we could do an array change with multi-picker like global array template and than per select defaults for each template option instead of writing up this whole thing over and over.

Can you give an example?

**Comment by moldcraft** [comment]
Sorry, I don't know the answer. If we knew, we would improve it already.

----

About that mysql error, I will try to save builder array value in separate meta. Right now it is saving

```
array(
    'json' => '[...]',
    'corrected_json' => '[...]',
    'shortcode_notation' => '...'
)
```

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/1983f2cc540204feb12ea96bc675f6cd17a8750f/includes/page-builder/class-fw-option-type-page-builder.php#L165-L166

in the same post meta together with all post/page options.

We thought that in post meta or wp option you can save huge amounts of data, but unfortunately you can't because of that mysql limit. So in some places we will need to fix (add hacks) to split data in multiple post meta or wp options, but also to continue to work with old/existing (already saved) data.

This is related to [this unfinished feature](https://github.com/ThemeFuse/Unyson/blob/5777e3a853d2e4231df7c5f7078434f69c636333/framework/core/components/backend.php#L761-L766) and [this](https://github.com/ThemeFuse/Unyson/issues/838).

**Comment by danyj** [comment]
>Can you give an example?

gladly , this is my idea  #901

**Comment by danyj** [comment]
Thnx for the JS suggestion.  I did not know about that sql limit issue but is nice to know now and I must than stop and rethink those arrays in order to continue. 

Like suggested in #901 multi-picker should not be used for same array sets , we need something else instead that would only switch the option values instead making us  rewrite the arrays over and over. Multi-picker is ok for up to 3,4 simple options, or for a set off different options per selection but bigger than that it gets heavy.

**Comment by danyj** [comment]
I will close this for now  and we can continue thinking over at #901
