### ISSUE TITLE
How to change popup option values via JS

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#902]
Sorry for those little ones but I am trying to work on #901  and I can get to change almost all options via JS  on click/change except  the popup option type , it seems like it is pulling data from somewhere else rather than from the input value 

The value is json, so when I do 

	$('input#someid').val('newjsonvalue');

I do see the value changed in the input and I also change the data-for-js attribute , but when I open the popup it does not look for those values but it loads the default ones. 

I do see that they are called but 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/popup/static/js/popup.js#L14

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/popup/static/js/popup.js#L33

but is there something else I need to change ?

**Comment by moldcraft** [comment]
On option init, it is created a fw.OptionsModal instance with options and options values from data-for-js attribute. On modal options change, the input is updated with values from OptionsModal, so changing input value has no effect because modal store in its instance the values.

Currently there is no way to access that modal instance and update its `values` property.

**Comment by danyj** [comment]
ok , got it , I thought I am going nuts , here , value returns as the one I set but that internal is using own
