### ISSUE TITLE
Translation Extension deletes all pages

### ISSUE THREAD

**Issue by mikymoto** [ThemeFuse/Unyson#916]
Hi, We have the site developed in one language working great. The moment we install the translation extension all pages dissapear. Then we add all pages from backup again but we are not sure what we are doing wrong installing the extension.

**Comment by llemurya** [comment]
@mikymoto you must set to ` true` the Convert Data switch option type in translation settings, because the default is set to `false` and all the pages that was created before you installed the translation extensions were hidden by our extension.Please see this [printscreen](https://static.md/9a3edb3e6054cd26d259190ae7100be5.png), enable this option and save the settings and all your pages will be converted in the default language.Please give us a feedback if this answer helped you.
