### ISSUE TITLE
How to get Unyson based themes approved by Theme Forest reviewers?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#948]
This post is made in light of latest issues we ( anyone using Unyson ) have approving our themes on TF. 
Some of our  fellow coders made it on TF and had no issues or we dont know about them, where others have serious problems and cant get their themes approved. 

@WPJobs  https://github.com/ThemeFuse/Unyson/issues/937#issuecomment-148519676

@pe6o https://github.com/ThemeFuse/Unyson/issues/937#issuecomment-148964653

Here are the lucky ones, http://themeforest.net/attributes/framework/unyson  ( don't forget to add encouraging comment for a fellow coder ) 

Can the "lucky ones"  please help us here and advise what should and should not be done. 
This is a great issue that concerns us all so we should all stick together if we want to see Unyson thrive.

We all know that coding and design plays major role in approval process, but in this case we are talking strictly about the Unyson framework issues. 

Please pitch in so that others dont make same mistakes.

**Comment by 2Fwebd** [comment]
Hi there, 

Well, I'm one of the guy behind Woffice : themeforest.net/item/woffice-intranetextranet-wordpress-theme/11671924 and all the theme is based on Unyson,* all of the features are built with extensions*. 

We plan to share all our extensions for free in the next weeks but I need to setup a blog first. But it's coming!

I didn't get any issue to have the theme approved regarding Unyson features. The only stupid thing is that you can't register post types directly from Unyson extensions on the first upload as it's not allowed by Themeforest. You need to have your theme approved a first time, then you can move them from your custom plugin to an extension which is way easier for everyone ! ;)

In that project, as you can see in the extensions list : alka-web.com/woffice-theme/ we've developed many extensions and most of them can be moved to any other Unyson theme, that's why I'll share them soon !

**Comment by danyj** [comment]
@2Fwebd  Thank you bud, can you advise if you have used all Unyson features like demo installs , auto installs and if you had issues escaping title,description,desc,help values

**Comment by WPJobs** [comment]
Thanks for creating this topic!

I can advice 3 things:

1)  Follow these requirements https://help.market.envato.com/hc/en-us/articles/202822450-WordPress-Theme-Submission-Requirements

2) Check yout theme with ThemeCheck plugin, it is mandatory! https://wordpress.org/plugins/theme-check/

3) Check HTML code that theme outputs with https://validator.w3.org/

4) Check your theme with Theme Unit Test https://codex.wordpress.org/Theme_Unit_Test, and if your theme supports WooCommerce https://docs.woothemes.com/document/importing-woocommerce-dummy-data/

**Comment by duongancol** [comment]
I agree with @WPJobs , but in step 2, you should also install Themeforest check plugin. It will ignore some requirements that 're only need in wordpress.org.
I also don't have much issues with reviewer.For escaping issue, just escape all string and output: https://developer.wordpress.org/themes/functionality/internationalization/#escaping-strings

**Comment by c0sm1n87** [comment]
so, do we escape everything or still waiting for answer ?:P

Also, I would like to ask a question regarding the Themecheck / TF plugin. I use a LESS compiler library to generate new CSS files which generates 4 warnings (because it uses @ini_set and apparently, it's not supported :) )

Another question would be about the register_post_type which raises another error, any thoughts? 

At the current moment I am still working at code quality, cleanups and documentation so it might take a while to submit it so if you have any suggestions please let me know. Also, if anyone is kind enough to take a quick look over it, I would appreciate it alot :)

**Comment by duongancol** [comment]
what compiler do you use to generate LESS file?
For register_post_type, you should seperate it to a plugin.

**Comment by c0sm1n87** [comment]
I use this library : http://lessphp.gpeasy.com/

**Comment by c0sm1n87** [comment]
@danyj @duongancol @WPJobs  any thoughts on this? :)

PS: I don't want to bloat the theme with plugins and I prefer to do it myself.. at least if I screw up, It's my fault :P

**Comment by WPJobs** [comment]
@c0sm1n87 in my themes i compile LESS files using WinLESS on a client side (directly in a browser), and then save compiled styles into file, this gives a much more opportunities than PHPLess, this library has a very stripped-down functionality

**Comment by danyj** [comment]
@c0sm1n87 I have been using that lib for a long time now https://github.com/YJSGframework/yjsg/tree/master/includes/yjsgcore/classes/less.php and worked wonder on Joomla but I did not get to the incorporation in WP and I think we will have big issues , not because of TF but because of 

    define('FS_METHOD', 'ftpext');

as for TF check  not passing , il take a closer look  and reply in few days

**Comment by c0sm1n87** [comment]
@danyj In Joomla! i use the library I mentioned, however the Joomla! themes i work on don't have to pass TF checks and I had absolutely no problem with the library (to the extent that I'm using). 

@WPJobs for what I need it to do does handle pretty well. also, this plugin was built on this library:

https://wordpress.org/plugins/lessphp/

however, I would prefer not to use a plugin for this :)

**Comment by c0sm1n87** [comment]
I don't follow every post so I am a bit behind, did TF answer your question regarding the escaping of the translatable strings?

**Comment by danyj** [comment]
no , they did not answer
https://forums.envato.com/t/output-sanitizing-issue-we-need-theme-reviewers-input-please-advise/11854/2

**Comment by pe6o** [comment]
Always, always leave message to the reviewer that the **auto-install** directory is for the Unyson 1-Click Install and that the Demo Install is not mandatory for the users and despite it's name it's not auto installed when the theme is activated.

**Comment by WPJobs** [comment]
@pe6o thank you for your feedback regarding this

**Comment by c0sm1n87** [comment]
I don't understand why the posts from Themezly were flagged and now are hidden :)

**Comment by danyj** [comment]
@2Fwebd  because I added links to Unyson git

**Comment by danyj** [comment]
@moldcraft  should handle that question 
https://forums.envato.com/t/output-sanitizing-issue-we-need-theme-reviewers-input-please-advise/11854/2
since it is Unyson related and we all need an answer. Best bet is to ask the reviewer that has approved Unyson ,

**Comment by c0sm1n87** [comment]
at the current moment I am trying to find a way to insert the less compiler without themecheck raising errors so I can submit it for review. I don't know if I should start escaping the hell out of the __(..) or leave them as how they are now.

I guess I will submit it one of these days without escaping and I will keep you updated with the reviewer answer (if it's not hard reject :+1: )

**Comment by danyj** [comment]
Useful info in ref to demo installs 
https://github.com/ThemeFuse/Unyson/issues/882#issuecomment-154907637

**Comment by moldcraft** [comment]
Envato checks if your theme follows these prefix rules http://themereview.co/prefix-all-the-things/

I don't agree with those rules. If you build a theme with `{theme-name}_...` prefixes, it is very inconvenient to use that theme as a base to create a new theme, you will need to do a lot of replaces.

With [our prefix](http://manual.unyson.io/en/latest/convention/prefixes.html#theme) `fw_theme_` it's easier to use a base theme (for e.g. Scratch Theme) and start to modify it or use pieces of code from it without doing a lot of replace. *Of course you can do a "Replace All" from editor, but you'll need to check everything to make sure there are not unwanted replaces.*

The main reason behind prefixes is to prevent conflicts, but what's the point to use theme slug in prefix because only one theme can be active, so if you will have in all your themes a function called `fw_theme_hello()`, it's impossible to have 2 included at the same time.

I think they should think a general prefix (like our `fw_theme_`) and promote it, for e.g. `wpt_`, abbr of `WordPressTheme`, very short and easy to write (without underscores, the letters are on the same line on keyboard)

What do you thing about those two approaches? Pros & Cons

**Comment by danyj** [comment]
@moldcraft   that is nuts.  I prefix with my website initials , for eaxmple in our jooma framework I prefixed 

    yjsg_

in  WP and our new site being themezly I prefix 

    thz_ 

so it is crazy to prefix by theme name since if you are creating one theme that should be base theme for others than you would have to redo the same crap all over again.

**Comment by danyj** [comment]
I asked on their post and got very short answer without any clear explanation. 
http://prntscr.com/9c6vzf

When looking at TF guideline it is clear that we should use unique prefix , but it does not say anywhere that we MUST use theme name 
http://prntscr.com/9c6vst
https://help.market.envato.com/hc/en-us/articles/202822450-WordPress-Theme-Submission-Requirements

@moldcraft  so I am not sure where you got the info that TF is  folowing guidelines from themereview or why we must use theme name as prefixes.

**Comment by moldcraft** [comment]
They soft rejected our theme because of prefixes and said that we must follow these rules http://themereview.co/prefix-all-the-things/

**Comment by danyj** [comment]
@moldcraft  that is simply not right. becuase 2 guys say so and nowhere in the requirements is written they get to do what they like. WRONG on all levels.

**Comment by danyj** [comment]
@moldcraft  what was your prefix?   

I mean when X theme can use 

    x_icon_portfolio_tags

than what else can be said about that

**Comment by moldcraft** [comment]
`fw_theme_...` like in our docs. 

Now we renamed everything to `the_core_...`, not a big deal, we just want to be accepted faster on TF, so at the moment we just do everything they say. 

Later, I hope, we will find a response about the prefixes: why they think our initial prefix is bad.

**Comment by danyj** [comment]
ok , keep us updated and best of luck !

**Comment by pe6o** [comment]
I prefix with **ssd_** which are my themeforest initials. It seems like it **really, really** depends on ohe reviewer one lands :\

**Comment by danyj** [comment]
@pe6o  thnx bud that is useful info ,  it just makes no sense at all to be forced to prefix with theme name

**Comment by pe6o** [comment]
Yes it kills any re-usability. Although the localization domain must be the theme name. 

At least it's easy to find and replace all the instances when creating a new theme.

**Comment by azharijelek** [comment]
My Themeforest items are using Unyson since 2015 until now. And I'm happy with it. 

just check out my profile there: themeforest.net/user/juarathemes

**Comment by danyj** [comment]
@azharijelek @moldcraft  this is not self promotion thread , it is thread where we should help each other in TF approval process.

**Comment by moldcraft** [comment]
*link deleted*

**Comment by moldcraft** [comment]
We made a form to collect feedback about your Unyson experience https://kate282.typeform.com/to/GC8AUt

**Comment by moldcraft** [comment]
Hi dear Unyson users,

We want to make several improvements and need your opinion over them. This is why we will highly appreciate your feedback about your interactions with it. Please complete the following form with your opinion over Unyson experience:

https://kate282.typeform.com/to/GC8AUt

Your feedback will help us make significant improvements to the framework. 

Thank you once again for being an important member of the Unyson community! We intend to keep building its progress together with you and deliver you more benefits.

**Comment by danyj** [comment]
@moldcraft  done ,  but I think new thread with catchy heading would be better to get all devs to participate.

**Comment by azharijelek** [comment]
@danyj @moldcraft my apologize. I'm Sorry for that.

**Comment by moldcraft** [comment]
* TF do not allow framework to be built-in theme and require it to be as plugin
* WordPress don't allow frameworks in plugin repository http://wptavern.com/the-wordpress-plugin-directory-will-no-longer-accept-frameworks

![](https://static.md/d76b534977e02576c567f20c5fac7568.png)

**Comment by 2Fwebd** [comment]
This is so stupid ...

**Comment by duongancol** [comment]
quite not understand, how about Unyson framework?

**Comment by moldcraft** [comment]
Unyson is not affected, the existing (already accepted) plugins will not be affected, they will not accept new framework plugins that will be submitted to wordpress.org

**Comment by danyj** [comment]
Has any one used 

    include(locate_template('template_name.php'));


in your theme? Do you know if it is safe to use it?
I am passing theme check fine and need to use this in order to pass variables to templates. 
Not getting answers here https://forums.envato.com/t/can-we-use-include-locate-template-to-include-templates/40897

**Comment by duongancol** [comment]
not sure about this but I usually use [get_template_part()](https://developer.wordpress.org/reference/functions/get_template_part/)

**Comment by ivandotv** [comment]
What about "output buffering" 
Theme check issues a warning about that.
```
//		@ini_set( 'output_buffering', 'on' );
```

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Theme-Includes/issues/1

**Comment by Ataurr** [comment]
Rich added some notes for approved wp theme on themeforest.
http://richtabor.com/themeforest-tips/

**Comment by 2Fwebd** [comment]
Yes, also note there was a few changes in TF review process. Impacting directly Unyson authors... We can't no longer use the `'force_activation'` param from the TGM class. 

Also, you've to make sure your theme can be activated without Unyson and won't throw ANY error or warnings... It should even work on the frontend without Unyson. Which is very stupid for the a framework plugin and right for any other plugin... 

What we've done for Woffice is to call a function in the `header.php` file which displays a full screen message saying that you MUST enable Unyson in order to get this theme to work. Actually, it's only for TF reviewers (pretty much) as they're the only one to enable just the theme and not the plugin. Any customer click on the TGM class. We can share it if you're interested. 

I'm just saying this because our last update has been rejected twice about those points. And you'll be rejected for any new item that doesn't respect those rules (as stupid as they're for frameworks) according to TF reviewers.

**Comment by danyj** [comment]
@2Fwebd 
> you've to make sure your theme can be activated without Unyson and won't throw ANY error or warnings..

that has been known since long time and yes your theme must work without Unyson.  Wont have any options to change but it wont mess users websites up either.

**Comment by Ataurr** [comment]
I think They just check Blog design working properly without error or broken. they dont check main theme design work fine without plugin.

**Comment by 2Fwebd** [comment]
I'm just saying this because that's the first time we have issues about that on a theme *update*. I

**Comment by Ataurr** [comment]
Some validation check added for themeforest WordPress theme.

https://github.com/Ataurr/Theme-Mentor-For-Themeforest/

**Comment by danyj** [comment]
@Ataurr  not bad but do you have to escape the functions outputs? 

for example this is inside a function



	if($echo){
		
		echo $html;
		
	}else{
		
		return $html;
		
	}

**Comment by Ataurr** [comment]
Just check "echo $"  with the regular expression. If found anything print details with line no. 
Reviewer also check the same thing with global search

**Comment by danyj** [comment]
> Just check "echo $" with the regular expression. If found anything print details with line no.

not sure I understand what you mean. Question is do we have to escape the output within functions. 
As far as I know you need to escape output when inside html not inside functions.

**Comment by elbisnero** [comment]
Looking to have a theme developed using the Unyson framework. I need someone experienced with this framework, anybody wants to collaborate with me?

**Comment by duongancol** [comment]
Can you give me a brief intro about your project?

**Comment by elbisnero** [comment]
Please contact me directly at my email laptop.center@yahoo.com so I can provide you with the details of what I need done. Thanks.

**Comment by danyj** [comment]
@moldcraft , @elbisnero , @duongancol  sorry but this is definetly wrong post for these things guys , 
we check this one for TF approvals,  please remove those posts and open different one for job posting

**Comment by elbisnero** [comment]
@danyj The comments have been removed. I apologize for the inconvenience but this was the only thread where I could find developers experienced using the Unyson framework. Where can I post a job for only Unyson developers? I am not interested in using another framework. Thanks in advance!

**Comment by duongancol** [comment]
maybe you should create a new issue if it's a public job.

**Comment by Ataurr** [comment]
@danyj @duongancol @2Fwebd @ivandotv  I think We should create a slack channel. So we can discuss share improve our products.

Others Framework has the channel like redux, elementor, cornerstone and so on. 

What do you think ?

**Comment by danyj** [comment]
@Ataurr , I think we had slack and one more 2 years ago , did not have much attention

**Comment by GheorgheP** [comment]
@danyj @duongancol @2Fwebd @ivandotv, plase provide your email addresses and we will add you to our slack channel.

**Comment by andreiglingeanu** [comment]
@danyj Now slack is more active.

**Comment by 2Fwebd** [comment]
Hey guys! :) 

help[at]2f-design.fr
mangiacapra.antonio[at]gmail.com

**Comment by danyj** [comment]
@GheorgheP   thx!  themezly@gmail.com

**Comment by Ataurr** [comment]
starxpeed@gmail.com

**Comment by andreiglingeanu** [comment]
Invites sent!

**Comment by ivandotv** [comment]
@andreiglingeanu ikixxx\\over\\gmail.com  (replace \\over\\  with you know what)

**Comment by duongancol** [comment]
@GheorgheP mine mr.duongancol[at]gmail.com 
ty!
anyway, long time no see bro, did you come back?

**Comment by GheorgheP** [comment]
Hi, 

I was working in ThemeFuse Technical Support Department.

But now, I'm back.
![](https://media.giphy.com/media/yj5UdA4elp8Wc/giphy.gif)

**Comment by duongancol** [comment]
<img src="https://media.giphy.com/media/l0MYC0LajbaPoEADu/giphy.gif"/>
