### ISSUE TITLE
[Discussion] Community Extensions

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#955]
I know not only I and but also other developers (@2Fwebd) want to share them own extensions that built on extension framework. 
So @moldcraft : what do you think about Comunity Extension? What is plan? How developer could share it? How user could download and learn to use?,...

**Comment by moldcraft** [comment]
As plugins on wordpress.org ?

**Comment by duongancol** [comment]
Yes, it's uploaded on Github, and is listed in Extensions page

**Comment by moldcraft** [comment]
So create a plugin and upload it on wordpress.org

If the extension will be really something good and useful, I think we can add it in this list (or create a new list below) https://github.com/ThemeFuse/Unyson#extensions

**Comment by duongancol** [comment]
So after it's approved on wordpress.org, they have to push you?

**Comment by moldcraft** [comment]
Yes, share the like somewhere here in issues

**Comment by duongancol** [comment]
ok, maybe it's the best way now but still waiting other ideas

**Comment by c0sm1n87** [comment]
I would be interested in your extensions if you don't mind :)

**Comment by danyj** [comment]
Nice post but why are we stopping at extensions only? I have option types that work magic and once we are live I will gladly share.

**Comment by duongancol** [comment]
@danyj I think option type should be add to core for all users, Extensions is bigger, the developer or user will decide which one is used in theme. 
@c0sm1n87 : I'm glad to share

**Comment by c0sm1n87** [comment]
@duongancol  I already emailed you few days ago, you should have my email in your inbox (it's the same that I have in this profile) . I'll patiently wait for them :)

**Comment by moldcraft** [comment]
P.S. **Important!** Please **prefix** all your extension and option type names.

**Comment by duongancol** [comment]
@c0sm1n87 I didn't get one

**Comment by c0sm1n87** [comment]
@duongancol I just resent it :)

**Comment by 2Fwebd** [comment]
Hi there, 

Here is the list of extensions developed for our theme (***Woffice***). They're all built with Unyson extensions following Unyson's documentation. Quick descriptions :  

* **Projects Manager Extension** : Create project with content / link / dates / comments / frontend edit,delete / tasks manager (managed by Ajax, with Email assignment, date, note, drag & drop...) / progress bar / widget / EventON sync... Well basically, It's a post type WITH A LOT of improvements and changes following Unyson framework. 
* **Wiki Extension** : Wiki post type (comment, revisions, frontend edit, delete option, like button, category, directory page, search, widget...)
* **Social Login** : Manage a Facebook (using another plugin) & Google (API files are in the extension) 
login/register buttons. 
* **Auto Updater** : Auto update the theme when there is an update available, it works with Envato API 
and a PHP file on our server. 
* **Users Map** : Use Buddypress Xprofile component and Geocoding API to create a map of all the users with picture/name/address and javascript show/hide action.
* **Birthdays** : Use Buddypress Xprofile component to create a Birthday field and them use this data in a widget to output the next birthday(s) (profile link, avatar, data, old...).
* **Poll** : Create a Poll widget powered by Ajax, with results tab in the extension's settings, unlimited options... 
* **Cover image** : Buddypress cover image powered by Ajax
* **Funfacts** : Create a Fun facts widget, just a slider (Flexslider) with icon/text/title to create some eye-catching messages
* **Maintenance page** : Create a Maintenance page with a lot of settings. It redirects all the users to this maintenance page once turned on.
* **Directory items** = Create a directory page with a map / search form. Each item has unlimited features (icon/name), content, category, thumbnail, location, link...

Sorry for the bad english and the lack of details ...

**Well, WE WILL publish them for free in a private repository pretty soon. We just need to get some stuff done before.** BUT if you need them before that and you don't need our documentation, feel free to email me at **contact[at]alka-web.com**, I'll send you the extensions files you need right after BUT I won't be able to provide support on them for now :/

See http://alka-web.com/woffice-theme/#behind for screenshots. 

Good news :
* All is commented
* We're working on them 7/7
* We're using prefixed functions
* We want to make them open source ! 

Bad news : 
* I (I used "we" before because I'm no longer alone on this project) created all the extensions BUT I'm not a developer (well I'm pretty good with PHP :) But I'm better with HTML, CSS and design stuff). SO, you may see some weird things as a backend developer BUT all of them are working and used by 1200+ users. 
* Most of them are directly called in the theme files, so I think it'll be better to document them before.

Seriously, most of them may not fit in your theme but you can use our work to create other extensions based on them. We have been playing A LOT with Unyson and there is A LOT of hours in these extensions so feel free to use them for your own project ! 

@moldcraft if you need any of them or any access to see the backend, don't hesitate to get in touch, I'd be glad help making Unyson an even better framework. 

2F

**Comment by danyj** [comment]
bravo @2Fwebd  :100: 

what I would like to see is Auto Update, I think we were waiting on it since Jan and Unyson team did not get a chance to get to it.

**Comment by c0sm1n87** [comment]
Thanks for the list, i will email you when i get home about some of them. Dont worry, i dont judge :) i m kinda new to wp, i started when i found this framework due to the fact that this mvc somehow resembles joomla's

**Comment by duongancol** [comment]
@2Fwebd :+1: 
@moldcraft I think the better way is we have Comunity Extension page that developer could upload them own extension with name, description, GitHub URL. After it's approved, it'll be listed here: http://manual.unyson.io/en/latest/extension/introduction.html#content
It's more convenient because they don't have to create an issue when they have a new extension to share. Please consider when we have more developers and extensions. 
@c0sm1n87 you probably send to wrong email

**Comment by c0sm1n87** [comment]
@duongancol i used the email attached to your git profile mr.duongancol at gmail.com

**Comment by moldcraft** [comment]
@duongancol Sorry, we can't accept any extension that easy. We need to analyze it. But now we don't have time for such things, we have a lot of issues to fix. At the moment, instead of adding more extensions, we cut them https://github.com/ThemeFuse/Unyson/issues/874

There should be a place for you, theme developers, to share new extensions, ideas for extensions, we will look at all this activity and, at some point, maybe decide to add one of those extensions in Unyson official list, but these things will not be as fast as you expect.

**Comment by c0sm1n87** [comment]
@2Fwebd I emailed you regarding your extension list :) :100:

**Comment by 2Fwebd** [comment]
@danyj I didn't had much time to polish it but most of it is here : https://github.com/2Fwebd/woffice-updater 

@c0sm1n87 I'll reply in a minute ;)

**Comment by moldcraft** [comment]
> @2Fwebd 
> https://github.com/2Fwebd/woffice-updater
> the Unyson extension that **you need to use in your theme's files** (framework-customizations/extensions/)

Why setting that requirement? Why not load it from a plugin? http://manual.unyson.io/en/latest/extensions/introduction.html#custom-load-locations

**Comment by moldcraft** [comment]
P.S. Sorry for promoting JetBrains products, but I want to say that you can use the [PhpStorm](https://www.jetbrains.com/phpstorm)'s '[Code Reformat](https://www.youtube.com/watch?v=xIxDar8CbJA)' function to arrange the code better https://github.com/2Fwebd/woffice-updater/blob/f5b5e3a05f14d524550c89e718ac064f112a70d9/server/theme-updater.php

**Comment by 2Fwebd** [comment]
@moldcraft, Ok I've missed that filter.. just added to our roadmap indeed that can be REALLY useful, thanks ! Regarding this repository, it's just some files from our theme but I'll definitely add more documentation in the next days

**Comment by 2Fwebd** [comment]
Thanks for the trick, I'll have a look ;)

**Comment by moldcraft** [comment]
No problem, just pointing what I notices after fast looking through it.

We are very thankful for your openness!

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/6#issuecomment-163635694 by @2Fwebd
>
> I'm sorry I didn't had the time to work on the documentation for our extensions and the Github reps. I'm know it's not perfect coding (as I'm not a back-end developer but they work). But here are the extensions we're using available for any Unyson theme developer who want to use some of them as inspiration or whatever : https://woffice.io/extensions/ I will write some documentation but I can't know. If anyone as any question, just get in touch at contact[at]alka-web.com
(I'll try to update theme regularly as we're making A LOT of changes everyday).

**Comment by danyj** [comment]
:+1:  @2Fwebd  that's a spirit. Cant wait to publish ours.

**Comment by andreiglingeanu** [comment]
Every extension can also contain it's option types or even container types! So, there's unlimited possibilities in there for anyone!

**Comment by 2Fwebd** [comment]
Yes, by the way, for everyone looking at https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/6#issuecomment-163635694 

My update policy was a big failure as I never had any minute to update those extensions on our site. HOWEVER they're updated on every theme update on our side (so A LOT). So if you need them, just shoot me an email so I can send you the latest version ;) 

Cheers !

**Comment by dobromir-hristov** [comment]
What happened with the sharing idea?
I also have some option types that I would like to share as well.
Maybe we create something like a curated list, like most JS frameworks have these days, `Awesome Vue` for example. 
The `url-picker` I did back in the days with Moldcraft still works beautifully, and is so much better than a simple text input :)

**Comment by andreiglingeanu** [comment]
> Maybe we create something like a curated list

I like the idea. Something like `awesome-unyson`

**Comment by dobromir-hristov** [comment]
There should be some guidelines on how a package should be added. Should we use the `theme-customizations` structure or just add the package/extension to a repo and give some basic guides on how a user should implement it?

**Comment by duongancol** [comment]
Just's my suggestion:

1. Add a Community Extension list somewhere in manual.unyson.io that display all extensions from the community. The developer who wants to contribute an extension can send @moldcraft an email or push it here. Then he chooses to add extension to the list
2. Add Community Extension tab [here ](http://take.ms/Vx6Af). 

Note: 
@moldcraft  doesn't have support or any responsibility for community extensions. So We have to add this note in Community Extension tab

Community extensions should be added as a plugin 

The last thing, theme author can choose extension from community list that's compatible or not. If yes, they should be added to extension installation process.

**Comment by danyj** [comment]
Pushing it here would require Unyson team to check the validity of code and also be responsible for it since everything would look like under one "roof".  A list of developers repos containing the extensions would be better I think.  A Unyson github Wiki page could be used for the list.

**Comment by andreiglingeanu** [comment]
I _don't_ like the idea of including something in the core UI (like @duongancol said about _Community Extensions_). I think a better categorization of the extensions is welcome - just like we have for shortcodes and they divide per tabs.

<hr>

> A list of developers repos containing the extensions would be better I think. A list of developers repos containing the extensions would be better I think.

Good idea, except the fact that I'd rather prefer to create a separated repo - like `themefuse/awesome-unyson` where the links will be added into the `README.md`, just like [`sindresorhus/awesome`](https://github.com/sindresorhus/awesome) project. The main benefit of that is the fact that anyone can comeup with a pull request to add their contibution (be it an extension, option type or whatever idea/article/trick you can think of). The list should be curated and trash should be filtered off of it.

**Comment by duongancol** [comment]
@2Fwebd the link doesn't work http://alka-web.com/woffice-theme/#behind

**Comment by 2Fwebd** [comment]
@duongancol sorry about that, we moved things around since 2 years. Description can be found at https://woffice.io but there isn't the old "extensions list" as before. Feel free to email us with what you need though.
