### ISSUE TITLE
[question] Wordpress dashes issue

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#992]
@moldcraft  I cant find the post now but I know that there was something about WP and -  in option types. Can you provide a link to info about this. 

I am working on an option type and would like to use 

       'buttonclass'  => 'this-is-class-name '

instead 

    this_is_class_name 

so just a hint how WP handles this would be great since I need to know if this pertains to  just option type  names  and not option values . 

Thank you!

**Comment by moldcraft** [comment]
The only thing I remember is that when you use - in option id and you want to use that option in javascript template in `addable-...` options, then you will get js error because it tries to create a js variable from that name.

Also in shortcode option ids are transformed in shortcode attributes `[shortcode option_id="..."]` and [this page](https://codex.wordpress.org/Shortcode_API#Attributes) says

> Attribute names are optional and should contain only the following characters for compatibility across all platforms:
> ...
> * Hyphen: - (Not allowed before version 4.3.0)

I don't remember any other problem.

**Comment by danyj** [comment]
thank you!!
